### ISSUE TITLE
Does QPDF decrypt encrypted PDF automatically when manipulating it even without prair manual --decrypt ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#342] opened 2019-07-04 05:52 UTC
Hi. 

1) QPDF seem to be automatically decrypt an encrypted PDF when manipulating it (rotate, delete, ........) EVEN without decrypt this encrypted PDF manually by the command:

qpdf --decrypt input.pdf output.pdf

see the following issue that opened by me on PDF Slicer (a frontend for QPDF) GitHub repository (my user name is Nokia808):

https://github.com/junrrein/pdfslicer/issues/102

I was 1st believed that the cause was that the encrypted PDF was not fully encrypted - see my last comment. But latter on I created FULLY encrypted PDF using a Windows advanced pdf editor called PDF-XChange editor plus, in such away no any editing process or copy procces allowed at all. Then I tried PDF Slicer to delete page 2 of this fully encrypted PDF. PDF Slicer deleted page 2 correctly & created a new PDF that is completely non-encrypted, inspite the fact that I did not remove encryption from this encrypted PDF by "qpdf --decrypt input.pdf output.pdf" command !  Does this a normal behavior or it is a bug ?

I attached with this email 2 PDF files:
1st one is named "original.pdf" which is the FULLY encrypted PDF that I created.
2nd PDF (nammed "after-deletion.pdf") is the output non-encrypted PDF that resulted from deletion of page 2 by PDF Slicer,

[original.pdf](https://github.com/qpdf/qpdf/files/3357996/original.pdf)

[after-deletion.pdf](https://github.com/qpdf/qpdf/files/3357998/after-deletion.pdf)

2) in previous versions of QPDF when I was used QPDF wrongly to decrypt already non-encrypted PDF using "qpdf --decrypt input.pdf output.pdf" then QPDF gave me error message said that the PDF is not encrypted.
But now, on version 8.4.2 (installed from official Fedora repositories) QPDF will create output PDF inspite the fact that the PDF that applied on which "qpdf --decrypt input.pdf output.pdf" command is already NON-encrypted !
Is this intended behavior or it is a bug ?

Many thanks for your hard efforts !

**Comment by jberkenbilt** [comment] 2019-07-05 21:52
I will look at this a little more closely, but from the library standpoint, the default behavior when you create a `QPDFWriter` object is to preserve encryption parameters from the `QPDF` object that is being written. Depending on how the client code is implemented, the effect may be to decrypt a file or not. It is possible to explicitly copy encryption parameters from one file to another. For example, if PDF Slicer creates a new empty QPDF object and adds pages from an original file and then writes the new object, unless it explicitly copies encryption parameters (with `QPDFWriter::copyEncryptionParameters`), the resulting file would be decrypted.

Regarding decrypting an already decrypted file, I don't think this has ever been an error, but maybe you're right. I don't see anything in the ChangeLog about it and don't remember having made that change. Right now, specifying `--decrypt` simply turns off the default behavior of preserving encryption. Anyway, whether or not it differs from before, that is the intended behavior.

**Comment by jberkenbilt** [comment] 2023-12-29 16:48
Sorry, this is very old, and I am unable to understand what workflow appears to be decrypting files. I am going to close this. Note the `--copy-encryption` option that would enable you to reapply encryption from one file to another if some workflow is causing the encryption to be dropped.

**Closed by jberkenbilt** 2023-12-29 16:48 UTC
