### ISSUE TITLE
Windows Defender Trojan:Win32/Zpevdo.B detected in qpdf-10.3.2-bin-msvc32.zip

### ISSUE THREAD

**Issue by nicolausdewitt** [qpdf/qpdf#533] opened 2021-06-03 15:57 UTC
I am trying to download the qpdf-10.3.2-bin-msvc32.zip release, but I keep getting an error from windows defender saying that it has detected "Trojan:Win32/Zpevdo.B".

Not having the problem with the 64-bit version from 10.3.2, and not having that same problem on 10.3.1.

Any idea why this might be flagging up?

**Comment by jberkenbilt** [comment] 2021-06-03 16:52
No, I have not seen this with the binary distribution. In the past, some test files in the source distribution would trigger some virus checkers because there were some invalid PDFs in the test suite that matched some signatures. I haven't seen anything like that in the binary distributions. Did you happen to check the signatures or checksums? Where did you download from? The sha256 of that file should be `c546b1ba7cff79b55d4b153fcd44a31f86534ead913132a2a4445dfc2875670e`.

**Comment by nicolausdewitt** [comment] 2021-06-03 21:07
I downloaded directly from the release page. We have some pretty aggressive new firewall rules at work, I can check some more tomorrow.

**Comment by jberkenbilt** [comment] 2021-06-03 22:04
Okay, if you find out exactly what's going on, I'd be interested to know in case there's something I can do about it.

**Comment by nicolausdewitt** [comment] 2021-06-04 09:33
It seems to be the fix-qdf.exe file that is causing the flag. There are apparently 15 vendors flagging it as suspicious on virustotal.com - https://www.virustotal.com/gui/file/3f153e9b183d4e75111c0adb78c3590afa006ed14f39a525b1a344dc36c99bc4/detection

**Comment by jberkenbilt** [comment] 2021-06-04 11:29
@nicolausdewitt This is helpful information. I'm not sure what to do though...I can rebuild and replace that zip file and see if the new version fares any better. Searching around on this, it seems this particular "virus" gets a lot of false positives as do some of the other ones virustotal is reporting. I'll need to educate myself a little more on what, if anything, I can do to prevent this or whether I'm just at the mercy of the antivirus engines. I have never seen virustotal before and don't know whether it's common for certain antivirus engines to be clustered together with false positives. I suspect a lot of packages use similar algorithms or heuristics. I'll have to study this.

In any case, it strikes me as extremely unlikely that there is actually a problem with it, unless something contaminated the build within GitHub actions. If in doubt, you can try one of the other binary distributions (unless you specifically need msvc 32-bit) or build it from source.

I'll try the rebuild thing and see if it helps. I will have to try to find a Windows system to test with, but that should be manageable.

**Comment by nicolausdewitt** [comment] 2021-06-04 12:59
@jberkenbilt I have no doubt it's a false positive, can't see how it wouldn't show up on the other builds from the same source if not. Sadly, I'm also at the mercy of our corporate firewall - the whole IT team got sent an email when I tried to update from version 8.x! :)

Microsoft have a link where you can submit a file you think has been incorrectly classified as malware for windows defender - https://www.microsoft.com/en-us/wdsi/filesubmission

I also noticed on the microsoft defender screenshot sent back from my IT team that it said the exe was unsigned. I noticed these guys (https://github.com/stride3d/stride/issues/285) got the same false positive assessment, and they were saying it was mainly because it was unsigned.

I hope that helps a bit, if there's anything else I can provide let me know!

Thanks for picking this up so quickly, it's appreciated.

**Comment by jberkenbilt** [comment] 2021-06-04 14:33
Thanks for bringing it to my attention. I saw lots of stuff about the executables being unsigned. I'll have to look into what that means, exactly. I am not a Windows person. I've spent my entire software development life (which goes back over 35 years, before Windows existed) in non-Windows environments and know only enough to make qpdf work decently on that platform. I'll figure out what someone needs to do to be able to sign stuff, and whether whatever that is is available to individuals doing open source software. I'll see if I can reproduce this and get it resolved. Thanks again.

**Comment by nicolausdewitt** [comment] 2021-06-04 15:24
Well qpdf certainly works well on windows as far as my experience goes, so you are definitely doing something right there! :)

It's really easy to get stuff signed in visual studio, you just select a certificate from the store and it signs it with signtool.exe on publish. The more difficult part is getting a valid cert. Most of my stuff is just published internally so we just generate our own certs.

There do seem to be some linux alternatives, these couple of links might help get you a headstart:

This looks like a decent linux version of signtool:
https://github.com/mtrojnar/osslsigncode

It's mentioned on this question on SO:
https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros

Sigstore, from the Linux Foundation might be a nice way to get a free dev cert, they don't appear to be live quite yet though.
https://sigstore.dev/what_is_sigstore/

I guess that's all under the assumption that signing it will actually make a difference but who knows. Cheers again, have a nice weekend.

**Comment by jberkenbilt** [comment] 2021-06-04 15:35
I rebuilt this in GitHub again, and for whatever reason, the new one doesn't fail. I was able to reproduce the error with the old one on my Windows VM. I will replace the zip file with a new one, which I guess I will call `qpdf-10.3.2-bin-msvc32-rebuild.zip` and will update the signatures, etc. I will also look into signing and submit the false positive. Thanks for all your helpful information.

I'll look into the signing. I do all my existing gpg signing after the fact because I don't want to deal with private keys in CI. I'm not sure it will be needed though or whether it would actually help. I guess I can eventually see if I can sign the one that's generating the alert and see if it helps. We'll see. Anyway, I'll put up the new binary distribution momentarily on github and sourceforge and post to qpdf-announce@lists.sourceforge.net when I've done it. I'll leave this open for now as a reminder to look into the signing and so forth.

Thanks again for bringing this to my attention.

**Comment by jberkenbilt** [comment] 2021-06-04 16:46
You can find a new version at https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2-bin-msvc32-rebuild.zip

Hopefully this one works.

**Comment by jberkenbilt** [comment] 2021-06-04 16:53
Note to self: remaining actions: investigate code signing to decide whether it's something I need to do and, if so, how to do it.

**Comment by jberkenbilt** [comment] 2021-06-04 21:33
Microsoft has already come back to say that this was in fact a false positive and that the next update of the definitions will not continue to flag this. I'm not sure about the other 14, but at least we got that confirmation.

**Comment by jberkenbilt** [comment] 2021-11-02 20:31
I'm going to go ahead and close this. I don't think I'm going to go to the trouble of code signing for Microsoft.

**Closed by jberkenbilt** 2021-11-02 20:31 UTC
Labels: next
