### ISSUE TITLE
average filter not implemented

### ISSUE THREAD

**Issue by rhedge** [qpdf/qpdf#83] opened 2016-07-19 00:37 UTC
This message appears when trying to merge certain PDFs. Not sure exactly what is causing it in the PDF. Is there a way to continue merging and ignore this error? If i have many files to merge, this will stop the whole process, even if just 1 file has the issue.

cheers

**Comment by jberkenbilt** [comment] 2016-07-19 16:31
The next time I have a chance to work on qpdf, I want to make it much more robust about recovering from this type of error, but I'm not sure exactly when that's going to be. qpdf started its life as a PDF checker, and there are still a few cases where it errors out on conditions that it could safely ignore. I wish I had a better answer for you. If you have a file you can share that's okay to include in the test suite, it would help. Alternatively, if you have a file I can use privately for testing but not include in the test suite, I may still be able to figure out what is causing the failure and reproduce it in some other way. If not, hopefully the work I'm already planning to address this general class of problem will help.

**Comment by rhedge** [comment] 2016-07-25 05:39
Hi,

I will try and get permission to send a couple of the files for private testing. Should I just email through?

 

thanks

**Comment by jberkenbilt** [comment] 2016-07-25 14:11
Email is fine. No guarantees that I will get to it soon, but I am hoping to find some time to catch up on some of the recently reported issues. Thanks.

**Comment by smilingthax** [comment] 2017-08-19 18:41
Well, the biggest problem seems to be that `QPDF_Stream::pipeStreamData` will accept `predictor==12` (also in `QPDF_Stream::understandDecodeParams`), and then tries to filter the stream (as long as /Color and /BitsPerComponent are not set as DecodeParms, i.e. their values are the defaults 1 resp. 8), but the PDF specification still allows all other PNG predictors to be used inside the stream (specified per row as byte 0 of each row), /Predictor 10...15 are all treated the same on decoding, the differ only on encoding.

So the low hanging fruit would be to implement the remaining PNG predictor decoding function, but still only support encoding as UP predictor (and also still not support encoding/decoding of TIFF prediction). Then simple PDF transformations would not fail any more, just because the input file contains a compressed stream with non-UP encoded rows...

More specifically, in
  https://github.com/qpdf/qpdf/blob/master/libqpdf/Pl_PNGFilter.cc#L74
add three formulas for Sub, Average and Paeth; don't forget to update the NOTE in Pl_PNGFilter.hh.
Also, `pipeStreamData` currently passes 0 as `bytes_per_pixel` to `Pl_PNGFilter`'s ctor, but for the only currently possible case of `colors==1` and `bits_per_component==8`, the correct value, `1`, has to be passed, because (e.g.) Sub needs `cur_row[i]` and `cur_row[i-bytes_per_pixel]`. The difficulty lies in reading a `0` when `i < bytes_per_pixel`.
(My own implementation in unpdf [(here)](https://github.com/smilingthax/unpdf/blob/master/unpdf/libnpdf/filter/pdffilter.cpp#L767) uses `thisline`/`cur_row` with `bytes_per_pixel-1` additional zero-initialized bytes at the beginning ("before the beginning"). It then extracts the `filter` number from "`cur_row[0]`" and overwrites that value in cur_row with another 0, resulting in `bytes_per_pixel` zeros before the actual row data; this obviates the need for special-casing `i < bytes_per_pixel`).

I've created a special test pdf that contains these relevant cases:
[test_qpdf.pdf](https://github.com/qpdf/qpdf/files/1235798/test_qpdf.pdf)

It wouldn't be too difficult to extend `understandDecodeParams` to also allow `/Color` and `/BitsPerComponent` in the DecodeParms of a FlateFilter, and calculate `bytes_per_pixel` from these. It would then also be possible (but maybe not desirable, as the encoder only reencodes with UP...) to decode when the `/Predictor` value is not only 12 (or 1), but 10...15. In that case I have some more test images:
[test_all.pdf](https://github.com/qpdf/qpdf/files/1235850/test_all.pdf)
(using `/Predictor 15`; this value might have to be changed with an editor to `12` for each image ...)

**Comment by jberkenbilt** [comment] 2017-08-20 04:01
@smilingthax Is this blocking any current projects? I agree that it would be pretty easy to fix. Maybe I can work it in.

**Comment by smilingthax** [comment] 2017-08-20 13:22
I don't have any immediate needs. I've been fixing some bugs in my own unpdf project and had some spare time to generate pdfs to test that particular area. 

From a more general perspective, it's quite unfortunate to have a perfectly valid pdf fail in libqpdf, though. `qpdf test_qpdf.pdf out.pdf` will not work; pdftopdf is also unable to process the file (qpdf's `--stream-data=preserve` option helps, and that workaround could also be added to pdftopdf...).

**Comment by jberkenbilt** [comment] 2017-08-20 22:11
If you can provide sample files it would be a big help. The spec is simple on this though. It's not much work.

**Comment by smilingthax** [comment] 2017-08-20 22:15
The sample files are behind links in my first comment ([test_qpdf.pdf](https://github.com/qpdf/qpdf/files/1235798/test_qpdf.pdf) and [test_all.pdf](https://github.com/qpdf/qpdf/files/1235850/test_all.pdf)).

**Comment by jberkenbilt** [comment] 2017-08-20 22:24
Also qpdf 7 and current master already now will automatically process streams without filtering if the filtering fails for any reason.

**Comment by jberkenbilt** [comment] 2017-08-20 22:25
Yeah, I see them now. Thanks. :-)

**Comment by jberkenbilt** [comment] 2017-08-30 13:05
Note to self: saved the files in misc/bugs/83

**Comment by jberkenbilt** [comment] 2017-11-27 21:43
Someone has submitted a pull request that implements the rest of the filters: #166 
I will study it and incorporate it next time I have a chance to work on qpdf.

**Comment by jberkenbilt** [comment] 2017-12-25 23:44
This is fixed in master now and will be in qpdf 7.1.0.

**Closed by jberkenbilt** 2017-12-25 23:44 UTC
Labels: next
