### ISSUE TITLE
Ability to copy form fields (and annotations in general?) when copying pages

### ISSUE THREAD

**Issue by junrrein** [qpdf/qpdf#437] opened 2020-04-26 03:45 UTC
Let me start by thanking your for developing this app and library. I use it in a simple GUI for editing PDFs I'm developing, where QPDF is doing all of the actual work.

I couldn't find in the documentation any clear reference as to whether it's possible to copy a page from one file to another while preserving any form fields that are present. From crawling through the issue list and the source code it seems this isn't possible, but I'm not sure.

**Comment by jberkenbilt** [comment] 2020-04-26 23:12
You could do it, but you'd have to do a lot of work. However, this is by far the most requested feature, and it's probably the next significant non-performance-related enhancement I will work on. I'm not sure exactly when I will get to it since qpdf is mostly a side project.

Right now, depending on the nature of what you're doing, it is possible to copy the entire AcroForm and Annotations dictionaries from one file to another, after forms will work on any page you copy, but this brings a lot of extra stuff around, and for large files, it is very inefficient. What I intend to do is to actually process the form and annotation information so that qpdf knows which ones are relevant for which pages, at which point I can do something intelligent. This is part of a general pattern of qpdf not preserving document-level structures when copying pages. There are several open issues here tagged with "pages". Most likely, when I get to this, I will close this issue as a duplicate, but right now I don't feel like spending the time to find which issue that would be . :-)

So, for now, the functionality is not there, but hopefully it will come in the not too terribly distant future.

**Comment by jberkenbilt** [comment] 2020-04-26 23:14
By the way, I do occasionally get requests for a qpdf GUI, but it's not something I'm inclined to write. Depending on the nature of what you're doing, let me know if there are things the library can do to help you. I have made some modifications to the library to help people who are using it in particular ways, including supporting people who are calling qpdf from other languages.

**Comment by junrrein** [comment] 2020-04-27 02:10
> (...) this is by far the most requested feature, and it's probably the next significant non-performance-related enhancement I will work on. I'm not sure exactly when I will get to it since qpdf is mostly a side project.

I'm glad to hear this, and I completely understand that this will get done "whenever it gets done".

> Right now, depending on the nature of what you're doing, it is possible to copy the entire AcroForm and Annotations dictionaries from one file to another, after forms will work on any page you copy, but this brings a lot of extra stuff around, and for large files, it is very inefficient.

Thanks for explaining this option, since I'm not well versed in the PDF format. Even if it's inefficient, it's an available option.

> Most likely, when I get to this, I will close this issue as a duplicate

I don't mind you closing this issue right now. If I could humbly request something, is making the fact that "a high-level interface for copying metadata and annotations between files is not provided at the moment" more apparent in the documentation.

> Depending on the nature of what you're doing, let me know if there are things the library can do to help you. I have made some modifications to the library to help people who are using it in particular ways, including supporting people who are calling qpdf from other languages.

This is really generous of you, thanks! My app is written in C++, so there won't be any issues in that front. But if I'm finding myself wishing for some specific interface, I'll file another issue.

**Comment by jberkenbilt** [comment] 2020-04-27 02:23
I'll leave this open as a reminder to make this clearer in the docs. That's a good suggestion. It's hiding in there, but not very clearly.

Thanks for the report and the feedback.

**Comment by jberkenbilt** [comment] 2021-02-18 15:25
This is going into 10.2.

**Comment by jberkenbilt** [comment] 2021-02-18 15:28
Closing as duplicate of #395.

**Closed by jberkenbilt** 2021-02-18 15:28 UTC
Labels: next, pages
