### ISSUE TITLE
No longer able to use "--" to terminate option flags

### ISSUE THREAD

**Issue by h3xx** [qpdf/qpdf#652] opened 2022-02-15 18:15 UTC
`qpdf` no longer allows standard GNU-style termination of option lists by using a `--` indicating that anything after is NOT supposed to be an option flag. For example using the filename `-in.pdf`:

```sh
qpdf --compression-level=9 -- -in.pdf out.pdf
```
This results in an error:
```

qpdf: unrecognized argument --

For help:
  qpdf--help=usage       usage information
  qpdf--help=topic       help on a topic
  qpdf--help=--option    help on an option
  qpdf--help             general help and a topic list
```

This is expected to treat all arguments after the literal `--` as filenames, like it did at the time of release 10.5.0.

Doing a `bisect`, I believe this was a regression introduced in ac0060ac38ecf4fa380f49fd1e40ebaabb479596.

The help message is also wonkily-formatted.

**Comment by jberkenbilt** [comment] 2022-02-15 18:55
Treating all arguments after `--` as non-options was never intended and was never implemented. What was in fact happening (which I didn't even realize) was that `--` was simply ignored except when used to terminate subparsers (`--pages`, `--encrypt`, and a few others). Note that qpdf does not follow gnu argument conventions.

I'm not sure whether I should re-introduce the unintentional behavior of ignoring `--` as it was never documented behavior. I didn't even know it did that, actually.

**Comment by jberkenbilt** [comment] 2022-02-15 18:56
What seems wonky to you about the help? It looks as intended to me. Can you point out what specifically you see as wonky? Note that, as with CLI, there is no intention to conform to gnu conventions.

**Comment by jberkenbilt** [comment] 2022-02-15 18:56
If it turns out that people were relying on this behavior, I will probably have to release 10.6.2 with an immediate fix.

**Comment by h3xx** [comment] 2022-02-15 19:08
What's wonky about the help message is that it tells you to run `qpdf--help=usage` which isn't a valid command. It should be `qpdf --help=usage`. There's a missing space.

**Comment by jberkenbilt** [comment] 2022-02-15 20:37
I am fixing both issues and releasing it as 10.6.2 along with another fix that is needed for pikepdf, so you can expect this to be fixed in the next day or two. Thanks for reporting it. I honestly had no idea qpdf was ignoring a bare `--` at the top level of arg parsing, and I guess I lost the functionality when I completely refactored argument parsing.

**Comment by h3xx** [comment] 2022-02-15 20:41
No problem-o. Thanks for responding so quickly. 🥇

**Closed** 2022-02-15 21:48 UTC
Labels: bug, next
