### ISSUE TITLE
When converting pdf to json, the Chinese font name is garbled

### ISSUE THREAD

**Issue by baipzy123** [qpdf/qpdf#1072] opened 2023-11-24 11:36 UTC
When converting pdf to json, the Chinese font name is garbled
qpdf --json-output test.pdf out3.json
"obj:8 0 R": {
    "value": {
     "/BaseFont": "/FPWNDA+    ",
"obj:14 0 R": {
     "value": {
     "/BaseFont": "/FPOHHT+      ͤ ڼ   "
[test.pdf](https://github.com/qpdf/qpdf/files/13458545/test.pdf)
,

![2023-11-24](https://github.com/qpdf/qpdf/assets/129270920/e7a6201e-cf0c-448d-8c37-0a5a0cc14bd4)

**Comment by jberkenbilt** [comment] 2023-11-24 12:59
The problem is that QPDF JSON doesn't properly encode PDF name objects that contain non-Unicode characters. Somehow I managed to overlook this possibility. I'll get this fixed.

**Comment by jberkenbilt** [comment] 2023-12-21 21:57
Starting with qpdf 11.7.0, any name whose canonical form is not valid UTF-8 will be represented as `n:` followed by the name in PDF syntax. This doesn't break compatibility because strings starting with n: are not currently valid, and json output by qpdf < 11.7.0 in this case will be invalid JSON though qpdf json will still read it.

**Closed** 2023-12-21 23:54 UTC
Labels: bug, next
