### ISSUE TITLE
QPDF hangs when checking a file

### ISSUE THREAD

**Issue by fturco** [qpdf/qpdf#82] opened 2016-07-13 20:38 UTC
I found a PDF book that causes `qpdf` to hang when using the `--check` option:

```
$ qpdf --check x.pdf 
checking x.pdf
PDF Version: 1.6
File is not encrypted
File is not linearized
```

I can display this PDF with Evince without problems.

I can send you the PDF in private via e-mail if you need. Let me take note of its MD5 checksum so I can find it later: a0f55f383a740bd65b3c81d1226aff55.

Edit: I'm using qpdf-6.0.0-2 from Parabola GNU/Linux-libre.

**Comment by jberkenbilt** [comment] 2016-07-19 16:33
I would be interested in the file if you can send it privately. I have a private place where I keep test files that I can't redistribute, but often I can figure out what the root cause is and manually introduce the error in another file for testing.

**Comment by fturco** [comment] 2016-07-19 16:50
Sent via e-mail.

**Comment by jberkenbilt** [comment] 2016-07-19 16:55
Received, thanks, though I haven't attempted to decrypt it. I don't know when I will have a chance to look at it. Note to self: message 625087

**Comment by jberkenbilt** [comment] 2016-09-10 19:42
I was able to decrypt and reproduce the bug. I have not attempted to fix it yet, but I should be able to get to it before the next qpdf release. Note to self: qpdf/misc/bugs/82.pdf

**Comment by jberkenbilt** [comment] 2017-07-26 09:30
I have a fix for this that will be in the next version hopefully being released this summer. I will push the fix to master soon. The "endobj" keyword was embedded in a content stream erroneously, but qpdf shouldn't get tripped up by that.

**Closed** 2017-07-26 10:28 UTC
Labels: bug, next
