### ISSUE TITLE
[Feature Request] Overlay form fields

### ISSUE THREAD

**Issue by CampinCarl** [qpdf/qpdf#395] opened 2020-01-22 14:00 UTC
Would it be possible to add **form field** support to the `--overlay` option?

Use case example: First I programmatically generate a PDF document (from a template) which includes an approvals signature page. Then I overlay a mostly empty PDF with only the necessary digital signature form fields (matching the template positioning) to the signature page, creating the final document. In my testing, form fields are discarded by the overlay operation but other document elements work as expected.

I can achieve the same effect by using `--underlay` instead—that is, put the form fields page into the document and *underlay* the original page—but this results in broken bookmarks for that page.

I'm open to suggestions if there are better options. Thanks for the great utility!

**Comment by jberkenbilt** [comment] 2020-01-27 19:38
You're basically bumping into a known issue, which is that qpdf doesn't deal with document-level metadata very well when copying objects from file to file. What you've seen is that the form metadata exists in one file, and the outline (bookmark) metadata is in the other. Eventually I would like to make this work, and the TODO file has a bunch of notes about it. I'm not sure whether outlines or form fields will make the cut first, but if one gets supported before the other, your workaround of using `--underlay` instead of `--overlay` would be fine. However, since neither type of metadata is copied now, you are seeing the problem you've described. I've labeled with this with `pages`, which is the label I use for all issues that are related to qpdf's inability to move page-specific document-level metadata around. If/when I get around to addressing the root cause, then this issue should come along for the ride. Thanks, and sorry I can't give you a happier answer at this time!

**Comment by CampinCarl** [comment] 2020-01-27 20:15
No need to apologize; thank you for the context! I'll keep an eye out for any updates.

**Comment by CampinCarl** [comment] 2020-01-31 02:52
Quick follow-up on this, I figured out how to do what I need using the `--qdf` option and `fix-qdf.exe`!

Here's a brief summary in case anyone else might benefit; I can put something more verbose in a Gist if anyone is interested.

1. Convert source document to QDF, specifically `--qdf` and `--object-streams=disable`
2. Add an /AcroForm dictionary to the document catalog, points to signature field object(s)
3. Add an /Annots array to the signature page object, annotations reference signature field object(s)
4. Append signature field object(s) to the document
5. Recompose PDF (fix-qdf > qpdf > PDF)

One could adapt this procedure to add other form fields and annotations (really anything else) as needed.

By the way, **huge** thanks for adding a fix-qdf executable in [9.1.1](/qpdf/qpdf/releases/tag/release-qpdf-9.1.1); makes it viable for my project 🎉🎉🎉!

**Comment by jberkenbilt** [comment] 2020-01-31 03:30
Great, thanks for the follow-up. It's nice to see people benefiting from fix-qdf. Thanks for letting me know that having it be a stand-alone executable is a help.

Note that, since you know the procedure for doing this manually, you could also use the qpdf library to write code for your purpose. This could either be C++ code, or if you're into Python, you can use the pikepdf Python module. But I'm glad you have a method that works for you for now and that you took the time to share it in case anyone else sees this.

**Comment by Monyer** [comment] 2020-04-23 05:43
The same problem. 
Original command: `qpdf --overlay cover_with_field.pdf --repeat=1 -- simple.pdf output.pdf`
cover_with_field.pdf has 1 page
output.pdf has several pages, for example 10 pages.
The field had lost after ran that command

I had used an ugly way to fix it:
Copy cover_with_field.pdf to 10 pages by using pypdf
Then run command: `qpdf --underlay simple.pdf -- cover_with_field.pdf output.pdf`

**Comment by jberkenbilt** [comment] 2020-04-23 15:29
I don't have any immediate plans to work on this, but I believe I will have other reasons in the not-too-distant future to tackle form fields in a more much comprehensive way that I am doing now, and hopefully this can be included.

**Comment by jberkenbilt** [comment] 2021-02-18 15:28
@junrrein I'm closing #437 as a duplicate of this issue. I will be working this for 10.2.

**Comment by jberkenbilt** [comment] 2021-02-18 15:28
This is going into 10.2.

**Comment by jberkenbilt** [comment] 2021-02-20 21:00
Ugh, sorry for the false hope. This turns out to be quite hard to implement in the general case. I am not going to hold up 10.2 for it. It's easy for the simple case of just copying annotations, but handling the general case of all the different places where transformation matrices are being applied plus handling the case of copying the same page more than once or having different annotations share appearance streams gets really complicated. I will have to give this some more thought.

**Comment by jberkenbilt** [comment] 2021-02-21 14:28
Actually I got it working so it will go in for 10.2.

**Closed** 2021-02-23 00:30 UTC
Labels: enhancement, next, pages
