### ISSUE TITLE
repair broken pdf page structure

### ISSUE THREAD

**Issue by CanadianHusky** [qpdf/qpdf#398] opened 2020-02-08 16:02 UTC
The link below has a problematic file. The root pdf object points to an actual page.
The file can be opened fine by Adobe Acrobat and Foxit reader. Some other software cannot open the file at all.

I am attempting to repair the file structure by linearization with qpdf 9.1.1
I have tried decompression streams too.

qpdf --linearize "input.pdf" "output.pdf"

the response traps the error correctly
(offset 808): INTERNAL ERROR: QPDF::calculateLinearizationData: first page object not in lc_first_page_private

https://www.dropbox.com/s/ph4z7obfxpk38g5/input.pdf?dl=0

Is it possible for a future version of qpdf --repair (or similar) option to repair such a structure problem ?

thank you in advance. Great library

**Comment by jberkenbilt** [comment] 2020-02-08 16:55
Thanks for creating the issue here. :-)

I've grabbed your file and stored it locally (note to self: misc/bugs/398/input.pdf), and I am able to reproduce the problem. `qpdf --check` doesn't find any errors. I will study this in more depth to figure out what's going on and to see if qpdf can fix it, but in any case, I'm marking this as a bug because qpdf should never generate an INTERNAL ERROR like this. Thanks for taking the trouble to report and for sending the file.

The `next` label indicates that I intend to study this next time I work on qpdf, but it doesn't mean that I will necessarily fix it. I will make that assessment after I've studied the file.

**Comment by jberkenbilt** [comment] 2020-02-22 16:07
I haven't really addressed the linearization internal error directly, but I have added a few lines of code to detect the case of /Pages pointing to a page, to walk up the tree to try to find the parent, and to repair the /Pages pointer in the document catalog, which will allow qpdf to linearize this file. The fix will be in whatever the next qpdf release is (9.1.2, 9.2.0, or 10.0.0).

**Comment by CanadianHusky** [comment] 2020-02-22 16:10
Much appreciated. Thank you.
Just being able to read such a pdf structure and write back a corrected pdf
is sufficient, even if it is not linearized.

**Comment by jberkenbilt** [comment] 2020-02-22 16:12
It will be linearized. I'm saying the internal error catches a condition caused by the broken page structure. Rather than making the linearization code handle it, I'm detecting and repairing the broken page structure. The next qpdf release will be able to linearize this file.

**Comment by jberkenbilt** [comment] 2020-02-22 16:17
The test case I added actually linearizes a file broken in the same fashion as your sample, and I manually tested that my latest qpdf can linearize your test file. Thanks for providing it. :-)

(The file in the test suite is one I hand-modified to break in this way. I didn't include your test file...I never do that unless I can ensure the copyright is okay.)

**Closed** 2020-02-22 16:51 UTC
Labels: bug, next
