### ISSUE TITLE
10.4.0 install fail

### ISSUE THREAD

**Issue by Pro-pra** [qpdf/qpdf#592] opened 2021-12-07 22:38 UTC
libqpdf.lai does not exist
```
DEBUG: libtool: install: ./install-sh libqpdf/build/.libs/libqpdf.lai /builddir/build/BUILDROOT/qpdf-10.4.0-1.x86_64/usr/lib64/libqpdf.la
DEBUG: ./install-sh: libqpdf/build/.libs/libqpdf.lai does not exist.
```
I not have libqpdf.lai file:
`$ ls libqpdf*

libqpdf.la
`

**Comment by jberkenbilt** [comment] 2021-12-10 17:19
I am not familiar with lai files. You haven't indicated what platform, compiler, etc. you are using.

**Comment by jberkenbilt** [comment] 2021-12-17 21:03
I'm going to close this, but if you find out what's going on and need more assistance, please feel free to reopen.

**Closed by jberkenbilt** 2021-12-17 21:03 UTC

**Comment by leleliu008** [comment] 2022-08-12 16:44
I'm facing same problem too. This problem is caused by cross-compiling. something error leads to `libqpdf/build/.libs/libqpdf.lai` is not generated.

**Comment by jberkenbilt** [comment] 2022-08-12 19:28
I hope to get qpdf 11 out in the next few weeks. Its build has been completely redone with cmake, which should eliminate this kind of issue. I don't have any intention of fixing any problems with the pre-cmake build at this time.

**Comment by leleliu008** [comment] 2022-08-12 19:28
It seems that `--disable-shared` options leads to this problem, I use `--enable-rpath` to resolve this problem. Although it is strange, but it works. `ltmain.sh` has problem, if no rpath is given, the `libqpdf/build/.libs/libqpdf.lai` will not be generated.
