### ISSUE TITLE
fix-qdf outputs small file with only object in it

### ISSUE THREAD

**Issue by HazelHex** [qpdf/qpdf#386] opened 2019-11-27 11:13 UTC
I have a quite large QDF form file, baked with **--preserve-unreferenced**.
It starts with:

> %PDF-1.5
> ...
> %QDF-1.0
> 
> %% Original object ID: 1 0
> 1 0 obj
> <<
>   /ID [
>     <...>
>     <...>
>   ]
>   /Size 2
>   /Type /XRef
>   /W [
>     1
>     3
>     1
>   ]
>   /Length 2 0 R
> >>
> stream
> ...
> endstream
> endobj
> 
> %QDF: ignore_newline
> 2 0 obj
> 10
> endobj
> 
> %% Original object ID: 2 0
> 3 0 obj
> <<
>   /E 228616
>   /H [
>     1261
>     208
>   ]
>   /L 228893
>   /Linearized 1
>   /N 1
>   /O 6
>   /T 228615
> >>
> endobj
> 
> %% Original object ID: 3 0
> 4 0 obj
> <<
>   /ID [
>     <...>
>     <...>
>   ]
>   /Index [
>     2
>     97
>   ]
>   /Info 106 0 R
>   /Prev 228616
>   /Root 6 0 R
>   /Size 99
>   /Type /XRef
>   /W [
>     1
>     3
>     1
>   ]
>   /Length 5 0 R
> >>
> stream
> ...
> endstream
> endobj
> 
> %QDF: ignore_newline
> 5 0 obj
> 485
> endobj
> 
> %% Original object ID: 4 0
> 6 0 obj
> <<
>   /Pages 123 0 R
>   /Type /Catalog
> >>
> endobj

When I run fix-qdf on it, the output file is very small:

> %PDF-1.5
> ...
> %QDF-1.0
> 
> %% Original object ID: 1 0
> 1 0 obj
> <<
>   /ID [
>     <...>
>     <...>
>   ]
>   /Size 2
>   /Type /XRef
>   /Length 6
>   /W [ 1 1 1 ]
>     1
>     3
>     1
>   ]
> >>
> stream
> ...
> endstream
> endobj
> 
> startxref
> 52
> %%EOF
> 

If I remove **--preserve-unreferenced** in the first place, fix-qdf works as intended.
Would be great if you can fix this. Thanks!

**Comment by jberkenbilt** [comment] 2019-12-01 23:51
Can you share the file? I use fix-qdf all the time on files with unreferenced objects, so there must be something else about the file that's breaking fix-qdf. If you are not able to share the file publicly but are able to share it privately, you can email me the file or send me a link privately by email at ejb@ql.org, and I can delete the file when I've determined what the problem is.

**Comment by jberkenbilt** [comment] 2020-01-15 00:32
Thank you for sending the file. The `next` label indicates my intention to look at this before releasing the next version. After I have looked at it more carefully, I can assess the difficulty and priority of a fix.

**Comment by jberkenbilt** [comment] 2020-01-25 22:55
(note to self: saved to misc/bugs/386/file.pdf)

**Comment by jberkenbilt** [comment] 2020-01-26 21:42
I figured this out. The fix will be in 9.1.1. The issue was pretty subtle. fix-qdf assumes there is exactly one XRef stream in a file, and that it appears at the end. When you have a qdf file with XRef streams, those streams are unreferenced, and so adding `--preserve-unreferenced` causes them to be output. As a special case, in qdf mode, qpdf will no longer output any XRef streams that happen to have been in the original file.

**Closed** 2020-01-26 23:29 UTC
Labels: bug, next
