### ISSUE TITLE
Size of output PDF is larger than that of input PDF after delete some pages with "--empty" flag !

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#355] opened 2019-09-01 17:44 UTC
Hi dear @jberkenbilt 
Thank you very much for your very hard efforts that will make the stone for future Linux PDF editors based on your great program .......

Dear please take look for this:
https://github.com/junrrein/pdfslicer/issues/74

I'm not sure if this is a bug or not ?

**Comment by jberkenbilt** [comment] 2023-12-29 16:53
I'm not sure what the issue is here. I'm closing this for age, but if there is an issue, please reopen or create a new issue.

**Closed by jberkenbilt** 2023-12-29 16:53 UTC
