### ISSUE TITLE
Believed-Corrupt File Tolerated by Zlib-Flate

### ISSUE THREAD

**Issue by hostilefork** [qpdf/qpdf#562] opened 2021-09-12 15:00 UTC
*(Not the highest priority issue in the world, but I had to look into it, so...mentioning it.)*

Someone had a zlib DEFLATE file that we were detecting as corrupt.  They used the fact that zlib-flate would decompress it as evidence that it was okay.  But I think it's corrupt, and pigz agrees:

    $ pigz -d < corrupt-zdeflated.bin
    pigz: skipping: <stdin>: corrupted -- incomplete deflate data

It's a case where zlib-flate gives 338 bytes output without complaint.  Here's a .zip of the .bin file (GitHub doesn't accept .BIN unless it's zipped):

**[corrupt-zdeflated.zip](https://github.com/qpdf/qpdf/files/7149770/corrupt-zdeflated.zip)**

I believe the issue comes down to this tolerance:

https://github.com/qpdf/qpdf/blob/8971443e4680fc1c0babe56da58cc9070a9dae2e/libqpdf/Pl_Flate.cc#L163-L169

The stream is missing a termination signal (likely the person creating it [failed to use Z_FINISH](https://stackoverflow.com/questions/22832953/zlib-inflate-returning-z-buf-error#comment34836985_22838521)).  And zlib-flate isn't counting that as corruption.

I know it's one of Mark Adler's pet peeves for malformed zlib data to make it around in the wild where he has to do Q&A about it.  So he'd probably say you should not be accepting a stream that hasn't been terminated, because it starts to suggest that others (like pigz or me, etc.) would need to accept it as well...and it's kind of a snowball effect.

Is there a reason qpdf needs this exemption?  If it's absolutely necessary, could zlib-flate at least print out a warning that the stream is incomplete, and it's decompressing it anyway?

**Comment by jberkenbilt** [comment] 2021-09-12 15:08
I will look into this. zlib-flate is not intentionally ignoring corrupted streams. Perhaps I didn't have a way to reproduce this millions of years ago when I first wrote that code.

**Comment by jberkenbilt** [comment] 2021-09-12 15:09
This is probably a bug that I will want to fix. Thanks for bringing it to my attention.

**Comment by jberkenbilt** [comment] 2021-11-02 21:38
It turns out that Adobe Acrobat generates compressed streams like this when you fill in forms with it, or at least there's a file in the qpdf test suite from 2018 that fails if I make this strict. There's the principal that readers should be as liberal as possible in what they receive, but I also appreciate the issue here. I think my compromise will that zlib-flate will complain when this happens but that qpdf will allow it with a warning.

**Comment by jberkenbilt** [comment] 2021-11-02 22:02
In the the next version of qpdf, zlib-flate, when run on this input file, will write this to stderr but still uncompress the stream as well as it can.

```
zlib-flate: WARNING: zlib code -5, msg = input stream is complete but output may still be valid
```

**Comment by jberkenbilt** [comment] 2021-11-03 13:38
Actually, I realized that, the way I implemented the warning, it was only two lines of code to have qpdf also issue a warning in this case, so that will be in place. It's a warning the user can't do anything about, so it might just be noise. According to my notes, the bad file in the qpdf test suite was written Acrobat for Android, which has written bad PDF files with other errors as well.

**Closed** 2021-11-03 21:27 UTC
Labels: bug, next

**Comment by hostilefork** [comment] 2022-01-11 04:11
Hello, sorry for the delay in replying.  Thank you for following up and explaining the reason for the tolerance.

I know there are a lot of people who subscribe to the ["Robustness Principle"](https://en.wikipedia.org/wiki/Robustness_principle) *("be conservative in what you send, be liberal in what you accept")*.  I've never liked that idea, so I fit squarely in the "criticism" section.  :-)

Glad it's documented now, and I'll stick with emitting an error if I see these files in my sphere.  Perhaps an error that links to this issue...
