### ISSUE TITLE
Performance regression on Windows with some PDF files

### ISSUE THREAD

**Issue by sekrause** [qpdf/qpdf#798] opened 2022-09-30 14:32 UTC
I have a PDF file where `pikepdf.Pdf.open()` has a 100x performance regression between version 4.0.0 and 4.1.0 using the 64-bit binary wheels: Instead of 3.5 milliseconds it takes 350 milliseconds to open the file. Not reproducible on Linux.

After I figured out that the regression happens in `qpdf` itself I checked out the msvc64-binaries of `qpdf`, here I can see the the same slowdown between the versions 10.3.2 and 10.4.0: While 10.3.2 processes the file very quickly, 10.4.0 takes more than 300 milliseconds longer. All later releases of `qpdf` have the same slowdown, including the most recent.

Is this a known issue?

@jberkenbilt The PDF that causes the slowdown is a file that I can't really make public, but I'm willing to send it in private by email. So far I have found no other PDF where I could reproduce this regression. If it's okay I could send the PDF causing the issue to you by email.

**Comment by jberkenbilt** [comment] 2022-09-30 15:43
Can you check with 11.1.0? There were a lot of performance enhancements made between 10.6.3 and 11.1.0. If you still see slowness in the current release, then I'd be interested in analyzing the file. Please let me know what you find with version 11.1. Thanks.

**Comment by jberkenbilt** [comment] 2022-09-30 15:44
The latest pikepdf uses qpdf 11.1 as well. I intend to release 11.1.1 within a few days with a few minor performance enhancements and a small bug fix.

**Comment by sekrause** [comment] 2022-09-30 20:16
qpdf 11.1.0 is faster than 10.4.0, but still something like 8 times slower than 10.3.2. A simple measurement with the PowerShell command `Measure-Command`:

```
Measure-Command { .\qpdf-10.3.2\bin\qpdf.exe test.pdf out.pdf }
Milliseconds      : 42

Measure-Command { .\qpdf-10.4.0\bin\qpdf.exe test.pdf out.pdf }
Milliseconds      : 462

Measure-Command { .\qpdf-11.1.0-msvc64\bin\qpdf.exe test.pdf out.pdf }
Milliseconds      : 321
```

As previously mentioned only reproducible with the Windows builds. I'll send you the test file right away!

**Comment by jberkenbilt** [comment] 2022-09-30 21:05
Thanks for telling me how to reproduce it. I have very limited Windows knowledge. I know enough to build qpdf on it, but it has never been a platform I've used for any serious work.

**Comment by jberkenbilt** [comment] 2022-10-01 14:36
I am also able to reproduce this with just using the `time` command in a msys2 shell. I see the following behavior:
* 10.3.2 is much faster than 10.4.0 and 11.1.0 for both msvc64 and mingw64 on this file.
* This is an encrypted file. The degree to which the performance is degraded is significantly more for encrypted files than non-encrypted files, but it is degraded for non-encrypted files as well
* The msvc64 binaries outperform the mingw64 binaries. I should possibly change which one I set as the default download for Windows users on sourceforge. Right now, mingw32 is the default, but maybe it's time to switch to msvc64. I don't imagine most people who are manually downloading qpdf from sourceforge or github are using 32-bit systems these days.
* For the first 100 pages of the PDF spec (used in my performance benchmarking), I see about a 10% decrease in performance between 10.3.2 and 10.4.0 but about a 33% increase between 10.3.2 and 11.1.0. For the other file in my performance test collection, I see a very large performance degradation between 10.3.2 and 10.4.0 and a slight degradation between 10.3.2 and 11.1.0.

One thing that changed between 10.3.2 and 10.4.0 was using openssl 3 instead of openssl 1. I have read (but have not independently verified) that openssl 3 is slower than openssl 1, but this can't be the whole story because non-encrypted files are also worse. I am not seeing any changes in the way qpdf was built. The switch to the latest MSVC compiler version didn't happen until 10.6.3.

The test file has at least one weird thing about it, which is that the metadata is cleartext but the file file fails to set `/EncryptMetadata` to false. This causes qpdf to "decrypt" the already decrypted metadata, but that's just one stream, and that doesn't happen with the other files. I can't see that having any impact. In your file, the logo in the content stream for page 1 is drawn with drawing commands stroke by stroke, suggesting it may have originated as an SVG file or some other vector graphic file, but this is completely fine and has no effect other than to create a somewhat larger content stream, but it should also not have a big impact.

By the way, looking at the PDF, the PDF creator field is filled in in such a way that I'm guessing this is an internally-developed PDF creation. Whatever library is being used for encryption is failing to set `/EncryptMetadata false` in the encryption dictionary. If you have a way to report a bug about that, you can report that.

I have reviewed the code changes between 10.3.2 and 11.1.0, and there aren't that many changes. The only thing that could be performance impacting that I can see is a call to check ownership of QPDF objects in some cases, but I don't see why that would be an issue on Windows but not on Linux. It also doesn't seem to be in the code path for a simple qpdf read/write.

I would also say that "100x performance degradation" is a mischaracterization. There is probably some combination of proportional degradation and constant additional time. My Windows box is a virtualbox VM running on Linux. I see between about 75 and 115 ms on 10.3.2 and between about 610 and 650 ms on 10.4.0. Awful, but not 100x. For 11.1.0, I see between about 480 and 490 ms.

I'm not sure what I'm going to be able to do with this, unfortunately. I don't have experience with Windows development tools, and my Windows dev setup is quite slow and painful since I'm running on a virtualbox VM. I also have only command-line tools and have never used a profiler on Windows.

I will leave this open and tag it as `performance`, but unless someone is able to step forward and help analyze the source of the difference, I'm not sure what to do.

One thing I can possibly do is to start running my performance benchmarking tool on Windows. I just tried running it, and while I'd never tested on Windows, it does actually work. The results are quite surprising -- the differences in performance on Windows between the different options is quite large compared to Linux. For example, generating object streams is a lot faster than disabling object streams on Windows, whereas those tests perform about the same on Windows.

Another option I could try would be to build with clang on Windows. I believe this still uses msvc for linking. I'd have to investigate.

I can't promise when I'm going to get to this, but you've got it more on my radar. I will also link this to the discussion ticket about Windows performance of qpdf. Thanks for taking the time to report.

I have a private stash of files. I'll keep your test file in my private stash (note to self: misc/bugs/798/test.pdf) in case I make some progress on this, but given that there's nothing odd about your file and that I see a discrepancy on other files as well, I shouldn't have any trouble reproducing this.

**Comment by jberkenbilt** [comment] 2022-10-01 14:38
The discussion on Windows performance is #715

**Comment by sekrause** [comment] 2022-10-01 17:03
> I'm not sure what I'm going to be able to do with this, unfortunately. I don't have experience with Windows development tools, and my Windows dev setup is quite slow and painful since I'm running on a virtualbox VM. I also have only command-line tools and have never used a profiler on Windows.

I just tried the profiling method of adding print statements with the execution time (using ``std::chrono::high_resolution_clock``) everywhere, starting in `QPDF::parse()`.

In that function pretty much all time is spent in the call to `initializeEncryption()` which takes around 200 ms on my computer.

`initializeEncryption()` is quite fast until [the first call to check_owner_password()](https://github.com/qpdf/qpdf/blob/236a02d40267e3ed99a535b69b7a779bc0b09e80/libqpdf/QPDF_encryption.cc#L993).

In `check_owner_password_V4()` it's starting to get trickier, there is no single line of code or function call that takes suspiciously a long time. It almost feels like every single function call into OpenSSL (no matter how small) adds some constant execution time. Unfortunately I have no idea *why* OpenSSL 3 could be so slow here.

**Comment by jberkenbilt** [comment] 2022-10-01 18:56
If you felt like trying to build your own qpdf, you could try building with openssl 1. An [older version of external-libs](https://github.com/qpdf/external-libs/releases/tag/release-2021-05-08) that has openssl 1.1 might work with 11.1.1 -- I haven't tried it. I'm not sure how hard it would be to get gnutls to work on Windows. I chose openssl for Windows because it has fewer external dependencies than openssl. You could also try running with native crypto. You can try the native crypto provider (without a rebuild -- it's in the distributed binaries) by setting the `QPDF_CRYPTO_PROVIDER` environment variable to the value `native`. You can run `qpdf --show-crypto` to verify. The first one listed is the default, and the rest or also available. I have no reason to believe the native crypto is insecure, but there have been some occasional bug reports with people not being able to initialize properly when using it. It was the default for years though and it worked fine for most people.

**Comment by sekrause** [comment] 2022-10-01 20:51
> If you felt like trying to build your own qpdf, you could try building with openssl 1. An [older version of external-libs](https://github.com/qpdf/external-libs/releases/tag/release-2021-05-08) that has openssl 1.1 might work with 11.1.1 -- I haven't tried it.

It doesn't work unfortunely. It does compile, but when trying to run qpdf I get this error:

```
qpdf: OpenSSL error: error:0308010C:digital envelope routines::unsupported
```

`native` _does_ work and is a lot faster. With qpdf 11.1.0 and my test file:

- `openssl` takes 340 ms to run.
- `native` takes 30 ms to run, so more than 10x faster.

**Comment by sekrause** [comment] 2022-10-01 21:11
A similar difference with my pikepdf test script:

```python
import os
import time
from pikepdf import Pdf

os.environ["QPDF_CRYPTO_PROVIDER"] = "native"

start = time.perf_counter_ns()
with Pdf.open("test.pdf") as pdf:
    print(len(pdf.pages))
stop = time.perf_counter_ns()
print((stop - start) / 1_000_000)
```

- _With_ setting `os.environ["QPDF_CRYPTO_PROVIDER"]` to `native` it prints a 2.5 milliseconds execution time.
- With the OpenSSL 3 crypto provider it's 175 milliseconds.

**Comment by jberkenbilt** [comment] 2022-10-01 21:14
Okay, I think we've learned that the issue is with the crypto provider. This is also used for random number generation, which may explain why there's a small impact even on non-encrypted files. qpdf always uses the random number generator for generating the `/ID` of the file. I'll leave this open in case I can explore alternatives, but there's probably not a whole lot I can do about it.

**Comment by sekrause** [comment] 2022-10-07 22:21
So I finally did manage to compile qpdf 11.1 with OpenSSL 1 (I made a mistake before) and it was immediately about 10% faster than 10.3.2.

Anyway, I think I have figured out what the problem is:

When using qpdf with OpenSSL 3 it does more work in `QPDFCrypto_openssl.cc`: Loading the "OpenSSL Legacy Provider" [in the constructor](https://github.com/qpdf/qpdf/blob/5c5b4e640e2df248192ff7aa518fb0d345884a33/libqpdf/QPDFCrypto_openssl.cc#L50) and then unloading it again [in the destructor](https://github.com/qpdf/qpdf/blob/5c5b4e640e2df248192ff7aa518fb0d345884a33/libqpdf/QPDFCrypto_openssl.cc#L80).

When processing my test file the Legacy Provider is loaded and unloaded again 450 times and each load/unload cycle seems to take just under a millisecond on my computer, which perfectly explains the ~300 ms runtime difference vs. OpenSSL 1.

It also explains why OpenSSL 1 is so much faster because no Legacy Provider is ever loaded then.

So the solution is probably to load the Legacy Provider just once and keep reusing it.

**Comment by jberkenbilt** [comment] 2022-10-08 11:30
Excellent analysis. I'll look at the legacy provider loading. Hopefully that should be an easy fix. Thanks!

**Comment by jberkenbilt** [comment] 2022-10-08 20:23
In my testing, this fix results in a 6x performance improvement with openssl 3 using 256 bit encryption (which doesn't use rc4 at all) and a 12x improvement when rc4 is actually used. This is a great find. I have to test with openssl 1.1 before I can commit the fix. I think I may be able to slightly improve the performance for openssl 1.1 as well.

**Comment by jberkenbilt** [comment] 2022-10-08 21:15
On Linux with these fixes, gnutls beats openssl by about 2% to 10% depending on the complexity of the file with native somewhere in between, but they are definitely on par now whereas before, openssl was vastly slower. The improvement will probably be even more noticeable on Windows. I overlooked this before because I don't run the performance benchmarking on Windows or with the openssl crypto provider, though I have, for this case, run it with openssl crypto. I also temporarily ran it with 128-bit encryption, which was even "more worse" than 256-bit. I will merge this fix when through CI. It will be released with 11.2.

**Comment by jberkenbilt** [comment] 2022-10-08 21:30
This fix also shaved several minutes off the Windows build in CI. Too bad it took so long for anyone to notice and report this!

**Closed** 2022-10-08 21:42 UTC
Labels: bug, next, performance

**Comment by sekrause** [comment] 2022-10-09 09:40
I can confirm that this commit fixes all performance problems with OpenSSL 3. Thank you for the quick fix!
