### ISSUE TITLE
Consider adding extraction of roman-numberated and arabic-numberated pages

### ISSUE THREAD

**Issue by me-kell** [qpdf/qpdf#1060] opened 2023-11-02 12:49 UTC
`qpdf` extract pages by absolute page number.

But a PDF-Document might have roman-numerated (in the frontmatter) and arabic-numerated pages.

Example:

The file `srcfile.pdf` has 3 roman-numerated pages (i, ii, iii) and 10 arabic-numerated pages (1, 2, 3, ..., 10).

The following command extracts pages i, ii, iii, 1, 2,  , 7

```bash
qpdf --empty --pages srcfile.pdf 1-10 -- targetfile.pdf
```

Is it possible to extract only arabic-numerated pages 1 to 10?

This is possibly related to issue [#939](https://github.com/qpdf/qpdf/issues/939)

**Comment by jberkenbilt** [comment] 2023-11-02 13:09
This will fit into the pages work I'm planning on doing.

**Comment by me-kell** [comment] 2023-11-02 13:15
These are very good news.

FYI: I had a question posted in [SO](https://stackoverflow.com/q/77402801/1659599)

**Comment by rubyFeedback** [comment] 2023-11-04 20:47
I think I ran into this when I had a few recent .pdf files. Arabic numbers are often at the beginning, right? Kind of like a sub-index or something. I find this very confusing; I'd wish page numbers would only be 1, 2, 3 and so forth, but I understand the rationale given here.

**Comment by jberkenbilt** [comment] 2023-11-04 20:50
Well, one of the things I'm trying to formalize is lots of different ways to refer to pages. People have asked for it by page label (this kind of user-supplied page number), also based on article threads, outlines, or other factors. I'm going go through all my notes and all the issues and try to come up with some framework. I don't know what it's going to look like. I'm concerned about adding even more complexity to qpdf's CLI, which is already very complex.

**Comment by me-kell** [comment] 2023-11-04 21:35
Maybe this can help to get some ideas (if not already known):

[PDF 1.7 - Page Labels](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#G11.1696265)

```
EXAMPLE The following example shows a document with pages labeled i, ii, iii, iv, 1, 2, 3, A-8, A-9, …
1 0 obj
    << /Type /Catalog
        /PageLabels << /Nums [ 0 << /S /r >> % A number tree containing
                               4 << /S /D >> % three page label dictionaries
                               7 << /S /D
                                    /P ( A- )
                                    /St 8
                                   >>
                             ]
                    >>
        …
    >>
endobj
```

And how other libraries manage page labels. For instance [cpdf (Coherent PDF) - Page labels](https://www.coherentpdf.com/cpdfmanual.pdf#section.11.5) or [pagelabels-py](https://github.com/lovasoa/pagelabels-py/tree/master/pagelabels).

**Comment by jberkenbilt** [comment] 2023-11-05 01:00
@me-kell Thanks. qpdf actually has pretty good support for page labels in the code and at the API level, just not so much on the CLI. The problem is that page labels can repeat and be ambiguous, especially when files are split and merged. If someone says they want pages i through iii but there is more than one set of pages numbered that way in a document because of concatenation of some other purpose, then it gets tricky. I have some notes about this since it can occur in other settings as well. For example, if you duplicate a page that an outline points to, which of the duplicate pages should the outline point to? These are just some of the issues I'm thinking about. I think most likely I will have qpdf default to simple behavior and pick the first match when there is ambiguity but provide some mechanism to be more specific and to detect matches, perhaps with a warning. When I get a little further along in my planning, I'll create a public discussion item to talk about the edge cases. Granted, these edge cases will not affect most users, so my goal will be to make the normal cases pretty simple.

One thing that I am likely to do is to provide some kind of JSON syntax that can be used to specify an unambiguous specification. I'm still working that out, and I'm still undecided as to what it should look like. I've considered other syntaxes as well (for the advanced/ambiguous case), but I'm reluctant to add yet another way to specify things.

**Comment by me-kell** [comment] 2023-11-05 10:11
Just an idea: how about passing the number of the label prepended to the page number?

For getting from "page 1 of pagelevel 3" to "page 2 of page level 4" one could pass something like `[3:1]-[4:2]` (see the page labels below).

```python
{'/Nums': ['0', {'/S': '/D'},   # 1st pagelabel from page 0
           '1', {'/S': '/R'},   # 2nd pagelabel from page 1
           '5', {'/S': '/r'},   # 3rd pagelabel from page 5
           '9', {'/S': '/D'},   # 4th pagelabel from page 9
           '13', {'/S': '/a'},  # 5th pagelabel from page 13
           '17', {'/S': '/A'},  # 6th pagelabel from page 17
           '21', {'/S': '/r'}]} # 7th pagelabel from page 21
```

There is though one problem. Some documents might have different numberings without any pagelabels at all.

**Comment by jberkenbilt** [comment] 2023-11-05 12:33
Good thoughts to keep in mind. Also note that you can get a dump of the page label information from a PDF file with qpdf using `qpdf --json --json-key=pagelabels file.pdf`. It's possible that qpdf could generate information to disambiguate that a caller could use, though it would be nice to have something that can be done without interaction for scripting. I think it can work though.

**Comment by me-kell** [comment] 2023-11-05 15:14
@jberkenbilt I didn't yet know the `json` options. Thanks.

With this option there is a workaround using a json parser like e.g. `jq`:

```console
$ INPUTFILE=inpufile.pdf
$ PAGELABELSLENGHT=$(qpdf --json ${INPUTFILE} | jq -r '.pagelabels | length')
$ echo "file '${INPUTFILE}' has ${PAGELABELSLENGHT} pagelabels"
$ for i in $(seq 0 $((${PAGELABELSLENGHT}-1)))
    do echo "pagelevel #$i starts at index #$(qpdf --json ${INPUTFILE} \
       | jq -r .pagelabels[$i].index)";
    done

file 'inpufile.pdf' has 2 pagelabels
pagelevel #0 starts at index #0
pagelevel #1 starts at index #4
```

And with a little bash script pages in a pagelabel can be converted to absolute pages:

```bash
cat <<'EOF' | tee relpage.sh
#!/bin/bash
PDFFILE=$1
STR=$2
PAGELABENR=${STR%:*}
PAGENRINLABEL=${STR#*:}
PAGELABELINDEX=$(qpdf --json ${PDFFILE} | jq -r .pagelabels[$PAGELABENR].index)
ABSPAGENR=$(($PAGELABELINDEX+$PAGENRINLABEL))
echo $ABSPAGENR
EOF
chmod +x relpage.sh
```

Usage: ./relpage.sh inputfile.pdf 1:39

```bash
qpdf \
    --empty \
    --pages \
    ${INPUTFILE} \
    $(./relpage.sh ${INPUTFILE} 1:17)-$(./relpage.sh ${INPUTFILE} 1:39) \
    -- \
    output.pdf
```

**Comment by jberkenbilt** [comment] 2023-11-05 16:03
@me-kell Yes, thanks for posting that. You're right -- this does provide a way to do it for now.

**Comment by jberkenbilt** [comment] 2023-12-29 17:43
I think there's nothing left to do here, so I'm closing. Please reopen if that is not the case.

**Closed by jberkenbilt** 2023-12-29 17:43 UTC
Labels: pages
