### ISSUE TITLE
page.images is missing images inside Form XObjects

### ISSUE THREAD

**Issue by benbro** [qpdf/qpdf#909] opened 2023-02-21 22:20 UTC
I think that this document can be used as an example:
[test.pdf](https://github.com/qpdf/qpdf/files/10798229/test.pdf)

https://github.com/ocrmypdf/OCRmyPDF/issues/977#issuecomment-1150807931

Python example from https://github.com/pikepdf/pikepdf/issues/423#issuecomment-1396252772
```python
def _find_images(container, depth=0):
    
    # derived from ocrmypdf/pdfinfo/info.py
    # `container` is a page (or an xobject for recursive calls)
    # This descends once into XObjects which may have nested images. It's some time ago I wrote this code, maybe you might want to increase recursion depth.
    # For images with alpha mask, this code will return a pair of (image, mask_image) to be merged or otherwise handled by the caller
    
    images = []
    
    if '/Resources' not in container:
        return images
    resources = container['/Resources']
    
    if '/XObject' not in resources:
        return images
    xobjects = resources['/XObject'].as_dict()
    
    for xobject in xobjects:
        
        candidate = xobjects[xobject]
        
        if candidate['/Subtype'] == '/Image':
            if '/SMask' in candidate:
                images.append( [candidate, candidate['/SMask']] )
            else:
                images.append(candidate)
        
        elif depth == 0 and candidate['/Subtype'] == '/Form':
            images.extend( _find_images(candidate, depth=depth+1) )
    
    return images
```

**Comment by cdosborn** [comment] 2023-03-09 03:04
This is caused by the fact getImages doesn't recurse when searching for images:
https://github.com/qpdf/qpdf/blob/main/libqpdf/QPDFPageObjectHelper.cc#L427

I noticed this is also is the case with `getFormXObjects`.

**Comment by jberkenbilt** [comment] 2023-03-09 11:55
Yeah, I think this will be an easy fix. There is other code that recurses into form xobjects.

**Comment by jberkenbilt** [comment] 2023-03-13 11:47
From QPDFPageObjectHelper.hh:
```c++
    // Returns an empty map if there are no images or no resources.
    // Prior to qpdf 8.4.0, this function did not support inherited
    // resources, but it does now. Return value is a map from XObject
    // name to the image object, which is always a stream. Works with
    // form XObjects as well as pages. This method does not recurse
    // into nested form XObjects. For that, use forEachImage.
    QPDF_DLL
    std::map<std::string, QPDFObjectHandle> getImages();
```

and

```c++
    // Iterate through XObjects, possibly recursing into form
    // XObjects. This works with pages or form XObjects. Call action
    // on each XObject for which selector, if specified, returns true.
    // With no selector, calls action for every object. In addition to
    // the object being passed to action, the containing XObject
    // dictionary and key are passed in. Remember that the XObject
    // dictionary may be shared, and the object may appear in multiple
    // XObject dictionaries.
    QPDF_DLL
    void forEachXObject(
        bool recursive,
        std::function<void(
            QPDFObjectHandle& obj,
            QPDFObjectHandle& xobj_dict,
            std::string const& key)> action,
        std::function<bool(QPDFObjectHandle)> selector = nullptr);
    // Only call action for images
    QPDF_DLL
    void forEachImage(
        bool recursive,
        std::function<void(
            QPDFObjectHandle& obj,
            QPDFObjectHandle& xobj_dict,
            std::string const& key)> action);
    // Only call action for form XObjects
    QPDF_DLL
    void forEachFormXObject(
        bool recursive,
        std::function<void(
            QPDFObjectHandle& obj,
            QPDFObjectHandle& xobj_dict,
            std::string const& key)> action);
```

I'm not sure whether pikepdf has a binding for `forEachImage`, but I think qpdf already has a solution to this problem that is just not being used by the pikepdf example above.

**Comment by jberkenbilt** [comment] 2023-03-13 11:54
Another possible solution would be to modify getImages to have an optional argument that recurses into form xobjects -- see #923 for further discussion.

**Comment by jberkenbilt** [comment] 2023-05-21 17:41
I'm closing this in favor of #923.

**Closed by jberkenbilt** 2023-05-21 17:41 UTC
Labels: bug, next
