### ISSUE TITLE
AES 256 encryption using a ë in the password

### ISSUE THREAD

**Issue by sotto** [qpdf/qpdf#270] opened 2019-01-07 09:38 UTC
A pdf encrypted by qpdf commandline on windows 10, with aes256 using a password with a ë in it, cannot be opened in  Adobe acrobat reader (or in gmail preview), giving wrong password as reason, although it can be opened using Foxit Reader.

**Comment by jberkenbilt** [comment] 2019-01-11 22:39
This is a duplicate of #215, which I hope to fix for qpdf 8.4.0. My goal is to get it out by the end of the month. The PDF spec is quite arcane about handling of special characters in passwords. I am going to make sure qpdf adheres strictly to the spec for encrypting files with non-ASCII passwords (which it does not currently do in all cases) and that, when opening files, it tries the various incorrect ways other software generates passwords.

In any case, thanks for your detailed report. I will attempt to reproduce this on a Windows machine from the CLI and make sure that, when fixed, all the readers you mentioned plus the other ones I test with can all open the file.

**Comment by jberkenbilt** [comment] 2019-01-19 16:01
I have fixed this bug and have confirmed that with current master, qpdf.exe on Windows is able to create encrypted files using either 128 or 256 bit encryption with accented characters, and that the resulting files can be opened by Adobe Reader and a variety of other readers. If you're interested in trying it out, you can grab a distribution from [CI](https://dev.azure.com/qpdf/_apis/resources/Containers/1368355?itemPath=distribution%2Fqpdf-8.3.0-bin-mingw32-ci.zip). This is somewhere between 8.3.0 and 8.4.0. I plan on releasing 8.4.0 within the next two to three weeks, and it will include this fix. The manual will include copious details on the nuances, but the bottom line is that qpdf's default behavior should be much more likely to create correct encrypted files with a variety of passwords.

I'm closing this now, but feel free to comment or reopen if needed.

**Closed by jberkenbilt** 2019-01-19 16:01 UTC
Labels: bug, next
