### ISSUE TITLE
Decryption fails with "incorrect length for /O and/or /U in encryption dictionary"

### ISSUE THREAD

**Issue by ppar** [qpdf/qpdf#96] opened 2017-01-02 11:13 UTC
While trying to decrypt a PDF file using the command line arguments:

`qpdf --decrypt --password=XXXXX foo/bar.pdf bar.cleartext.pdf`

qdpf gives the following error message and bails out:

`foo/bar.pdf (encryption dictionary, file position 249): incorrect length for /O and/or /U in encryption dictionary`

The version of qpdf I'm using is 6.0.0, installed from homebrew on OS X 10.11.6

The input file can be opened using "Adobe Acrobat Reader DC" version 2015.010.20056, Acrobat shows the following properties for the file:

- PDF producer: BitMiracle.Docotic.Pdf 4.1.5706
- PDF version: 1.6 (Acrobat 7.x)

- Security method: Password Security
- Document open password: yes
- Permissions password: yes
- Encryption level: 128-bit AES

- Can be opened by: Acrobat 7.0 and later
- Restrictions: Printing: allowed; everything else: not allowed

**Comment by jberkenbilt** [comment] 2017-01-02 17:41
Any chance you can provide a copy of the file? Feel free to send it to me by email or provide a link where I can get it from. I can always delete the file afterwards. I can take a look at the file and see if I can tell what's going on. Mostly these kinds of errors result from qpdf being stricter than Adobe Reader about malformed files. Unfortunately, most people just determine whether their PDFs are valid by testing whether Adobe Reader can open them. Often when I see such files, I can tweak qpdf to make it more permissive in certain ways.

**Comment by pvaczi** [comment] 2017-05-11 14:23
I have the same problem. I would send you the file, but I don't find your email in the profile.

**Comment by jberkenbilt** [comment] 2017-07-31 00:34
@pvaczi Sorry for overlooking your comment. You can email me at `ejb@ql.org`.

**Comment by jberkenbilt** [comment] 2017-08-11 23:26
I have received a file by email, which I will keep private. Note to self: misc/bugs/private/96.pdf. Hopefully I will figure out what the issue is. evince also can't open the file, but ghostscript can.

**Comment by jberkenbilt** [comment] 2017-08-11 23:29
I fixed it already. My first guess was to null-pad the /O and /U values, and that worked. This will be fixed in 7.0.0.

**Closed** 2017-08-11 23:54 UTC

**Comment by sidd313** [comment] 2017-11-17 17:02
I am trying to do pdftotxt for a file. But it says the file is encrypted , but opens perfectly fine in Acrobat reader. Then i try this decrypt it using qpdf and it gives the following error.

qpdf --decrypt --password='' S1005471.pdf try.pdf

S1005471.pdf (encryption dictionary, file position 537771): incorrect length for /O and/or /U in encryption dictionary
[S1005471.pdf](https://github.com/qpdf/qpdf/files/1483111/S1005471.pdf)

**Comment by jberkenbilt** [comment] 2017-11-17 17:24
@sidd313 What version of qpdf are you using? This works for me with 7.0.0.

**Comment by sidd313** [comment] 2017-11-17 17:26
Can you share with me the new decrypted pdf.  I used an online editor from 
https://www.tutorialspoint.com/unix_terminal_online.php to decrypt it.

**Comment by jberkenbilt** [comment] 2017-11-17 22:24
Sure, next time I'm at my computer. How should I get it to you? If I don't hear anything, I'll stick it on my personal web site, put a link here, and delete it when you tell me, or I can get it to you in some other way that you specify.

**Comment by sidd313** [comment] 2017-11-22 12:01
Hi can you please send that file as a email attachment to my email id. bs0842@isical.ac.in. I can verify whether I can do pdftotext on that decrypted file .

**Comment by jberkenbilt** [comment] 2017-11-22 15:32
@sidd313 I sent it. Please let me know if you got it. If not, I'll put it up somewhere for you to download.

**Comment by sidd313** [comment] 2017-11-22 15:45
I didn't received the email, the college server blocked it. I would very grateful if you can send again to my Gmail id : sidd313@gmail.com

**Comment by jberkenbilt** [comment] 2017-11-22 17:30
@sidd313 Sent to the gmail address. If that fails, I will put it somewhere for you to download.
