### ISSUE TITLE
Remove not needed objects from pdf

### ISSUE THREAD

**Issue by kallegit1950** [qpdf/qpdf#174] opened 2018-01-20 06:52 UTC
I have a pdf which is 1.4GB (due to lots of pictures) and has 60 pages. I want to extract now 2 pages from it. I would expect that these two pages are around 50MB. But these two pages are again 1.4 GB. My assumption is that all the pictures which are not needed are still embedded in that file. Which doesn't make sense to me. I tried

` qpdf infile.pdf --pages infile.pdf 30-31 -- outfile.pdf`

as well as

`qpdf --empty --pages infile.pdf 30-31 -- outfile.pdf`

Am I on the wrong path here, or is that a bug or even wanted for unknown reasons?

Thanks.

**Comment by jberkenbilt** [comment] 2018-01-20 14:33
Is it possible for you to share the PDF file? I can take a look and see why the output file is so big and determine whether it's a bug or whether there's something that's referenced in a way that's causing it to be retained once the pages are split. If you can put the file somewhere that I can download, I'll pull it down, look at it, and delete it when done. You can send me a link privately at my email address (ejb@ql.org) if you want. If you can't share the file, you could try `qpdf --split-pages infile.pdf outfile.pdf` and see what the sizes of the individual pages (outfile-01.pdf through outfile-60.pdf) are to see if there is a pattern. You could also run `qpdf --show-pages --with-imagesinfile.pdf` to see whether there are some image objects that are referenced by all the pages. I'm just guessing here, but it's possible that the file could be constructed in such a way that there is some catalog of images that is referenced by the metadata for all pages but only in the page contents for some pages. If that's the case, qpdf wouldn't have any way to know this and would continue to include the information on all pages. In that case, it would still be possible to use qpdf to extract out only the parts you want, but it would require either manual editing of the file or writing C++ code. There wouldn't be any way to do it directly from the command line. Anyway, I'm happy to take a look. If there is some specific reason why this is happening, it may be possible to add some flag to qpdf to enable it to do some additional transformation to handle this case. Thanks.

**Comment by kallegit1950** [comment] 2018-01-20 15:39
Hello,

thanks, when running --show-pages I get

`page 1: 46 0 R
  content:
    44 0 R
page 2: 55 0 R
  content:
    53 0 R
page 3: 60 0 R
  content:
    58 0 R
page 4: 67 0 R
  content:
    65 0 R
page 5: 79 0 R
  content:
    77 0 R
page 6: 88 0 R
  content:
    86 0 R
page 7: 95 0 R
  content:
    93 0 R
page 8: 102 0 R
  content:
    100 0 R
page 9: 105 0 R
  content:
    103 0 R
page 10: 112 0 R
  content:
    110 0 R
page 11: 119 0 R
  content:
    117 0 R
page 12: 139 0 R
  content:
    137 0 R
page 13: 156 0 R
  content:
    154 0 R
page 14: 165 0 R
  content:
    163 0 R
page 15: 178 0 R
  content:
    176 0 R
page 16: 193 0 R
  content:
    191 0 R
page 17: 211 0 R
  content:
    209 0 R
page 18: 226 0 R
  content:
    224 0 R
page 19: 238 0 R
  content:
    236 0 R
page 20: 256 0 R
  content:
    254 0 R
page 21: 267 0 R
  content:
    265 0 R
page 22: 281 0 R
  content:
    279 0 R
page 23: 292 0 R
  content:
    290 0 R
page 24: 303 0 R
  content:
    301 0 R
page 25: 310 0 R
  content:
    308 0 R
page 26: 324 0 R
  content:
    322 0 R
page 27: 331 0 R
  content:
    329 0 R
page 28: 345 0 R
  content:
    343 0 R
page 29: 356 0 R
  content:
    354 0 R
page 30: 365 0 R
  content:
    363 0 R
page 31: 376 0 R
  content:
    374 0 R
page 32: 385 0 R
  content:
    383 0 R
page 33: 394 0 R
  content:
    392 0 R
page 34: 403 0 R
  content:
    401 0 R
page 35: 410 0 R
  content:
    408 0 R
page 36: 423 0 R
  content:
    421 0 R
page 37: 437 0 R
  content:
    435 0 R
page 38: 442 0 R
  content:
    440 0 R
page 39: 445 0 R
  content:
    443 0 R
page 40: 454 0 R
  content:
    452 0 R
page 41: 465 0 R
  content:
    463 0 R
page 42: 476 0 R
  content:
    474 0 R
page 43: 488 0 R
  content:
    486 0 R
page 44: 493 0 R
  content:
    491 0 R
page 45: 496 0 R
  content:
    494 0 R
page 46: 507 0 R
  content:
    505 0 R
page 47: 512 0 R
  content:
    510 0 R
page 48: 524 0 R
  content:
    522 0 R
page 49: 538 0 R
  content:
    536 0 R
page 50: 547 0 R
  content:
    545 0 R
page 51: 565 0 R
  content:
    563 0 R
page 52: 579 0 R
  content:
    577 0 R
page 53: 590 0 R
  content:
    588 0 R
page 54: 599 0 R
  content:
    597 0 R
page 55: 604 0 R
  content:
    602 0 R
page 56: 614 0 R
  content:
    612 0 R
page 57: 626 0 R
  content:
    624 0 R
page 58: 635 0 R
  content:
    633 0 R
`

I created a test document which shows a similar behavior but is much smaller. I created a file with scribus (scribus file as well attached), it has 2 text fields and two pictures. One of these on each page. A scribus export with uncompressed pictures is about 17 MB, both pictures alone are 16MB. The output file with only one page is again about 17MB in size. I would have expected around 8 or 9 MB.

Files can be found here:

https://www.file-upload.net/download-12933234/qdf-test.zip.html

Of course maybe scribus messed up the pdf export, if you can see that in your tools I would open an issue for scribus. In that case, could you please give me as well some details I can pass on to them?

Thanks for your quick answer!

**Comment by jberkenbilt** [comment] 2018-01-21 15:21
Looks like my guess is correct. The `/Resources` key that lists what resources are used by the pages is attached to the `/Pages` dictionary where it is inherited by all pages, so every page's `/Page` dictionary references all the images. I have to run now, but later today, I will post a detailed response with enough information for you to report a bug to scribus and also to manually work around it and get the extraction that you are looking for. Stay tuned. :-)

**Comment by jberkenbilt** [comment] 2018-01-21 19:59
If you'd like to report a bug to scribus, and I think you should, you can report that by attaching all the `/XObject` and other resources to the pages tree at other than the page level, it is preventing page splitting from working from any application that figures out which objects are referenced by a page just by looking at the resource dictionary. Please feel free to refer them to this issue for additional information. What they should do instead is to attach a `/Resources` dictionary to each page containing references only to the images and fonts that are used by that page. In addition to messing up page splitting, their way of doing this messes up linearization because a linearized PDF file starts with a serial presentation of all objects referenced by the first page, which in their case, is all the big objects in the file.

Here's a walk-through of extracting just one page without all the extraneous images. It works by having you mutate the PDF file to null out the images that you don't need. You can find those by using qpdf's inspection capabilities.

Start by using qpdf to convert the file to qpdf's style of creating output. This is not required, but it will make the rest of the steps more reliable. If you skipped that step, it's likely that the rest would still work, but it would be impossible to guarantee.

```
% qpdf qpdf-test-pictures.pdf /tmp/1.pdf
```

Now take a look at the pages and images. We'll observe that each page references all the images in its resources. Then we'll look at the content stream to see which images are actually used by the page.

```
% qpdf --show-pages --with-images /tmp/1.pdf
page 1: 9 0 R
  images:
    /REI0: 19 0 R, 5184 x 3456
    /REI1: 20 0 R, 5184 x 3456
  content:
    12 0 R
page 2: 10 0 R
  images:
    /REI0: 19 0 R, 5184 x 3456
    /REI1: 20 0 R, 5184 x 3456
  content:
    14 0 R
```

You can see that `/REI0` and `/REI1` are both referenced on both pages. Let's see what's referenced by the content stream in page 1. Notice that all the images in this case start with `/REI`, so we can just search for that. The output above shows that the content for page 1 is `12 0 R`, which is a reference to object 12, generation 0. We can show the contents and search for a reference to the image:

```
% qpdf --show-object=12,0 /tmp/1.pdf --filtered-stream-data | grep /REI
/REI0 Do
```

So you can see that only `/REI0` is referenced. We want to get rid of all the other images. We know already that the only other image is `/REI1`, which is `20 0 R`, so replacing all references to `20 0 R` with `null` would be sufficient at this point, but we can do a little more inspection to see what's going on. We'll look at the page dictionary for page 1. We can see from the show pages output that it's `9 0 R`.

```
% qpdf --show-object=9,0 /tmp/1.pdf
<< /ArtBox [ 0.00000 0.00000 595.28000 841.89000 ] /BleedBox [ 0.00000 0.00000 595.28000 841.89000 ] /Contents 12 0 R /CropBox [ 0 0 595.28000 841.89000 ] /Group 13 0 R /MediaBox [ 0 0 595.28000 841.89000 ] /Parent 7 0 R /Rotate 0 /TrimBox [ 0.00000 0.00000 595.28000 841.89000 ] /Type /Page >>
```

If you look at this dictionary, you can see that there is no `/Resources` key and that the value of `/Parent` is `7 0 R`. Let's look at the parent in the page tree.

```
% qpdf --show-object=7,0 /tmp/1.pdf
<< /Count 2 /Kids [ 9 0 R 10 0 R ] /Resources 11 0 R /Type /Pages >>
```

Here we see the pages and a `/Resources` dictionary at `11 0 R`. Look there we can see the images in the `/XObject` dictionary:

```
% qpdf --show-object=11,0 /tmp/1.pdf
<< /Font << /Fo0Form 16 0 R /Fo0S0 17 0 R /Fo0S1 18 0 R >> /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /XObject << /REI0 19 0 R /REI1 20 0 R >> >>
```

What we can do now is to just replace the reference to `/REI1` with null, doing it carefully to not change the number of characters.

```
% sed -i -e's,/REI1 20 0 R,/REI1 null  ,' /tmp/1.pdf
```

Let's check ourselves:

```
% qpdf --show-object=11,0 /tmp/1.pdf
<< /Font << /Fo0Form 16 0 R /Fo0S0 17 0 R /Fo0S1 18 0 R >> /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /XObject << /REI0 19 0 R /REI1 null >> >>
```

Now we can take just page 1:
```
% qpdf /tmp/1.pdf --pages /tmp/1.pdf 1 -- /tmp/2.pdf
```

Let's take a look at the new pdf:

```
% qpdf --show-pages --with-images /tmp/2.pdf
page 1: 9 0 R
  images:
    /REI0: 16 0 R, 5184 x 3456
  content:
    10 0 R
```

Just one image, and we can also see the expected reduction in file size:

```
% ls -l /tmp/[12].pdf
-rw-r--r-- 1 ejb ejb 17509829 Jan 21 14:52 /tmp/1.pdf
-rw-r--r-- 1 ejb ejb  9793427 Jan 21 14:53 /tmp/2.pdf
```

For your 60 page PDF where you want to capture just two pages, you could do a similar exercise where you null out the 58 images referenced by the pages you are not trying to keep. It would be tedious but scriptable. To make it slightly more reliable, you could limit the replacement to only the `/Resources` dictionary, though you might have to write a script or use something other than sed. It's easy to do this stuff in a text editor that can reliably edit binary files (like emacs), but not for 1+ GB file!

**Comment by jberkenbilt** [comment] 2018-01-21 20:04
Since qpdf is behaving as designed and the problem is with the underlying PDF, I'm going to go ahead and close this issue. Thanks for the report, and please let me know if you have any additional questions. It would be possible to write a short C++ program using qpdf that would handle this particular type of file automatically. There's already a library routine that pushes inheritable attributes in the pages structure down to the page level. From there, it would be possible to scan the content streams for a page and then prune from the resources any image that isn't referenced in the content stream.

**Closed by jberkenbilt** 2018-01-21 20:04 UTC

**Comment by kallegit1950** [comment] 2018-02-08 17:45
Hello, I opened a bug report with scribus. They say you do something wrong https://bugs.scribus.net/view.php?id=15135 Can you take a look at that please?

**Comment by jberkenbilt** [comment] 2018-02-10 15:20
I posted a new bug with clarification. It doesn't look like they understood the issue. I've tried to clarify it. qpdf is not doing anything wrong, and Scribus is not creating invalid PDF files. The problem is that Scribus is creating PDF files that don't convey optimal information to PDF readers. The person who responded to the bug report is correct that Scribus is creating valid, compliant PDF files. They are just not creating files that enable page splitting applications to get the information they need. See my udpated bug report. I would have commented on 15135 but it had already been closed. Thanks for following up.

https://bugs.scribus.net/view.php?id=15140

**Comment by jberkenbilt** [comment] 2018-06-22 00:57
QPDF will probably prune unused resources from files like this starting in 8.1, which I expect to release in the next few days.

**Comment by rubyFeedback** [comment] 2020-03-29 17:03
By the way, just wanted to comment that the explanations are very useful. I came to this via google search and while I had another issue, the explanations given were really useful; I did not know about the /Resources entry for example prior to the comments above.
