### ISSUE TITLE
Assert fires in QPDF::checkLinearization()

### ISSUE THREAD

**Issue by gtbarnabas** [qpdf/qpdf#231] opened 2018-08-07 00:33 UTC
I have a tool that calls the QPDF::checkLinearization() method. When we run the tool against a particular PDF file, it hits an assert and crashes:
```
pdf-dump-info: libqpdf/QPDF_linearization.cc:958: void QPDF::checkHSharedObject(std::__cxx11::list<std::__cxx11::basic_string<char> >&, std::__cxx11::list<std::__cxx11::basic_string<char> >&, const std::vector<QPDFObjectHandle>&, std::map<int, int>&): Assertion `this->m->xref_table.count(og) > 0' failed.

Aborted (core dumped)
```
The file can be downloaded at "http://gdcm.sourceforge.net/gdcm-2.3.0.pdf". We are able to view this file with standard PDF viewers.

**Comment by jberkenbilt** [comment] 2018-08-07 01:53
Yes, there are lots of issues with checkLinearization. I need to just do a clean pass through the code and get rid of all calls to assert. It's on my to-do list. That's the last bit of library code that calls assert. It should generate warnings instead, like all the other checking code does.

**Comment by gtbarnabas** [comment] 2018-08-07 04:00
In this case, is this a problem with the file, or with the tool?

**Comment by jberkenbilt** [comment] 2018-08-07 14:31
It is most likely a problem with both the file and the tool. The file most likely has a problem that the tool is not handling gracefully.

This is a duplicate of #209 and probably other issues. When I work this issue, I will go through all the open issues and figure out which ones are manifestations of the same root cause.

**Comment by jberkenbilt** [comment] 2018-08-07 14:47
Just for context, I originally wrote that code as a checker for my own linearization code, hence all the asserts. This was before I had open sourced qpdf, which I originally wrote while working at a company that did lots of PDF stuff. Only later, when I was able to open source qpdf, was it repurposed as a general checker that was run over linearized files generated by other tools. I have been gradually going through qpdf and making it be more accepting of broken files. This is the last significant area, and fixing it is high priority but also a decent amount of work because lots of code will assume that all prior assertions passed (e.g., not checking nulls, etc.). I'll actually have to go through all the logic and make sure that changing assertions to warnings doesn't introduce crashes in later code. I bet I could still knock it out in a day though.

**Comment by jberkenbilt** [comment] 2018-12-17 13:09
I'm hoping to get to this in the current round of fixes.

**Comment by jberkenbilt** [comment] 2019-01-04 18:23
This is fixed in master.

**Comment by jberkenbilt** [comment] 2019-01-04 20:19
This is fixed in master and will be fixed in the upcoming 8.3.0 release.

**Comment by rbrito** [comment] 2019-01-23 22:20
Dear @jberkenbilt,

The PDF files (I have at least 2 ready to send, but may find more if you want me to) that I have here (for issue #268) that were giving me problems with linearization with version 8.2.1 of qpdf still continue to give me the problem with version 8.3.0 of qpdf:

```
$ qpdf --version
qpdf version 8.3.0
Run qpdf --copyright to see copyright and license information.
$ qpdf --linearize to-linearize.pdf to-linearize.linearized.pdf 
INTERNAL ERROR: QPDF::calculateLinearizationData: page object for page 9 not in lc_other_page_private
$ 
```

Would you like me to send you the files that I have here?

Thanks for your great tool,

Rogério.

**Comment by jberkenbilt** [comment] 2019-01-24 16:38
@rbrito I'm happy to receive any files you may have. I'm going to release 8.4.0 in the next couple of weeks, and it would be nice to knock these out. What I really need to do is to take a complete pass through the linearization code. An error during linearization is definitely a bug and is different from not asserting in check code. Thanks.

**Closed** 2019-01-24 16:38 UTC
Labels: bug, next

**Comment by jberkenbilt** [comment] 2019-01-24 16:40
@rbrito We can use #268.
