### ISSUE TITLE
Merge fails to insert "empty" pdf

### ISSUE THREAD

**Issue by TheChatty** [qpdf/qpdf#31] opened 2014-01-13 14:15 UTC
The following fails due to some "vector::_M_range_check":
qpdf --empty test.pdf
qpdf --empty out.pdf --pages test.pdf 1 --

And if the range parameter is optional, why does the following have "insufficient arguments":
qpdf --empty out.pdf --pages test.pdf --

By the way, the following is valid (range for second pdf is given):
qpdf --empty out.pdf --pages test.pdf test2.pdf 1 --

But it fails due to the same check procedure if test.pdf is empty.

**Comment by jberkenbilt** [comment] 2016-09-10 18:55
I wonder if this is what happened to the user who reported https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825246.

**Comment by jberkenbilt** [comment] 2017-07-29 13:02
Looking at this more closely, the problem is just that we're trying to access page 1 of an empty file. I think this is just not fully understanding how to use the feature. Adding an empty file as one of the input files to --pages isn't useful because there would never be anything copied. Using --empty as the original input is file. I'm going to close this, but feel free to reopen or reach out for additional assistance. I know this is very old. Sorry about that.

**Closed by jberkenbilt** 2017-07-29 13:02 UTC
Labels: next
