### ISSUE TITLE
qpdf --check writes errors not to stderr, but to stdout

### ISSUE THREAD

**Issue by vstepaniuk** [qpdf/qpdf#438] opened 2020-04-29 14:57 UTC
Ubuntu 19.10
qpdf 8.4.2

```
$ qpdf --check file.pdf 2>/dev/null
checking file.pdf
PDF Version: 1.5
File is not encrypted
File is linearized
ERROR: linearized file contains an uncompressed object after a compressed one in a cross-reference stream
WARNING: page 0 has shared identifier entries
WARNING: page 0: shared object 12: in hint table but not computed list

$ echo $?
2
```

So there were errors and warnings, and `qpdf` exited with code `2`  - But it writes the errors and warnings to `stdout`!!! why?

**Comment by jberkenbilt** [comment] 2020-04-29 20:39
I am not able to reproduce this. When I run qpdf, it writes its error messages to stderr. Are you sure maybe your qpdf isn't a wrapper or something?

**Comment by vstepaniuk** [comment] 2020-04-29 20:54
Try with this:
[https://www.icj-cij.org/files/case-related/157/157-20170612-WRI-01-00-BI.pdf](https://www.icj-cij.org/files/case-related/157/157-20170612-WRI-01-00-BI.pdf)

**Comment by jberkenbilt** [comment] 2020-04-29 21:24
Yes, I can reproduce it. Thanks. Seems that linearization warnings are being written to stdout. I will fix this. Yes, it's just checkLinearization. :-( Thanks for drawing this to my attention.

**Comment by jberkenbilt** [comment] 2020-04-29 21:31
I checked every place where qpdf writes to stdout, and the only ones that should have been stderr were warnings and errors reported by `--check` when it checks linearized files. Given that this has been floating around since 8.4.2, I will not do a special release for it, but it will definitely be fixed in whatever the next release is. Thanks again for reporting.

**Comment by vstepaniuk** [comment] 2020-04-30 06:29
Ok, feel free to close it when you fix it

**Comment by vstepaniuk** [comment] 2020-04-30 21:55
Here I compiled a list of unique errors and warnings which I get for a rather big database of PDF files, **WHICH ARE ALL WRITTEN TO STDOUT**:
```
ERROR: first shared object number mismatch: hint table = n; computed = n
ERROR: first shared object offset mismatch: hint table = n; computed = n
ERROR: linearized file contains an uncompressed object after a compressed one in a cross-reference stream
ERROR: page length mismatch for page n: hint table = n; computed length = n (offset = n)
ERROR: part n is empty but nshared_total > nshared_first_page
ERROR: shared object n length mismatch: hint table = n; computed = n
WARNING: end of first page section (/E) mismatch: /E = n; computed = n..n
WARNING: first page object offset mismatch
WARNING: incorrect first object number in outline hints table.
WARNING: incorrect object count in outline hint table
WARNING: incorrect offset in outlines table: hint table = n; computed = n
WARNING: object count mismatch for page n: hint table = n; computed = n
WARNING: page n has shared identifier entries
WARNING: page n: shared object n: in computed list but not hint table
WARNING: page n: shared object n: in hint table but not computed list
```

**Comment by jberkenbilt** [comment] 2020-04-30 22:06
@vstepaniuk Yes, those are all linearization errors and warnings, and I searched for each one in the code and verified that they will be written to stderr now. The ones that are ERROR in 8.4.2 will be in WARNING in current versions. I decided to reclassify all findings by the linearization code as warnings since they don't prevent the PDF from otherwise working.

Would you like to test the fixed version? What's the best way to do that? Can you check it out of github (fixes are in master) and build from source? If not, what platform are you on? No worries if you can't or don't want to test the fixes.

**Comment by jberkenbilt** [comment] 2020-04-30 22:06
This is quite a collection of linearization errors. I'm curious as to where these files came form.

**Comment by vstepaniuk** [comment] 2020-04-30 22:27
> I'm curious as to where these files came form.

from different sources

Will try to install from source and re-check the files in a while

**Comment by vstepaniuk** [comment] 2020-05-04 13:58
I have v. 8.4.2 running, but the current master version on the configure stage says:
```
$ ./configure
...
configure: WARNING: unable to find required header jpeglib.h
configure: WARNING: unable to find required library jpeg
configure: error: some required prerequisites were not found
```

**Comment by vstepaniuk** [comment] 2020-05-09 10:20
`overflow reading bit stream` without a word ERROR or WARNING also goes to stdout..

**Comment by vstepaniuk** [comment] 2020-05-10 13:57
Also what about the `--no-warn` option?
it seems not to work in v. 9.1.1 - will it work now?

**Comment by jberkenbilt** [comment] 2020-05-10 22:53
I've reopened the issue and will check your other two comments (bit stream and --no-warn). I'll let you know and will make sure they both behave properly.

**Comment by vstepaniuk** [comment] 2020-05-11 04:47
Here is spreadsheet comparing errors and warnings from different utilities:
https://docs.google.com/spreadsheets/d/1UA9HOKW9rYnUOQ5JAnFUwZ7N6YftSotzhe46zBgiEJY/edit?usp=sharing
and the result is rather interesting

**Comment by vstepaniuk** [comment] 2020-05-11 07:23
Is it possible to fix those errors with qpdf?

**Comment by vstepaniuk** [comment] 2020-05-11 12:44
I mean the **pdftotext** and **pdfinfo** errors - I have solved almost all **qpdf** errors with **qpdf** itself

**Comment by jberkenbilt** [comment] 2020-10-20 21:35
@vstepaniuk Would you be willing to open a separate issue with the spreadsheet and errors? I'd like to close this one as soon as I resolve the remaining two comments, which I am working on onw.

**Comment by jberkenbilt** [comment] 2020-10-20 21:47
The problem with `overflow reading bit stream` will also be fixed. There was a place where I was writing an exception to stdout with no prefix. It now writes `ERROR: overflow reading bit stream` to stderr.

I am not seeing any issues with `--no-warn`. I will close this issue with a push shortly and get this into 10.0.2 or 10.1.0 or whatever is the next release.

I am adding a flag for the next release called `--warning-exit-0` that will cause qpdf to exit with a status of 0 instead of 3 when there are warnings. This should reduce some exit status checking when the intention is to truly ignore warnings. I will use it myself in one bit of code for work...

**Comment by vstepaniuk** [comment] 2020-10-20 22:30
Yes, Thanks!

**Closed** 2020-10-20 22:38 UTC
Labels: bug, next
