### ISSUE TITLE
xref object stream incorrectly inserted in place of object

### ISSUE THREAD

**Issue by ztravis** [qpdf/qpdf#809] opened 2022-10-27 22:00 UTC
For an input document where an xref object stream's number has been reused by a later incremental update (intentionally or not), `qpdf` will output the xref in place of the object.

One way that this might actually happen: if you start with a PDF with an object stream xref that incorrectly does not include its own object number and then later do an incremental update to append some content (e.g. a text stamp), you might miss the xref's object number when figuring out the next available object number to use. Your output is a PDF + an appended stamp where the previous xref has the same object number as your first stamp object (a font, for example). This PDF, while malformed, is still viewable in acrobat and other readers. If you pass it through `qpdf`, the xref object gets written in place of the intended object which can cause the output to no longer be viewable (e.g. if it's a font, at least in my version of acrobat - 9.5.5 on linux...).

The incremental update spec doesn't mention xref updates, and it seems like that isn't really meant to be done, but I do think it makes sense to always use the latest version of an object.

I've attached some sample data: clean.pdf is the original (malformed) PDF, clean-stamped.pdf is an example stamped/incrementally updated version (with an object number collision between the xref and a font), and clean-stamped-qpdf.pdf is the resulting output (with an xref object in place of that font).

[clean.pdf](https://github.com/qpdf/qpdf/files/9883364/clean.pdf)
[clean-stamped.pdf](https://github.com/qpdf/qpdf/files/9883365/clean-stamped.pdf)
[clean-stamped-qpdf.pdf](https://github.com/qpdf/qpdf/files/9883366/clean-stamped-qpdf.pdf)

**Comment by jberkenbilt** [comment] 2022-10-28 11:42
Thanks for the data and the clear explanation. This may require some special case code in qpdf, but I don't imagine it will be very hard to fix.

**Comment by m-holger** [comment] 2022-11-13 17:37
I am not convinced that the explanation of the problem is accurate.

It seems to me that the problem is that the XRef stream is object 25 0 according to the xref table, but is labeled (incorrectly) as 26 0 obj. This triggers an attempt to reconstruct the cross reference table, resulting in the XRef stream replacing the the font as object 26 0.

Would it make sense to check that xref table entry 26 points to a valid object 26 and if so relabel the xref stream as object 25 before deciding to reconstruct the cross reference table?

**Comment by ztravis** [comment] 2022-11-13 17:56
Sure, there may be some other mechanism at play here! I can try and generate a PDF where the xref table is really missing (rather than being incorrectly labeled as I've done in the example) and see what happens.

**Comment by m-holger** [comment] 2022-11-14 12:19
XRef / object streams are probably a bit of a red herring

What appears to be happening is that there are duplicate objects 26 0, one of which is really object 25 0. When qpdf attempts to access 25 0 it recognizes the error and attempts to correct the xref table, when in this case the proper way to correct this would be
to correctly label object 25 0 as 25 0.

This suggests to me the following heuristic when encountering an unexpected objgen (say for example 13 0) when attempting to load an object by offset:

Try to load object 13 0. If this is successful (i.e. if the xref table entry for 13 0 to a different valid object 13 0) than warn about the unexpected objgen but load the object anyway. Otherwise, repair the xref table, i.e. do what we are currently doing.

**Comment by m-holger** [comment] 2022-11-14 12:20
If you agree that this is the right approach I can do a PR.

**Comment by jberkenbilt** [comment] 2022-11-14 13:06
My impulse is to say that this is not a safe change.

I'd say to check how other viewers handle this including something poppler-based, evince, okular, ghostscript with old and new PDF interpreter, Adobe Reader if you have a copy, chrome, firefox. It may be possible to test their behavior with this case by creating a file where the object that is wrong in this way is something that will change the appearance in an obvious way like replacing one standard font with another. If it seems like other viewers are recovering in this fashion, especially Adobe reader, then it might be safe. If Adobe reader doesn't do this, then qpdf shouldn't do it.

It's likely that a heuristic like this will change the way a lot of files recover. Changing the logic around file recovery would be extremely high risk as a lot of people have come to depend on qpdf being able to recover certain files. A very common case of incorrect xref offsets is when people generate PDF templates with text, then fill in the text without adjusting offsets and lengths. I've seen this more times than I can count. If the difference in lengths happens to cause some objects to be offset just the right amount, this recovery would render those previously usable files useless. The PDF spec (earlier, pre-ISO versions) recommend recovery by looking for object numbers at the beginning of the line the way qpdf does it, so deviating from this is likely to cause qpdf to recover differently from other viewers, which could be hazardous.

**Comment by m-holger** [comment] 2022-11-14 13:43
Taken a step back, I am not entirely clear whether this is a / the real issue or an artifact of the (possibly) hand-crafted example of the issue that @ztravis  is experiencing.

If this is not the real / a real-life problem then I am not to keen to spend much time on it.

**Comment by ztravis** [comment] 2022-11-14 22:02
This is a real issue we've encountered - I can't share the specific PDFs involved, but I've generated some additional test data that mimics more closely the original xref data for at least one "type" of broken input which appear to have been generated by iText 5.4.5. In these, named "broken-*.pdf", the xref stream includes its own object number but as a free object. I've also generated a set of PDFs where the original stream was well formed but the stamping logic used the same object number as the previous xref (with/without incrementing the generation number). The same issue occurs in all of these cases.

That being said, I admit this is a pretty rare issue and requires a few steps to trigger and something to be wrong along the way (either a malformed starting PDF or buggy stamping logic). I also appreciate that this loading/cleaning code is sensitive and changes can have unintended effects elsewhere! If there's a way to fix this, or at least to warn when it happens, that would be great, but I understand that you can't deal with every possible weird thing in a PDF!

[broken.pdf](https://github.com/qpdf/qpdf/files/10007324/broken.pdf)
[broken-stamped.pdf](https://github.com/qpdf/qpdf/files/10007325/broken-stamped.pdf)
[broken-stamped-qpdf.pdf](https://github.com/qpdf/qpdf/files/10007326/broken-stamped-qpdf.pdf)

**Comment by jberkenbilt** [comment] 2022-11-14 22:33
It is normal and expected for the xref stream to be a numbered object that is not otherwise referenced. If something is reusing the object ID, that's a mistake. The xref stream's offset is supposed to be in the xref stream and counted in the /Size field in the trailer dictionary. What I see in broken.pdf is that the xref stream is object 25 and is accounted for by /Size being 26 in the trailer dictionary. However object 25 does not actually appear in the xref stream, which is wrong. I think this matches your description. However in this case, qpdf doesn't seem to have any issues with the file, so I guess I'm not seeing the problem you're seeing.

I'll study it more closely.

One thing that might help would be if you can provide the output of `qpdf --json-output --json-stream-data=none out.json` (from qpdf 11) on one of your broken files. You can inspect out.json before sending it. There may be metadata strings, like outlines, but there will be no stream data. You can redact the strings. In combination with this, you could provide the output of `qpdf --show-xref infile.pdf`.

Can we ignore the original files you posted in favor of the new ones? The difference appears to be that the original file (clean.pdf) has the xref stream numbered as 26 whereas broken.pdf has it numbered as 25. Was that a mistake in the hand-creation of an example?

**Comment by ztravis** [comment] 2022-11-14 23:38
In broken.pdf, the xref stream is object 25; there are 26 entries in the xref stream, but the last one (for object number 25) is a "free object" entry - the actual object reference does not appear in the xref stream. There's no issue running that PDF through qpdf, but the version "broken-stamped.pdf" has an incremental update that uses that "free" object number 25 for a font entry, and that stamped PDF (which has two object 25s - the xref, which never appears in an xref, and the font) is what ends up malformed when going through qpdf.

The two sets of files are very similar and exhibit the same issue. The first set was just simpler for me to generate, but in both cases the xref stream shares the same object number as a later font resource, and the xref stream object offset never appears in any xref table. That being said, the first example does have the additional issue that the original xref stream includes a reference to an object "25 0" that does not match the actual object found there, so feel free to ignore that set of files if that complicates the analysis.

I think an even simpler example would be a normal PDF with a correct xref stream that then had an incremental update that reused the object number and generation of the xref stream; based on the general idea of an incremental update the new object should take precedence over the xref, but I agree that reusing an xref object like this is a bad idea, and maybe not worth the effort to fix... In this case there is no malformed xref, just a reused object number.
Here is such an example:
[simple-stamp.pdf](https://github.com/qpdf/qpdf/files/10007816/simple-stamp.pdf)

**Comment by m-holger** [comment] 2022-11-15 19:13
The key problem with broken-stamped.pdf seems to be that there are two objects 25 0, the font and the xref stream. When doing a qpdf --show-xref qpdf correctly shows the font as object 25 0, but when rewriting the file it writes out the xref stream. Manually changing the  objgen of the xref stream to say 39 0 fixes the problem and allows qpdf to rewrite the file correctly.

None of the viewers I tried (including Acrobat) had a problem displaying the stamp correctly despite the errors in the pdf file. (This is probably not surprising given that they wouldn't have any reason to try access the xref stream by objgen.) 

Occular allowed me to edit the file. It maintained the xref streams for all incremental updates but changed the objgen for the first xref stream from 25 0 to the invalid 31 0. qpdf was able to rewrite the output correctly.

**Comment by jberkenbilt** [comment] 2022-11-19 20:01
I have done my analysis. The actual issue is that, when qpdf reads the xref stream, which it does early, it gets stored in the object cache by number even though it wasn't read through the xref table/stream. Then the reused object gets loaded into the xref table correctly, but since it's already in the cache, that doesn't have any effect. I believe the correct fix (a one-liner) is to simply not insert the object in the cache when we indicate to readObjectAtOffset that we don't care and are not checking the object ID. As already explained in the comments, this happens for xref streams and linearization hint tables, which I believe would be subject to the same bug. I will push up a fix momentarily.

**Comment by jberkenbilt** [comment] 2022-11-19 20:09
My one-line fix isn't quite right, but that is what the problem is.

**Comment by jberkenbilt** [comment] 2022-11-19 21:26
I've summarized the issue in more detail in a comment in the code, but the basic issue is this. When a file is updated by append, an object's xref entry would be first read in the later xref, then read again the earlier one, but the earlier one would be ignored because we want the later one to take precedence. For example:

* appended xref says object 10 is at byte offset 500; store that in the xref table
* original xref says object 10 is at byte offset 200; ignore that because object 10 is already in the xref table
* when resolving object 10, we go to offset 500

What's happening here is (using my made up numbers)

* appended xref says object 10 is at byte offset 500; store that in the xref table
* object 10 is the old xref stream, so it gets read and cached by its offset in /Prev, not through the xfef tale
* original xref says object 10 is at byte offset 200; ignore that because object 10 is already in the xref table
* when resolving object 10, although the xref table correctly says 500, we already have the object in cache, so the cached object prevails.

My "fix" is, for the special case of xref streams, we do not add the object to the object cache if the object is already in the xref table.

I believe the same bug applies to linearization hint streams, but there is other code that relies on information added to the cache for the linearization hint stream, so fixing it for that case would be quite a bit more difficult. This is a very obscure problem, and I think it would be even more obscure to have this bug with the linearization hint stream. The xref stream may often be at the end of the file and be the highest numbered object, so writers may reuse it. It's also more likely to be left out of the xref table. However linearization hint streams are floating around in the middle, and writing linearized files is much harder and therefore less likely to be done by junky writers that don't follow the spec. As such, I think the likelihood of encountering this bug with reused linearization hint streams is very low, and it's not worth reworking the existing code to make it possible to fix it for that case.

**Comment by jberkenbilt** [comment] 2022-11-19 21:27
My fix is in #819

**Comment by jberkenbilt** [comment] 2022-11-19 21:28
I hand-coded a simple PDF that has this problem. It's in the test suite. I used a font again for override but the font actually matters in the file, so the file displays differently when processed with qpdf before and after the fix.

**Closed** 2022-11-19 22:03 UTC
Labels: bug, next
