### ISSUE TITLE
qpdf-5.2.0 fails md5.test on upgrade from previous versions

### ISSUE THREAD

**Issue by tgurr** [qpdf/qpdf#56] opened 2015-11-10 10:50 UTC
build.log: http://dpaste.com/1ZECJWF.txt
qtest.log: http://dpaste.com/0SBCPNB.txt

The tests pick up the installed version. If I uninstall qpdf (5.1.3) first and then try to compile/run the tests/install qpdf-5.2.0 it works, which is a problem for source-based distributions like e.g. Exherbo or Gentoo.

**Comment by jberkenbilt** [comment] 2015-11-10 18:49
Thanks for letting me know about this. I'll have to look into a way to fix it since I'm just relying on libtool to get the library paths right. In the mean time, I will be releasing 6.0.0 with an soname bump, so for that specific case, you won't run into any issues. I will leave this issue open as a reminder.

**Comment by jberkenbilt** [comment] 2016-09-10 19:11
I'm going to try to look at this before the next qpdf release, but no guarantees. I'm trying to find some time to catch up.

**Comment by jberkenbilt** [comment] 2017-07-29 13:09
I should note that qpdf 5.2.0 inadvertently introduced a binary incompatibility and only lasted for a very short time. I routinely run qpdf tests with older, non-compatible versions installed, and I've never seen this. qtest always puts the working build directory first in the path, and libtool creates wrappers that ensure that the right library is used. Can you provide a recipe for reproducing this?

**Comment by jberkenbilt** [comment] 2017-08-20 04:02
I'm going to close this for now since I build from source all the time with older, non-compatible versions installed, and I never see this. If someone can find a way to reproduce it, please reopen. Thanks.

**Closed by jberkenbilt** 2017-08-20 04:02 UTC
Labels: incomplete

**Comment by jberkenbilt** [comment] 2017-10-22 14:13
I think this will be fixed by #158. Looks like I had the link directories in the wrong order.
