### ISSUE TITLE
fonts rendered glitchy

### ISSUE THREAD

**Issue by brendanhowell** [qpdf/qpdf#413] opened 2020-03-23 16:09 UTC
I wish I could be more precise but I can only explain by saying that my document ends up with what appear to be inverted fills when run through qpdf and printed. The original document, when rendered via PS looks fine. It is using a rather unusual font called fold (https://fontlibrary.org/en/font/fold) which has a lot of non-filled regions.

I'm using version 8.4.0 on debian.
[original.pdf](https://github.com/qpdf/qpdf/files/4370444/original.pdf)
[glitched.pdf](https://github.com/qpdf/qpdf/files/4370460/glitched.pdf)
[scanned_output.pdf](https://github.com/qpdf/qpdf/files/4370510/scanned_output.pdf)

**Comment by jberkenbilt** [comment] 2020-03-29 17:16
This may or may not be helpful, but when I open these in chrome, all three look the same. When I open them from the desktop using atril (which seems to have replaced evince on Ubuntu), original.pdf and glitched.pdf look the same with the second row being the same text bug gray instead of what looks like random symbols. This suggests to me that the problem is most likely not in qpdf but in whatever is rendering this for print. If you have a PDF-capable printer, you might try sending the PDF directly to the printer, or if you have access to Adobe Reader on some non-Linux system, see what happens there.

**Comment by brendanhowell** [comment] 2020-03-30 18:25
If I print it on my HP LaserJet 500 color M551 (with updated firmware) using the IPP Anywhere drivers it comes out glitched. But if I print using the Postscript driver it's fine. The difference is that the IPP Anywhere driver filters the PDF via pdf2pdf using the qpdf library. That's my logic for thinking qpdf is involved. I could also be that HP has a bug in the PDF interpreter.

**Comment by jberkenbilt** [comment] 2020-03-31 02:18
If supported, you might try sending to the printer directly and bypassing the drivers altogether. It's been quite a few years since I've had an HP printer, but it used to work to just ftp to the printer with anonymous ftp and upload the file. Also you can set up a printer with cups that goes straight to the "JetDirect" port, which I think is 9100, and tell it it's a generic printer with no drivers. There may be more modern options. I'd try connecting to the printer with a web browser and seeing what your options are. It would be good to conclusively rule qpdf in or out. I doubt it's qpdf because qpdf has no awareness of fonts and would just be preserving the contents of the font streams, but stranger things have happened, and it's always perilous for a software developer to claim the problem is in someone else's code. :-)

**Comment by brendanhowell** [comment] 2020-03-31 12:37
Indeed, the bug is either in the font, the rendering tool (weasyprint) or likely Cairo/Pango. The FTP trick is really cool and makes me love my HP even more. Thanks for your help and patience!

**Comment by jberkenbilt** [comment] 2020-04-02 01:02
Great, thanks for following up. I'm glad the trick was useful. :-) I'm going to go ahead and close the issue, but feel free to reach out if anything else comes up.

**Closed by jberkenbilt** 2020-04-02 01:02 UTC
