### ISSUE TITLE
Questions for closed issue #306 

### ISSUE THREAD

**Issue by jsxcool** [qpdf/qpdf#309] opened 2019-03-14 19:24 UTC
I tested two simple pdf files made by Latex, either containing a png or jpeg picture. (6.pdf is png, pic2.pdf is jpeg)

I tried the command  "qpdf --qdf --compress-streams=n --decode-level=all in.pdf out.pdf".
It did decode the image stream, but gave me unreadable bits. Like 
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

For "pdf-parse-content.cc", in function "handleObject(QPDFObjectHandle obj)", 
 if (obj.isInlineImage())  {
        std::cout << QUtil::hex_encode(obj.getInlineImageValue()) << std::endl;
  }
else    std::cout << obj.unparse() << std::endl;
This if statement was always false when I debug. So it se
[pdfTestFiles.zip](https://github.com/qpdf/qpdf/files/2954239/pdfTestFiles.zip)
[pdfTestFiles.zip](https://github.com/qpdf/qpdf/files/2954240/pdfTestFiles.zip)

emed skipping all image values.

For my purpose, I want to extract text and image contents from pdf file. So I can encode and compress them as my way. In the example folder, "pdf-invert-images.cc" seems should be into QPDFObjectHandle::getRawStreamData, but it still can't handle the two pdf files. So is there a easy-use API to extract image ? Or For different PDF producers, there exists decoding problem ?

_Originally posted by @jsxcool in https://github.com/qpdf/qpdf/issues/306#issuecomment-471733703_

**Comment by jberkenbilt** [comment] 2019-03-14 20:59
I think this is just an question of understanding how to work with binary data. I'll try to help if I have some time, but I think the library is working as intended. What you posted above looks like binary image data. It's what I'd expect. I'm not sure what exactly you're expecting to get from here. Did the answer I posted in your other issue not work? Thanks for any clarification.

**Comment by jsxcool** [comment] 2019-03-14 23:34
Thanks for your help, jberkenbilt. I know parsing PDF is really a hard work.

What I expect for image is the binary pixel (0, 1) for grayscale pictures, RGB pixel (0~255, 0~255, 0~255) for colored pictures. With these raw data, I can easily compress and re-construct the image. (shown in my python code screenshot on the attachment)

With the solution you posted, I can get the image stream, some of which are hex, some of which I don't know. It's true I don't have a good understanding for image stream. I don't know how PNG or JPEG encodes pixels. But how can I use the image stream data qpdf gives me? It seems incompletely decoded pixels.  

By the way, pdf file produced by Microsoft-Word still has the image problem. And qpdf can't handle pdf file produced by Google Docs.

[classification.zip](https://github.com/qpdf/qpdf/files/2968839/classification.zip)

**Comment by jberkenbilt** [comment] 2019-03-15 14:29
When you say it can't handle the file produced by google docs and that the word one still has the problem, what problem specifically are you talking about? Most images are not inline images, so checking for inline images will be relatively ineffective. There is a getPageImages method in QPDFPageObjectHelper that can help you find images in pages. It won't find inline images, but you can either combine that with something that finds inline images, or you can call externalizeInlineImages first, which will convert all inline images to normal images.

Regarding the format of images in PDF, if you decode the stream, they are just raw image data. They are not PNG or anything like that. The BitsPerComponent field tells you how many bits are in a component. So if it's 8, then each byte represents a component. The ColorSpace field tells you how many components make a pixel. The built-in ones like DeviceRGB, DeviceGray, and DeviceCMYK are easy. They are 3, 1, and 4 components per pixel respectively. Using this information combined with width and height, you can map the binary data into pixels. Some cases are more complex to handle, such as BitsPerComponent of 1 for bitonal images. Some color spaces are ICC-based or otherwise derived. Those are more difficult to interpret. If you are looking at raw data, not filtered (i.e. compressed) and the compression type is DCTDecode, the raw image data is JPEG-encoded, and the stream is literally a JPEG file. You could extract the raw data without touching it and open it in any image viewer that supports JPEG, which is pretty much all of them.

Note that QPDF doesn't have any native support for image file formats. It gives you access to the raw data, but you will have to write additional code to convert them into usable image files. Other libraries can do that, but it's not something that qpdf currently supports.

**Comment by jberkenbilt** [comment] 2019-07-13 14:33
I'm going to close this, but feel free to reopen if you have further questions on this topic.

**Closed by jberkenbilt** 2019-07-13 14:33 UTC
