### ISSUE TITLE
Unabled to read this damaged file

### ISSUE THREAD

**Issue by akdor1154** [qpdf/qpdf#391] opened 2019-12-20 06:30 UTC
QPDF cannot read this file:
```
WARNING: /home/jarrad/Downloads/STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf: file is damaged
WARNING: /home/jarrad/Downloads/STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf (offset 116): xref not found
WARNING: /home/jarrad/Downloads/STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf: Attempting to reconstruct cross-reference table
/home/jarrad/Downloads/STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf (offset 1477088): unable to find /Root dictionary
```

Chromium (PdfJS?) seems to read it OK, I don't have a machine with Adobe Reader on hand sorry but I expect it's ok there as well. I fully expect the file is damaged, but consider this a feature request for QPDF to read it anyway :)

Let me know if there's anything else I can provide. Sorry that I can't do much more than report here, my knowledge of the PDF format is non-existent. :(
[STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf](https://github.com/qpdf/qpdf/files/3986980/STANDREWSYR6BOOKLISTLETTERANDORDERFORM.pdf)

Tested with master as of 2019-12-20, same behaviour in 8.0.2.

-Jarrad

**Comment by jberkenbilt** [comment] 2019-12-20 18:25
I always like getting damaged files and trying to see if I can get qpdf to read them. I'll definitely give this a look next time I have a chance to work on it. Usually I try to steal some time for qpdf during the holidays! Thanks.

**Comment by jberkenbilt** [comment] 2019-12-20 18:25
"next" tag indicates intention to study this, after which I can prioritize if/when to fix, depending on the nature of the problem.

**Comment by jberkenbilt** [comment] 2020-01-26 21:09
Looks like stopping at the first `%%EOF` might make this file recoverable, but it would break lots of other files. After spending about a half an hour on this, I am able to manually recover the file to the point where it looks the same as when chrome views it, but I don't see a quick way to make a safe change that would do this. I will leave this open, but I'm not going to fix it for right now.

**Comment by deepaksen1996** [comment] 2021-07-22 10:52
I would suggest trying opening the file with pdfrw==0.4, it automatically fixes the pdf while reading and writing. Then you can move ahead with your further process.

# !pip install pdfrw==0.4
from pdfrw import PdfReader, PdfWriter
def alter2(file_path):
    input_pdf = PdfReader(file_path)
    out_pdf = PdfWriter()
    for page in input_pdf.pages:
        out_pdf.addpage(page)
    new_path = file_path.split('.pdf')[0]+'_new.pdf'
    out_pdf.write(new_path)
    return new_path

**Comment by liam-mills** [comment] 2023-04-04 01:11
Sorry to re-open an old thread, but I'm experiencing the same issue as OP, however the PDFs I'm trying to use are not corrupted and actually open fine. They are reported to be damaged but I don't see any obvious difference between files that work and files that don't.

I am attempting to password protect some PDFs, and the failing PDFs return the below:

`qpdf --encrypt password123 password123 256 -- "PasswordProtectMe.pdf" PasswordProtected.pdf`

`WARNING: PasswordProtectMe.pdf: file is damaged
WARNING: PasswordProtectMe.pdf (offset 17317): xref not found
WARNING: PasswordProtectMe.pdf: Attempting to reconstruct cross-reference table
qpdf: PasswordProtectMe.pdf: unable to find /Root dictionary`

The affected PDFs are using PDF v1.4, but telling QPDF to use this PDF version has no change in the outcome. I do have other PDFs which are v1.4 that work fine, and get password protected properly.

Any assistance would be greatly appreciated. Let me know if I can provide any additional information, cheers.

**Comment by jberkenbilt** [comment] 2023-04-04 12:52
@liam-mills I'd have to see a file to know what the issue is.

**Comment by liam-mills** [comment] 2023-04-10 23:46
Hi @jberkenbilt thanks for your reply.

The PDFs in question have some sensitive information from our clients, would sending you the PDF headers from a functional and a non-functional PDF respectively suffice? Cheers.

**Comment by jberkenbilt** [comment] 2023-04-15 23:20
@liam-mills Not sure what you mean by "headers", but if you use `qpdf --json`, it will generate a json file that doesn't include images or page contents. It does however include some text like bookmark labels and some annotation information. If the file is damaged in a way that `qpdf --json` can't open it, then I'd probably have to actually look at the file.

**Comment by jberkenbilt** [comment] 2023-12-29 16:58
Closing this -- these seem like problems with broken PDF files, not actual qpdf issues.

**Closed by jberkenbilt** 2023-12-29 16:58 UTC
