### ISSUE TITLE
bash auto-completion

### ISSUE THREAD

**Issue by vstepaniuk** [qpdf/qpdf#441] opened 2020-05-11 02:58 UTC
Ubuntu 20.04
qpdf version 9.1.1
```
for file in *; do qpdf <Tab>

bash: compgen: warning: -C option may not work as you expect
basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 0)
```

**Comment by vstepaniuk** [comment] 2020-05-11 03:00
Though just `qpdf <Tab>` works correctly..

**Comment by dreua** [comment] 2020-05-12 17:16
After enabling bash completion (`eval $(qpdf --completion-bash)` since [it is missing on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1834337)), I can confirm this in Fedora 31 and 32. It is probably a general problem with the way qpdf's completion works. 

qpdf is the only program using the -C option for completion on my system. (Check via `complete | grep -- -C`)

(qpdfs completion is `complete -o bashdefault -o default -o nospace -C qpdf qpdf`)

Same story with `sudo qpdf`.

**Comment by jberkenbilt** [comment] 2020-05-12 17:56
I was being lazy by using -C. It's not very robust and causes different problems with zsh. Probably the correct fix is to be unlazy when implementing completion. Using -C is better than nothing but not as good as it should be.

**Comment by jberkenbilt** [comment] 2020-05-12 17:59
For what it's worth, aws cli also uses -C and has exactly the same problem. This may be a bash bug, and not a qpdf bug. Bash is passing a negative argument in a place where one would not be expected. I'll have to check the bash docs and make sure my expectations are not off.

**Comment by jberkenbilt** [comment] 2021-05-08 11:35
I am no longer able to reproduce this bug with current bash, so I am closing it.

**Comment by dreua** [comment] 2021-05-12 07:38
I can still reproduce with 5.1.0 unfortunately, not sure which version you tested.

```
[red@cted ~]$ sudo qpdf bash: compgen: warning: -C option may not work as you expect
basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 0)

[sudo] password for da: 
sudo: a password is required
[red@cted ~]$ for file in *; do qpdf bash: compgen: warning: -C option may not work as you expect
basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 0)
^C
[red@cted ~]$ qpdf --version
qpdf version 10.3.1
Run qpdf --copyright to see copyright and license information.
[red@cted ~]$ bash --version
GNU bash, version 5.1.0(1)-release (x86_64-redhat-linux-gnu)
[...]
```

**Comment by jberkenbilt** [comment] 2021-05-12 10:59
Sorry, I can reproduce it. I accidentally tested it using zsh. Must have been a loose brain cable. Anyway, it is at least partially a bash problem....but I can make qpdf sanitize the information passed in from bash, which it should be doing anyway, so I'll leave this open and fix that aspect of it.

**Comment by jberkenbilt** [comment] 2021-05-12 11:02
Note to self: study this using my compgen example script...

**Comment by jberkenbilt** [comment] 2021-05-12 12:57
I fixed qpdf's messing up on string bounds when given invalid inputs, but of course I can't fix that bash is giving qpdf invalid inputs. After this fix, you just get
```
bash: compgen: warning: -C option may not work as you expect
```
Too bad I used zsh by mistake and this missed the train for 10.3.2. Oh well. There will be another release at some point.

**Comment by dreua** [comment] 2021-05-12 17:35
No worries, I don't consider this a high priority issue :wink: Thanks for taking care of it anyways, would be nice to have it fixed at some point.

**Closed** 2021-05-13 17:55 UTC
Labels: bug, next
