### ISSUE TITLE
Form still not working with pdftk when file decrypted

### ISSUE THREAD

**Issue by Sen** [qpdf/qpdf#12] opened 2013-06-13 15:30 UTC
PDF file: http://www.immi.gov.au/allforms/pdf/1066.pdf
Part C, question 53. Title(mr/mrs/miss/ms)

Only this kind of Button not working, other parts seems work.

**Comment by jberkenbilt** [comment] 2017-07-29 12:48
I never did anything with this, and I can't longer reproduce it. Work is being done on form flattening as well. I'm going to close this as "incomplete", but feel free to reopen if this is still an issue.

**Closed by jberkenbilt** 2017-07-29 12:48 UTC

**Comment by jberkenbilt** [comment] 2017-07-31 01:02
Actually, I found that I had previously saved the zip file. I am not able to reproduce any issues with the latest qpdf.

**Comment by jberkenbilt** [comment] 2017-07-31 01:02
For future record, note to self: files saved in `~/source/qpdf/misc/1196s*`
