### ISSUE TITLE
[Feature request] Edit document info

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#360] opened 2019-09-08 18:34 UTC
Hi. I suggest to add abilities to edit "document info". This will allow developer of PDF Mix Tool to include this new functionality in his program.

To make it more clear please see the following screenshoot (from Windows program):

![document-info](https://user-images.githubusercontent.com/25375330/64492765-4570de00-d267-11e9-97c7-37983c4a66c1.PNG)

Also see the following 2 screenshoots which show what "Additional metadata" in above screenshoot mean:

![Capture -1](https://user-images.githubusercontent.com/25375330/64492829-232b9000-d268-11e9-91ef-b421e7bb4512.PNG)

Regarding "Copyright Status" in above picture it includes the following options:
- Unknown
- Copyrighted
- Public Domain

![Capture -2](https://user-images.githubusercontent.com/25375330/64492832-29ba0780-d268-11e9-915b-d785a969659f.PNG)

Also, address kindly the following related issue, that I already opened it since long time:
https://github.com/qpdf/qpdf/issues/108

**Comment by jbarlow83** [comment] 2019-09-10 00:27
For basic XMP you can use use pikepdf (Python binding library I wrote for qpdf). 

Given the complexity of XML and the additional XMP rules I have a feeling qpdf won't be adding it natively for some time. You can also extract the XMP block using qpdf and edit with it a full featured library like python-xmp-toolkit or libexempi.

**Comment by Nokia808** [comment] 2019-09-10 13:50
@jbarlow83 
Hi. Many thanks for your replay ! 

Kindly can you clarify the following:

1) does pikepdf is dependent on QPDF (need QPDF as dependency) or not ? If yes, so okay from adding it to elevate power of QPDF. But if it a standalone library, then does it wise to use both of them by GUI or it is better to remove QPDF & use pikepdf instead ?

2) I found the following library:
https://sno.phy.queensu.ca/~phil/exiftool/
it is well maintained. It is used by GUI for meta data edit of PDF on Linux which is:
https://github.com/Glutanimate/PDFMtEd
it seem that PDFMtEd is a dead project & not well known.
Can you please evaluate exiftool library & inform us which is better for document info edit of PDF: pikepdf or exiftool ?

Please notice that on page of exiftool there is the following statement:
"ExifTool is not guaranteed to remove metadata completely from a file when attempting to delete all metadata. For JPEG images, all APP segments (except Adobe APP14, which is not removed by default) and trailers are removed which effectively removes all metadata, but for other formats the results are less complete:
    PDF - The original metadata is never actually removed."

Which is better: pikepdf or exiftool ?

**Comment by jbarlow83** [comment] 2019-09-10 20:29
1. It depends on libqpdf. I don't know what makes sense for a GUI, it would depend on the application design.
2. I haven't used exiftool extensively so I don't know. It sounds like they update metadata by appending, so the original metadata stays in the data stream. pikepdf/QPDF can remove the original metadata if that's an issue for you.

**Comment by Nokia808** [comment] 2019-09-10 21:20
@jbarlow83 
Okay point (2) is clear: ExifTool is not suitable. 

But there is something confusing. You said:
"pikepdf/QPDF can remove the original metadata if that's an issue for you." 
But from your 1st comment in this thread I understood that QPDF has no ability. But you now said pikepdf/QPDF !
Dear it may be my mistake when post 2nd & 3rd screenshots about "Additional metadata". Let we omit "additional metadata". Let we consider only the following metadata:
- Document title
- Author
- Subject
- Keywords
- Creator application
- Producer application
- Creation date
- Last modification date
Only these no more. Is QPDF able to edit & remove them by itself or we have to use pikepdf ?

**Comment by jbarlow83** [comment] 2019-09-10 21:34
The problem is that PDF metadata is a small XML file in the XMP schema that gets attached to a PDF. XMP is a complicated format with, in my opinion, questionable design decisions that add a lot of complexity without much benefit. exiftool can edit XMP records, but it cannot properly remove an old one from a PDF because editing PDFs is hard. QPDF can delete and add the whole XMP record as a unit, but cannot edit XMP data. pikepdf has limited capabilities to edit XMP, and can use QPDF to properly delete the old record and delete the new one. Nothing is perfectly suited.

**Comment by KurtPfeifle** [comment] 2019-09-11 08:04
There are two methods to store metadata in PDF:

   1.

   The “old” and initial method, already present in PDF-1.0, stores only
   very limited information in the “document information dictionary”. It
   supports the following “keys”, any of which may be empty and not contain
   any real value:
   - Title
      - Subject
      - Author
      - Keywords
      - Creator
      - Producer
      - CreationDate
      - ModDate
      - Trapped
   2.

   The newer XML *metadata stream* which was introduced with PDF-1.4. If
   present it MUST contain at least the same info as "1." contains, and
   additionally can contain any extra arbitrary metadata info you can think
   of. The XML structure of the metadata stream must conform to the *XMP:
   Extensible Metadata Platform* specified by Adobe.

The CLI tool pdfinfo shows the contents of “1.” by default. For dumping
“2.” you have to run the tool with the added parameter "-meta". Maybe a
first simple step could be to support the "1." variant for cases where "2."
is not present (I think these kind of documents are very rare nowadays).

Just be aware: If you'd modify "1." where "2." also is present, you'll HAVE
to modify "2." accordingly, otherwise the resulting doc would not confirm
to the PDF standard.

Am Di., 10. Sept. 2019 um 23:34 Uhr schrieb jbarlow83 <
notifications@github.com>:

**Comment by jbarlow83** [comment] 2019-09-11 08:28
@KurtPfeifle That is an additional complication I did not get into. 

pikepdf attempts to synchronize edits to DocInfo and XMP. No idea of exiftool is capable of that, but XMP editors in general can't edit a DocInfo block, and in general you cannot convert XMP to DocInfo because the former allows for multivalued fields with tag attributes.

**Comment by jberkenbilt** [comment] 2023-12-29 16:55
Closing for inactivity.

**Closed by jberkenbilt** 2023-12-29 16:55 UTC
