### ISSUE TITLE
Windows 10: version 9.1.1 requires administrator privilege to convert PDF

### ISSUE THREAD

**Issue by fgrieu** [qpdf/qpdf#397] opened 2020-01-29 15:01 UTC
On two Windows 10 machine (French x64,  version 10.0.18363.592 fully patched), executables of version 9.1.1 (as in qpdf-9.1.1-bin-msvc64.zip and qpdf-9.1.1-bin-mingw64.zip) fail with "unable to acquire crypt context with new keyset: error number 5: Access Denied" (later two words in French) for all commands trying to read/write PDF, unless cmd.exe is run with administrative privileges.
Deactivating antivirus, shortening the PATH variable, making qpdf-9.1.1\bin the current directory does not change the symptom.
No such issue with 9.1.0, nor under a Windows 7 VM.
Verbatim from command line follows (tst1.pdf is a small plain vanilla PDF).
```
C:\util> .\qpdf-9.1.1\bin\qpdf.exe --version
qpdf version 9.1.1
Run qpdf --copyright to see copyright and license information.

C:\util> .\qpdf-9.1.1\bin\qpdf.exe tst1.pdf tst1out.pdf
unable to acquire crypt context with new keyset: error number 5: AccÞs refusÚ.


C:\util> .\qpdf-9.1.0\bin\qpdf.exe tst1.pdf tst1out.pdf

C:\util>
```
<sub>Side note: incorrect accentuated characters in French error messages are a common annoyance on the Windows command line (but that's the lesser of localization issues: there's chkdsk's garbled logs, help and error messages gone from informative to worse than useless, _(authorization to) read access rights (of files)_ translated to the effect of _authorization to read (file data)_ in the dialog to adjust a file's access rights...</sub>

**Comment by jberkenbilt** [comment] 2020-01-31 01:46
I just tried running qpdf 9.1.1 on a freshly installed Windows 10 system using a non-administrator user, and I am not able to reproduce this problem. There is something about this crypt context that I don't understand. Most of this code has been contributed by other users. I'm not sure how to solve this, but it doesn't appear to be a problem that affects all Windows 10 non-admin users.

**Comment by jberkenbilt** [comment] 2020-01-31 01:48
Regarding internationalization, sadly, qpdf is not internationalized. I'm just one person, and I only speak one language. Maybe someday. I wish qpdf were better behaved regarding internationalization, but it was off my radar when I originally started writing this 18 years ago, and I have never gone back and done it right. But even if I did, I don't have any way to get translations.

**Comment by fgrieu** [comment] 2020-01-31 09:30
I apologize for reporting something that is no longer reproducible including on one of the tow machine where it previously occured, and on a frsh Windows 10 x64 Fr install. I propose that we close the bug.

I'm perfectly happy with qpdf in English, and an occasional message in French as translated by Windows, complete with garbled accents. Don't get me wrong: my rant was against Windows!

**Comment by jberkenbilt** [comment] 2020-01-31 18:14
No apology needed. This particular problem has been elusive. I don't know why it happens sometimes and why it doesn't. At least recent changes should make it easier to diagnose and should reduce the likelihood of its happening. I'll go ahead and close this. Thanks for taking the time to report.

**Closed by jberkenbilt** 2020-01-31 18:14 UTC
