### ISSUE TITLE
error "operation for Name object attempted on object of wrong type"

### ISSUE THREAD

**Issue by rbro** [qpdf/qpdf#74] opened 2016-04-05 15:23 UTC
I'm running version 6.0.0 and seeing an error "operation for Name object attempted on object of wrong type" when running the command:

`qpdf --empty --pages a.pdf 1-z -- b.pdf`

The pdf file doesn't return any errors when running qpdf --check.  It also runs cleanly when running:

`qpdf a.pdf b.pdf`

I'm not able to share the file, but are there things I can do to try to narrow it down?

**Comment by jberkenbilt** [comment] 2016-09-10 15:09
Hi, sorry for not answering this. I must have missed it originally, and it's been months since I've had a block of time to look at it. I don't have anything specific to suggest. You can look at it in a debugger. This indicates something invalid in the PDF file. Next time I have a good block of time to work on qpdf, my highest priority item is to audit all the errors and figure out ways to recover that don't result in fatal stops.

**Comment by jberkenbilt** [comment] 2016-09-10 19:34
There are some other issues around dictionary parsing code where qpdf gets confused about malformed dictionaries such as #36 and #64. I don't know whether it's the same thing, but once I fix those, maybe this problem will go away.

**Comment by jberkenbilt** [comment] 2016-09-10 19:35
Note to self: next tag indicates intent to request retest if the related issues are fixed.

**Comment by jberkenbilt** [comment] 2017-07-28 14:27
I'm going to make a fix to qpdf that should hopefully make qpdf able to recover from almost all of the cases where this exception is currently being thrown. This will go on imminently. It's next on my list of fixes.

**Comment by jberkenbilt** [comment] 2017-07-29 23:20
I've fixed several cases of this. Without a concrete file to reproduce this with, I can't really know whether the issue is fixed the file in question. Unfortunately, I have not coded a fix that would allow this to be handled gracefully in all cases. There are hundreds of cases in qpdf where we call getName(). Some of them check the type, and some don't. Ideally, there should be a getName variant that takes a default value, but in many cases, there is no sensible default, so the places that call getName would have to be modified to handle each case of malformed data explicitly.

**Comment by jberkenbilt** [comment] 2017-07-29 23:32
I'm going to close this issue in the absence of a reliable way to reproduce it. I have made changes that will likely handle most of the cases where this error could occur, usually be treating the object that was being read at the time as null. This will often result in other problems, but at least in most cases a useful error message should be generated. There are still may cases left in the code where this could still occur. Fixing it across the board would be a major undertaking. Hopefully it's much better now though.

**Closed by jberkenbilt** 2017-07-29 23:32 UTC
Labels: next
