### ISSUE TITLE
qpdf --check and exit codes

### ISSUE THREAD

**Issue by rbro** [qpdf/qpdf#50] opened 2015-08-28 13:21 UTC
I am running qpdf --check against a pdf and getting the following output:

```
checking /tmp/test.pdf
PDF Version: 1.2
File is not encrypted
File is linearized
WARNING: incorrect object count in outline hint table
```

but the exit code is 2.  I see the documentation says the exit code will be 2 if errors, and 3 if warnings.

Should the above be considered a warning with a exit code of 3?  I am able to process the file with qpdf, so it seems to be a valid pdf.

Thanks for your help.

Ryan

**Comment by jberkenbilt** [comment] 2015-08-28 14:24
Is that the complete output? It doesn't look like enough output. Is there anyway you can make the file available to me?

**Comment by rbro** [comment] 2015-08-29 18:28
Thanks.  Yes, that is the complete output.  I'm not able to share the file, but are there other things I could do to try to narrow it down?  Also, the reason I asked this is that I'm using qpdf to merge lots of documents together like:

```qpdf --empty --pages 1.pdf 1-z 2.pdf 1-z 3.pdf 1-z 4.pdf 1-z -- output.pdf```

where the number of pdf files could be in the hundreds.  Right now, if one of the pdf's has an error, the merge fails.  I was looking for a way to check each file in advance to see if qpdf will process it.  If --check returns an exit code of 2, will qpdf still be able to process it?  I'm finding in some cases it might, in which case, running --check might be too strict for me.

Alternatively, would it be possible to add an argument to the above merge command to "continue if a file has an error"?  And then perhaps write the failed files to a separate log file?

**Comment by jberkenbilt** [comment] 2016-09-10 18:40
Sorry for not replying to this sooner. I'm trying to get a little caught up, though I'm not going to get all the way caught up. I'll try to make sure that my fixes I'm hoping to get in to be more forgiving of errors will improve qpdf's handling of this case.

**Comment by jberkenbilt** [comment] 2019-01-18 14:54
@rbro Can you retry this with 8.3.0? It may still be an issue, but I have made a number of enhancements that may have mitigated this. If it's no longer a problem or no longer relevant, we should go ahead and close the issue. Fairly soon I'm hoping to rework some of the linearization code, but with 8.3.0, many conditions that used to cause qpdf to exit are now just warnings.

**Comment by v-garcia** [comment] 2019-05-25 05:11
Seems that Issue is still here on qpdf version 8.4.2.
Exit code is 2, with only warnings.
Here is the full output.

```
checking `.\file.pdf`
PDF Version: 1.6
File is not encrypted
File is linearized
WARNING: incorrect object count in outline hint table
```

Vincent.

**Comment by jberkenbilt** [comment] 2019-05-26 22:34
I see what the problem is. This should be an easy fix. The linearization checking code is treating warnings as errors even though it is outputting them as warnings. I will make sure this is fixed in the next non-patch release, which I will probably make in late June.

**Closed** 2019-06-22 23:47 UTC
Labels: bug, next

**Comment by guysoft** [comment] 2020-05-26 13:05
Hey, is there any place in the documentation that says what are the exit codes?
I can sort of figure that 3 is for warnings and 2 is for error, what is 1?

**Comment by jberkenbilt** [comment] 2020-05-26 13:26
I don't use 1 since the shell uses 1 if it fails to execute the program. So if I run qpdf and it exits with 1, it means it's not installed or not executable or something. Avoiding exit 1 in my own code is a tip I picked up early in my software career.

Looking through the docs, it's not spelled out that clearly. I will make a note to add something to the documentation. If you run `qpdf --help`, it is mentioned at the very bottom of the help, which I realize is too long for anyone to ever actually read.

**Comment by jberkenbilt** [comment] 2020-05-26 13:27
@guysoft See previous comment. But to answer your question 2 and 3 are the only exit codes qpdf uses.

**Comment by guysoft** [comment] 2020-05-26 14:41
Thanks @jberkenbilt . was looking at the Manual on the website. Also man. Both didnt have what ``--help`` provided. Thanks!
