### ISSUE TITLE
Building under MinGW with UNICODE enabled fails

### ISSUE THREAD

**Issue by ancwrd1** [qpdf/qpdf#65] opened 2015-12-17 09:28 UTC
When building the library for Windows target with UNICODE and _UNICODE preprocessor flags the compilation fails.

The QUtil.cc contains a call to GetEnvironmentVariable, which gets preprocessed into GetEnvironmentVariableW resulting in compilation errors.

Same issue for the SecureRandomDataProvider.cc and CryptAcquireContext API call.

The simple resolution is to use the non-Unicode functions: GetEnvironmentVariableA, CryptAcquireContextA

**Comment by jberkenbilt** [comment] 2015-12-17 17:45
Thanks for the report. I will keep this in mind for the next update. Hopefully I will be able to reproduce it in my build environment.

**Comment by jberkenbilt** [comment] 2023-12-29 16:16
I'm closing this because it's very old and all the tools have moved on.

**Closed by jberkenbilt** 2023-12-29 16:16 UTC
