### ISSUE TITLE
qpdf SOMETIMES remains hanging in QPDFWriter::popPipelineStack()

### ISSUE THREAD

**Issue by ZeeOrm** [qpdf/qpdf#52] opened 2015-10-01 13:28 UTC
hi,

release compiled qpdf SOMETIMES remains hanging in the
 QPDFWriter::popPipelineStack(PointerHolder<Buffer>\* bp) function's
 while cycle (see below)

``` c++
   delete this->pipeline_stack.back();
    this->pipeline_stack.pop_back();
    while (dynamic_cast<Pl_Count*>(this->pipeline_stack.back()) == 0)
    {
        Pipeline* p = this->pipeline_stack.back();
        this->pipeline_stack.pop_back();
        Pl_Buffer* buf = dynamic_cast<Pl_Buffer*>(p);
        if (bp && buf)
        {
            *bp = buf->getBuffer();
        }
        delete p;
    }
    this->pipeline = dynamic_cast<Pl_Count*>(this->pipeline_stack.back());
```

with the following call stack:

```
(gdb) bt
#0  0x60000000e10d5ec0:1 in QPDFWriter::popPipelineStack ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:909
#1  0x60000000e10e2050:0 in QPDFWriter::unparseObject ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:1520
#2  0x60000000e10dd130:0 in QPDFWriter::unparseObject ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:1192
#3  0x60000000e10d7740:0 in QPDFWriter::writeObject ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:1815
#4  0x60000000e10c9380:0 in QPDFWriter::writeStandard ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:3032
#5  0x60000000e10bab50:0 in QPDFWriter::write ()
    at ../../../tgs/t3/iqpdf/src/libqpdf/QPDFWriter.cc:2323
#6  0x60000000e1154d50:0 in ppdf::CPdfCodecQpdf_001::Write ()
    at ../../../src/pdfqpd/pdfcodecqpdf.cpp:699
#7  0x60000000e11d3a20:0 in ppdf::CPdfMergeXObject_001::CreateTempFile ()
    at ../../../src/pdfupd/pdfmergexobject.cpp:498
```

some idea?

thanks in advance

**Comment by jberkenbilt** [comment] 2015-10-01 15:29
There's not really enough information for me to go on here. It looks like you're using the library from your own code. The line numbers in your stack trace don't match my line numbers. Is your qpdf modified? If not, what version are you using? Have you manipulated the PDF through calls to various QPDF methods before invoking QPDFWriter? Is it possible for you to reproduce this through the command line qpdf tool?

Looking over the code in QPDFWriter, it's hard for me to see how it could be hanging in popPipelineStack except in the case of a memory error. The method asserts that the stack has a depth of at least 2 and that the top of the stack is the current pipeline, and the while loop unconditionally pops the stack. If there were no Pl_Count on the stack (and there should always be because activatePipelineStack make sure of it), it would probably segfault rather than hang.

If I were to debug this, I guess I'd just look carefully at the pipeline stack and make sure it was sane. Basically the base of the stack should be a count and then everything else should be either some kind of encryption or compression filter or something to capture stream contents into a buffer.

**Comment by ZeeOrm** [comment] 2015-10-05 09:06
hi Jay,

thanks for your quick answer,
sorry i was deep in an other urgent case to fix first

so the qpdf is a qpdf-5.1.2 version
  the shift in line numbers is due to some temporary debug changes of mine,
  the qpdf lib is (as far as i know) not modified but only used in our
products
    ( sorry i am not the product's responsible developer,
      i am involved only due to being the problem actually happened
      on a unix (HPUX/Itanium) platform )

reproducing the problem is not easy, it happens only sometimes
and only with our official release compiled code
   so i have to "debug" the release version optimized code
   at assembly level after attaching with the debugger if the
   hang up happens during the tests :-)

our official compiler is an aCC: HP aC++/ANSI C B3910B A.06.10 [Mar 22 2006]

i try to go now further based on your hints

anyway could you give more details on how to judge
  if the pipeline stack is sane?

kind regards,
Zee (Zoltán)

**Comment by jberkenbilt** [comment] 2018-06-18 15:09
I'm going to close this issue because of not having enough information to work on it, but also because, since it was created, I have fixed many bugs of this type where qpdf could get into infinite loops. If you are still seeing this problem with current qpdf (>= 8.0.2), please feel free to reopen this issue. Thanks!

**Closed by jberkenbilt** 2018-06-18 15:09 UTC
