### ISSUE TITLE
Feature request: page "stamping"

### ISSUE THREAD

**Issue by kilburn** [qpdf/qpdf#207] opened 2018-05-06 10:50 UTC
We would like to _stamp_ PDF pages with pages from another file. By stamping I mean "pasting" pages from one pdf on top of another pdf. See the example on the image, that represents stamping `B.pdf` on top of `A.pdf` to obtain `AB.pdf`.

![stamping](https://user-images.githubusercontent.com/116100/39672512-971e5a3e-512b-11e8-92cd-647b0062f7ac.png)

I'm envisioning something on the lines of:
```
qpdf A.pdf -stamp B.pdf -output AB.pdf
```

We are currently using `pdftk` for that task, but we'd love to get rid of it. I don't know whether this is a relatively easy operation or a hard one though.

**Comment by jberkenbilt** [comment] 2018-12-17 13:11
I'm working on some other enhancements that may make something like this scriptable using the CLI, but I doubt I will prioritize adding this as a first-class feature. I'm labeling this "adjacent" as a reminder to myself to keep in mind while working on the other enhancements.

**Comment by colourful-land** [comment] 2018-12-28 00:33
It's a frequently used use-case and I think it's one of the main reasons people use pdftk. Although it says "stamping", it's more often used for adding a singature on a pdf file for government organisations who insists on only accepting non-cryptograaphic signatures.

**Comment by jberkenbilt** [comment] 2019-01-11 12:50
After the changes made for 8.3.0, this should be relatively easy to implement. I'm going to try to prioritize it for 8.4.0.

**Comment by colourful-land** [comment] 2019-01-11 13:09
@jberkenbilt it's amazing that you have always been so helpful to the community!

**Comment by kilburn** [comment] 2019-01-11 13:53
These are awesome news @jberkenbilt ! Do not hesitate to ask here if you need some testing or anything. Thanks!

**Comment by jberkenbilt** [comment] 2019-01-11 15:35
@kilburn I'd be interested in your ideas as to how the feature should work. In your example, it looks A and B are both single-page documents. How should it work? I can think of various options from simplistic to complex. My first thought would be something like `qpdf A.pdf AB.pdf --stamp=B.pdf` would just stamp pages of B.pdf onto pages of A.pdf in a collation kind of style. So if A.pdf had 5 pages and B.pdf had 2, page 1 of B.pdf would be stamped onto the odd pages of A and page 2 of B.pdf would be stamped onto the even pages of B. This seems like a good model because it makes it easy to stamp left and right pages differently.

One could imagine making it more complicated with page ranges, etc., but maybe that's just overkill. If someone really needed that, they could probably do it in stages, especially now with the new `--collate` option added in qpdf 8.3.0.

From a library standpoint, what I will most likely do is to add helper methods that allow extraction of a page as a form XObject, which can then just be drawn on the destination page with a specified transformation matrix. Virtually all the code to actually do that now exists because it's basically how qpdf 8.3.0's appearance stream generation works. Page stamping is nothing more than a simpler version of annotation flattening. With the many hours of effort that went into that, page stamping is probably something I could knock out in a few hours. I know of at least two cases where people are already using qpdf to convert pages to form XObjects, so providing direct library support for it would be useful anyway.

**Comment by jberkenbilt** [comment] 2019-01-11 15:44
@colourful-land For the signature case, how should this work? Will it be necessary to provide scaling and translation of the stamp? Or would it be up to the person creating the stamp file to make sure it lines up? One could imagine options like `--stamp-rotate`, `--stamp-translate`, and `--stamp-scale` to refine the positioning of a stamp. I'm not sure it's worth all that, but it would probably be easy enough to implement. One could even imagine a `--stamp-matrix` flag that would allow specification of the transformation matrix. For people who really understand PDF, this would allow extreme control with very little code, but I suspect it may be overkill. :-)

I actually have a little python script I wrote using [pikepdf](https://pypi.org/project/pikepdf/) that takes a transparent image of my signature and adds it to a page of a PDF file at a specified width and position. I use this to add my signature to paper forms all the time rather than printing, signing, and scanning.

**Comment by kilburn** [comment] 2019-01-11 15:57
My current use case is to stamp page numbers and headers to a file. That is, I've got a 30-page document, I generate another 30-page document using LaTeX that contains the page numbers and headers to my liking, and then I stamp those on the original document.

Cycling through the "stamp" pdf's pages seems reasonable to me (that's what you proposed if I understood correctly). Examples:

* `qpdf A.pdf AB.pdf --stamp=B.pdf` where `A` has 10 pages and `B` has 2 would stamp `B1` to odd `A` pages and `B2` to even `A` pages.

* `qpdf A.pdf AB.pdf --stamp=B.pdf` where `A` has 10 pages and `B` has 10 pages would stamp `B1` to `A1`, `B2` to `A2`, ..., and  `B10` to `A10`.

* `qpdf A.pdf AB.pdf --stamp=B.pdf` where `A` has 1 page and `B` has 10 pages would stamp `B1` to `A1` (and stop here because `A` has no more pages)

As you said, more complex situations can be resolved by splitting, duplicating and/or rejoining pages before the stamp operation. What is important to make clear (and ensure it works this way) is that stamping is performed "onto", meaning that `B`'s page in the examples above are pasted **above** `A`'s pages (and thus a solid object in `B` will occlude that portion of `A`).

**Comment by jberkenbilt** [comment] 2019-01-11 16:00
@kilburn Your description matches what I'm thinking in all aspects. I'm *hoping* I can get this in for 8.4.0, which I'm hoping to get released before the Ubuntu 19.04 feature freeze at the end of the month, but usual disclaimers apply. My day job and real life often get stamped on top of my qpdf work in such a way that solid objects in my life occlude portions of my qpdf work. :-)

**Comment by KurtPfeifle** [comment] 2019-01-11 16:50
Would it be equally easy to add a `--background=bg.pdf` option?

It would work similar to the `--stamp=stmp.pdf` option, only that this `stmp.pdf` would for the background of the page (and hence solid objects of `A` would occlude the respective portion of `bg.pdf`).

`pdftk` has the `stamp` as well as the `background` parameter.

----

BTW, `pdftk` also has `multistamp` and `multibackground` params. The difference is:

* `stamp`/`background` uses only the first page of the respective PDF to use it as a stamp and background for each processed PDF page.
* `multistamp`/`multibackground` uses all pages of the respective PDF and applies them as stamp/background to each page of the processed PDF; if there are more pages in the original PDF than in the stamp/background PDF, the remaining original pages get stamped/backgrounded with the *last* page of the stamp/background PDF.

I've been using this feature a lot in the past with `pdftk`.

*(From my POV there is no need to make the 'background' params the same priority as the 'stamp' ones, though. It would be really nice to get the stamp in for 8.4.0.)*

**Comment by michael-o** [comment] 2019-01-11 16:57
I think this should start simple. `B.pdf` is a single page and it applies to all pages to `A.pdf`.

My usecase is a LaTeX generated document which contains a specific layout and shall have a document id branded on. In most cases on all pages, but it may also include a cover page which does not have that specific layout, so page ranges would be nice for the second step.

**Comment by jberkenbilt** [comment] 2019-01-11 17:31
I wonder how pdftk does it. My guess is that the only difference between stamp and background would be whether the new drawing commands were inserted at the beginning or at the end of the contents. I have personally never used pdftk, but I have a lot of feature requests for people who are trying to replicate what they do with pdftk using qpdf. I try to avoid looking at other implementations when possible...probably this habit is embedded in my brain to prevent me from accidentally violating a license. I think the behavior outlined above would make it possible for qpdf to emulate pdftk's behavior, and I can see about the `--background` option.

**Comment by kilburn** [comment] 2019-01-11 18:41
After the comments here I think a possible (long-term goal?) interface could be:

```
--overlay <file> [source-page-range=1-z] [destination-page-range=1-z] [repeat=1-z] --
--underlay <file> [source-page-range=1-z] [destination-page-range=1-z] [repeat=1-z] --
```

where `overlay` stamps "on top" whereas `underlay` "backgrounds" the specified file below the pdf being processed. Then the extra options:

* `source-page-range` defines the range of pages from the original file that will receive the overlay/underlay
* `stamp-page-range` defines the range of pages from the stamp file `<file>` to use for stamping.
* `repeat-page-range` defines the range of pages from `<file>` that will be repeated if the number of destination pages is larger than the number of source pages.

Both page-range selectors here are defined like in the `pages` command (this should provide lower learning curve for users, and possibly even a shared implementation avoiding bugs).

Let's say we have 2 files:

* `A` has 5 pages `A1`, `A2`, `A3`, `A4`, `A5`
* `B` has 2 pages `B1`, `B2`

| Command                                      | Result                                 |
|----------------------------------------------|----------------------------------------|
| `qpdf A1.pdf --overlay B.pdf 1-z 1-z 1-z`    | A1+B1, A2+B2, A3+B1, A4+B2, A5+B1      |
| `qpdf A1.pdf --overlay B.pdf`                | same as above (uses defaults)          |
| `qpdf A1.pdf --overlay B.pdf 2-z 1-z 1-z`    | A1, A2+B2, A3+B2, A4+B2, A5+B2         |
| `qpdf A1.pdf --overlay B.pdf 2-z`            | same as above (uses defaults)          |
| `qpdf A1.pdf --overlay B.pdf 1-z 1 1-z`      | A1+B1, A2+B1, A3+B2, A4+B1, A5+B2      |
| `qpdf A1.pdf --overlay B.pdf 1-3 1 1`        | A1+B1, A2+B1, A3+B1, A4, A5            |
| `qpdf A1.pdf --overlay B.pdf 1-z 1-z r1`     | A1+B1, A2+B2, A3+B2, A4+B2, A5+B2      |
| `qpdf A1.pdf --underlay B.pdf 1-z 1-z 1-z`   | B1+A1, B2+A2, B2+A3, B2+A4, B2+A5      |

Notes:

* The resulting document always has the same number of pages the input file
* Overlay vs Underlay just changes whether the new content goes below the content of the source file (underlay) or above (overlay)

It seems to me that this should be "relatively easy" to implement, given that you have some sort of "Iterator(document, page-ranges)" object (I'm assuming it throws on construction if the range doesn't contain any valid page for the given file). The transformation could then follow some pseudo-code like:

```
function stamp(sourceDoc, mode, stampDoc, sourcePageRange, stampPageRange, repeatPageRange) {
    sourceIterator = Iterator(sourceDoc, sourcePageRange);
    stampIterator = Iterator(stampDoc, stampPageRange);

    while (sourcePage = sourceIterator.next()) {

        if (stampIterator.finished()) { // No more pages in stampIterator
            stampIterator = new Iterator(stampDoc, repeatPageRange);
        }

        stampPage = stampIterator.next()
        stampContent = stampDoc.getPage(stampPage)

        if (mode == MODE_OVERLAY) {
            sourceDoc.getPage(sourcePage).append(stampContent);
        } else {
            sourceDoc.getPage(sourcePage).prepend(stampContent);
        }
    }
}
```

**Comment by michael-o** [comment] 2019-01-11 19:02
@kilburn there are some errors:

* `stamp-page-range`/`destination-page-range`
* options can be shorter: `...-pages`

**Comment by jberkenbilt** [comment] 2019-01-11 19:11
@kilburn Thanks for thinking this through. I like your proposal. I'll probably do something a little different for command-line flags, but I think you have correctly generalized the problem. In case anyone hasn't noticed, qpdf 8.3.0 has shell completion for zsh and bash, and so I'm trying to make completion-friendly options. Anyway your theory that this would be relatively easy to implement is correct. When I am ready to actually start working on this, I'll digest it fully and propose a CLI syntax.

Thanks everyone for the collaboration. It's really helpful.

**Comment by michael-o** [comment] 2019-01-11 19:14
@jberkenbilt I'd be happy to test this when you have a decent branch...

**Comment by kilburn** [comment] 2019-01-11 19:30
I have fixed a few things in the above comment and changed the `repeat-pages` default value to be whatever the `stamp-pages` range is (I think this would be less surprising for users).

I have no attachment to the proposed option names at all. I'm not a native english speaker, so my names are oftentimes suboptimal to say the least. I just wanted to draft something that should be understandable by users and would cover all the use-cases presented in this thread. I call this "mission accomplished" given your response :)

@jberkenbilt Thank YOU for this excellent piece of software!

**Comment by colourful-land** [comment] 2019-01-12 00:21
> @colourful-land For the signature case, how should this work? Will it be necessary to provide scaling and translation of the stamp? Or would it be up to the person creating the stamp file to make sure it lines up?

I'll start by explaining how I did it without qpdf:

1. The user has a scanned signature:

    $ ls signature.jpg

2. the user transforms that into a pdf file with imagmagick:

    $ convert signature.jpg signature.pdf

3. add the margin:

    $ pdfcrop --margin '340 1700 720 90' signature.pdf throw-away.pdf

4. Lay it over an existing PDF:

    $ pdftk unsigned_contract.pdf stamp throw-away.pdf output signed_contract.pdf

5. Delete the intermediary file:

    $ rm throw-away.pdf

Notice that I left out the scaling for simplicity.

Now, since we have an opportunity to invent, what's the best way to do it? For a user, to specify the top and left measurements where the signature/stamp is a bit of trouble, but the most troublesome part comes from making sure the throw-away pdf has the same size as the underlying unsigned.pdf. A user needs to calculate this in order to supply the `--margin` parameter to `pdfcrop`. Let's imagine a new tool `pdfstamp` (or a new parameter of qpdf - I'm in the creative process so allow me, thanks!). I'm also going to shortcut the jpg->pdf conversion, assuming `pdfstamp` has it.

    $ pdfstamp --paper-size unsigned_contract.pdf --left 340 --top 1700 signature.jpg throw-away.pdf
    $ pdftk unsigned_contract.pdf stamp throw-away.pdf signed_contract
    $ rm throw-away.pdf

This is certainly better than the current situation we have. Now, let's see if we can get rid of the throw-away. Assuming `qpdf` is more powerful than pdftk, allowing standard input, we will have:

    $ pdfstamp --paper-size unsigned_contract.pdf --left 340 --top 1700 signature.jpg - \
    | qpdf unsigned_contract.pdf signed_contract.pdf --stamp=-

Traditionally, qpdf doesn't directly provide cropping, scaling, bleeding, margin adding kind of things (beyond `--qdf`), so that's how far we can progress for the command line users. The only ask for qpdf is to accept standard input as the source of the stamp. If `qpdf` intends to provide those in the future, this might work:

    $ qpdf signature.jpg --paper-size unsigned_contract.pdf --left 340 --top 1700 - \
    | qpdf unsigned_contract.pdf signed_contract.pdf --stamp=-

This design is slightly inefficient because if the throw-away pdf file is big (1GB?) a lot of data would pass through the pipe unnecessarily. But it significantly reduced the types of parameters. For example, you would not need to provide a `--scale` and a `--stamp-scale`, a single `--scale` would do. So it might represent a stable point in the design space.

> I actually have a little python script I wrote using [pikepdf](https://pypi.org/project/pikepdf/) that takes a transparent image of my signature and adds it to a page of a PDF file at a specified width and position. I use this to add my signature to paper forms all the time rather than printing, signing, and scanning.

Will take a look, might be useful for myself! Thanks!

**Comment by jberkenbilt** [comment] 2019-01-26 23:01
I'm thinking of `--overlay file.pdf --to=pages --from=pages --repeat=pages --` and the same for underlay. The `pages` options are page ranges. `--to` applies to the main input while `--from` and `--repeat` apply to the overlay/underlay file. Using named rather than positional arguments is more completion-friendly and easier to read than positional arguments but offers the same functionality as suggested by @kilburn.

I have finished implementation of the library methods required to make this work, so it's just a question of coding up the CLI stuff...probably just an hour's work at this point. Maybe I can even finish today.

Regarding @colourful-land's great suggestions, the functionality you're looking for could be implemented using the library as I've implemented it. There are two main new methods: QPDFPageObjectHelper::getFormXObjectForPage and QPDFPageObjectHelper::placeFormXObject. The former returns a form XObject for a page, and the latter generates content to place that form XObject within a region of a page. There is an example program in the examples directory that pulls it all together including using QPDFObjectHandle::copyForeignObject to grab a page from one file and overlay it on a page in another file. Note that PDF files do not lend themselves to pipes because you have to be able to see around in the file. QPDF does not provide any way to read a PDF file over a pipe. I think you could easily achieve functionality like what you're suggesting using a combination of ImageMagick and qpdf and generating temporary files, coding it up in C++ with the library, or hopefully using a future version of [pikepdf](https://pikepdf.readthedocs.io/en/latest/pikepdf.html) once he updates it to handle the new APIs in 8.4.0. It's not likely that I will add stuff this fancy to the CLI, but the functionality to do it will exist in the library with the coming release.

If anyone wants to test, you'll know when this is in master because it will automatically close this ticket. We can continue discussing if needed. I hope to get 8.4.0 out in the next week or two at the most. This is the last major thing for 8.4.0. There is one recent bug that I'd like to see if I can fix as well, but that's about it.

**Comment by jberkenbilt** [comment] 2019-01-27 03:51
Changes are heading into CI. I still have to update `--help` and the manual to describe the new features, but I should get this into master tomorrow or Monday.

**Comment by jberkenbilt** [comment] 2019-01-27 14:34
@KurtPfeifle I think the overlay and underlay options for 8.4.0 will handle your use case as well. I expect to push changes to master this morning.

**Closed** 2019-01-27 15:12 UTC
Labels: next

**Comment by michael-o** [comment] 2019-01-27 17:41
@jberkenbilt. That's awesome,. thank you. Looking forward to see this soon in the Free BSD Ports Collection.

**Comment by robsco-git** [comment] 2019-04-02 06:44
> @colourful-land I actually have a little python script I wrote using [pikepdf](https://pypi.org/project/pikepdf/) that takes a transparent image of my signature and adds it to a page of a PDF file at a specified width and position. I use this to add my signature to paper forms all the time rather than printing, signing, and scanning.

It would be great to see some example code of how this is achieved :smile:

**Comment by AlisterH** [comment] 2019-07-31 12:10
> > @colourful-land I actually have a little python script I wrote using [pikepdf](https://pypi.org/project/pikepdf/) that takes a transparent image of my signature and adds it to a page of a PDF file at a specified width and position. I use this to add my signature to paper forms all the time rather than printing, signing, and scanning.
> 
> It would be great to see some example code of how this is achieved 😄

Yes, is there any chance of seeing this?  I think a lot of people would find it useful.
Thanks.

**Comment by AlisterH** [comment] 2019-08-01 23:38
> I think a lot of people would find it useful.

Although it would be even better if the overlay/underlay option was enhanced to allow specifying position.  This feature is great, but the page that is used as the overlay/underlay is simply placed in the centre of the page, and if necessary scaled down to fit.   I imagine a very common use case is wanting to place a stamp in a corner of the pdf.  If all pages are the same size and orientation this is easily accomplished by creating a full page stamp.  If the pages are all the same shape and orientation I guess you can just create the stamp at the largest page size, and it will always be placed in the same corner (although it may not be desirable that it is scaled down on smaller pages).
But if some pages are portrait and others are landscape a portrait stamp will come out wrong on a landscape page, and vice versa.  See screenshot illustrating the results of attempting to apply the same stamps to both portrait and landscape pages.
![image](https://user-images.githubusercontent.com/714600/62334010-08078b00-b51a-11e9-880c-409850340c89.png)

**Comment by jberkenbilt** [comment] 2019-08-02 01:31
Okay, I'll attach some sample code and a sample signature. First of all, the sig-transparent.pdf file was created completely from scratch in a text editor. I am not saying this is the way normal people do things, but I am very comfortable editing PDF and image files as binary data in editors. It's from years of doing this stuff, I guess. I'm sure there are probably easier ways to do this.

To get the image data for this example, I started up gimp and drew the signature, used the color selector to select the background color, and then used Layer -> Transparency -> Color to Alpha to make it transparent, following some instructions I found by googling "gimp color to alpha". I exported as sig.png. Then I ran

```
convert -alpha extract sig.png smask.pgm
convert sig.png -alpha deactivate gray.pgm
```

In sig-transparent.pdf, you can find the gray data in object 8 and the smask in object 10. The width and the height come from the pgm file header, and the data is the raw data. I just copied this from the file in emacs in binary mode. If you're ambitious, you could use this file as a starting point for your own signature, or surely there's a way to do it using a fancier tool or maybe gimp directly. I haven't investigated because I like to know exactly how things work. After I copied the data and width and height in, I used fix-qdf to correct the offsets and xref and used atril to make sure the file works.

There are magic comments in the file used by the add-sig script. On line 51 of the add-sig script, I hard-coded the ratio of the image. This could easily have been extracted from the image data. Doing this is left as an exercise for the reader. :-) (But you can just read /Width and /Height from the image stream dictionary.)

For the rest, read the code.

This is not "production-ready." It is not general. It is a quick hack I threw together for my own private use (and to feel out pikepdf), which I have adapted by request for this ticket by replacing my real signature with some hand-written text I drew with my mouse in gimp. To get my real signature, I actually signed a piece of paper with a thick, black pen, scanned it, and started from there to get the transparent png.

Also, this could have been done as a form XObject, but I wrote this code before I realized you could create form XObjects in this way. If I were doing it now, I would create the signature as a form XObject, but it's not that different. The content stream code for drawing the image is about the same.

Here's the code for add-sig. I'll attach the signature file. I hope this is useful.

```python
#!/usr/bin/env python3
import os
import sys
import argparse
import pikepdf

whoami = os.path.basename(sys.argv[0])

def warn(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def parse_args(args=sys.argv[1:], prog=whoami):
    parser = argparse.ArgumentParser(
        prog=prog,
        description='Add transparent signature from sig to a PDF file',
    )
    parser.add_argument('--sig-file',
                        help='optional path to sig-transparent.pdf',
                        required=True)
    parser.add_argument('--src',
                        help='original PDF file',
                        required=True)
    parser.add_argument('--dest',
                        help='final PDF file',
                        required=True)
    parser.add_argument('--page',
                        help='page to insert signature into, numbered from 1',
                        type=int,
                        required=True)
    parser.add_argument('--x',
                        help='x coordinate of sig in points',
                        type=int,
                        required=True)
    parser.add_argument('--y',
                        help='y coordinate of sig in points',
                        type=int,
                        required=True)
    parser.add_argument('--width',
                        help='width of sig in points',
                        type=int,
                        required=True)
    return parser.parse_args(args)

options = parse_args()

# This code is crafted to work specifically with sig-transparent.pdf.
# It knows where the image is in the original file and also its aspect
# ratio.

sig_prefix = 'sig'
ratio = 4.615

sig_file = options.sig_file
sig = pikepdf.Pdf.open(sig_file)
orig_image = sig.pages[0]['/Resources']['/XObject'][f'/{sig_prefix}']

pdf = pikepdf.Pdf.open(options.src)
page = pdf.pages[options.page - 1]
if '/Group' not in page:
    page['/Group'] = pikepdf.Dictionary()
for d in (('/CS', pikepdf.Name('/DeviceRGB')),
          ('/I', True),
          ('/S', pikepdf.Name('/Transparency')),
          ('/Type', pikepdf.Name('/Group'))):
    page['/Group'][d[0]] = d[1]

height = options.width / ratio
sig_content = f'''q
{options.width} 0 0 {height} {options.x} {options.y} cm
/{sig_prefix} Do
Q'''.encode()
page.page_contents_add(pikepdf.Stream(pdf, sig_content), prepend=True)
image = pdf.copy_foreign(orig_image)
if '/Resources' not in page:
    page['/Resources'] = pikepdf.Dictionary(XObject=pikepdf.Dictionary())
elif '/XObject' not in page['/Resources']:
    page['/Resources']['/XObject'] = pikepdf.Dictionary()
page['/Resources']['/XObject'][f'/{sig_prefix}'] = image
pdf.save(options.dest)
```

**Comment by jberkenbilt** [comment] 2019-08-02 01:32
[sig-transparent.pdf](https://github.com/qpdf/qpdf/files/3459262/sig-transparent.pdf)

**Comment by jberkenbilt** [comment] 2019-08-02 01:34
I think cleaning this up and making it a tad more general and providing step-by-step instructions would be a great blog post. I have added it to my blog backlog. Maybe I'll actually write it sometime. :-)

**Comment by AlisterH** [comment] 2019-08-05 07:05
Thanks, that looks very useful.
The script gives me a syntax error I can't figure out how to fix at the moment, but I'm not very good with Python.  Am I the only one, or is there a mistake in it?

**Comment by jberkenbilt** [comment] 2019-08-05 17:06
@AlisterH Make sure you're using python3, not python2. In most Linux distributions, `python` is python2. EIther make it executable and execute it directly or explicitly run `python3 whatever.py`.

**Comment by jberkenbilt** [comment] 2019-08-05 17:08
To avoid possibility of cut and paste problems, here's the code as an attachment. github makes me put an extension on it like txt, but you can rename it to add-sig.py or even just add-sig.

[add-sig.py.txt](https://github.com/qpdf/qpdf/files/3468626/add-sig.py.txt)

**Comment by AlisterH** [comment] 2019-08-06 07:26
Ah, I see - those funny f-strings are a new feature in Python 3.6, and I was trying to run it in Python 3.5.

**Comment by e-gaulue** [comment] 2020-01-22 20:44
Sorry to come back on this issue, but I still don't manage to use it as explained.

I tried to overlay in order to remove fixed header and footer and replace them by a white background (our printer paper already have those). So I tried to create a pdf file with a top white band, transparency and a bottom white band. I've got it in PNG, but I never managed to convert it to pdf. I tried through imagemagik, gimp, inkscape (only open-source solutions), but I never managed or did manage but couldn't see it.

So I wonder:
- How do you do this (png to pdf keeping transparency) ?
- does qpdf handle this transparency as I've seen another issue where it's not so clear?
- would you recommend another tool handle this (if possible opensource and available on Windows)?

Best regards, Edouard

**Comment by mschilli87** [comment] 2020-01-23 08:30
@e-gaulue: This looks less like a qpd-specifc problem to me. So maybe you don't need the single maintainer or one of the less than 50 watchers of this repository to help you. I'd recommend asking on stackexchange or another platform with a broader audience. Don't forget to mention and link the cross-post, though. This way you might get a helpful reply much faster. An alternative tool you could try would be pdftk but my best guess is the issue is with your stamp file, not with qpdf itself.
If you are sure it's a qpdf issue, consider providing example pages along with the exact command you use to try to stamp one on the other.

**Comment by e-gaulue** [comment] 2020-01-23 10:21
Just in case some others get here,

I finally manage. But building PDF transparency is far to be so easy using classical tools.

Rereading this thread, I tried again with gimp. I drew my boxes in white and my transparency in black. Then I've been to Layer -> Transparency -> Color to Alpha and change my black to transparency.

Later I exported it to PDF. Be careful, don't tick the "save images as vectorial when possible", in this case this won't work.

I also created a full transparency A4 PDF from Gimp and tried to modify it from Mac Preview, it also fails and complains with bad object quantity.

Another working way: work with PNG and deal with transparency in the alpha canal. Then the imagemagik `convert` command manage to convert your PNG with transparency to PDF with transparency.

So, as of today, I would say "dealing with transparency in PDF is not so easy": above are two ways... On the contrary, "to break transparency is easy": open a PDF with transparency in a tool that support it badly and then save may simply remove your transparency.

Regards,

**Comment by mara004** [comment] 2021-05-01 20:21
Thanks very much for the Python example code, that's really useful for me!
However, I am encountering the problem that my signature is partly hidden behind other objects of the Pdf I want to stamp onto. Is there any way to explicitly set the signature XObject to the top-most layer?

**Comment by jberkenbilt** [comment] 2021-05-01 22:22
@mara004 Objects are stacked from bottom to top in order of presentation, so ensuring that it is on top is just a matter of making sure it is drawn last. A common pattern is to prepend `q\n` (`\n` = newline) before the first content stream and append `Q\n` after the last content stream followed by the code to draw your transparent image or form XObject. Here's a new example that I wrote later (and had forgotten about this issue). This one actually reads the PNG, splits it into layers, and ensures that it's on top. It's also a little more generic. I use it myself now instead of the earlier example. The code is inline and also attached as a text file.

```python
#!/usr/bin/env python3
import argparse
import os
import pikepdf
import PIL.Image as Image
import sys

whoami = os.path.basename(sys.argv[0])


def parse_args(args=sys.argv[1:], prog=whoami):
    parser = argparse.ArgumentParser(
        prog=prog,
        description='Add transparent RGBA PNG a PDF file',
    )
    parser.add_argument('--png',
                        help='path to RGBA PNG file',
                        required=True)
    parser.add_argument('--src',
                        help='original PDF file',
                        required=True)
    parser.add_argument('--dest',
                        help='final PDF file',
                        required=True)
    parser.add_argument('--page',
                        help='page to insert image into, numbered from 1',
                        type=int,
                        required=True)
    parser.add_argument('--x',
                        help='x coordinate of image in points',
                        type=int,
                        required=True)
    parser.add_argument('--y',
                        help='y coordinate of image in points',
                        type=int,
                        required=True)
    parser.add_argument('--width',
                        help='width of image in points',
                        type=int,
                        required=True)
    return parser.parse_args(args)


options = parse_args()

rgba = Image.open(options.png)
(width, height) = rgba.size
rgb = Image.new("RGB", rgba.size, (255, 255, 255))
alpha = rgba.getchannel('A')
rgb.paste(rgba, mask=alpha)

pdf = pikepdf.Pdf.open(options.src)

alpha_stream = pikepdf.Stream(pdf, alpha.tobytes())
alpha_stream['/Type'] = pikepdf.Name('/XObject')
alpha_stream['/Subtype'] = pikepdf.Name('/Image')
alpha_stream['/ColorSpace'] = pikepdf.Name('/DeviceGray')
alpha_stream['/BitsPerComponent'] = 8
alpha_stream['/Interpolate'] = True
alpha_stream['/Width'] = width
alpha_stream['/Height'] = height

rgb_stream = pikepdf.Stream(pdf, rgb.tobytes())
rgb_stream['/Type'] = pikepdf.Name('/XObject')
rgb_stream['/Subtype'] = pikepdf.Name('/Image')
rgb_stream['/ColorSpace'] = pikepdf.Name('/DeviceRGB')
rgb_stream['/BitsPerComponent'] = 8
rgb_stream['/Interpolate'] = True
rgb_stream['/SMask'] = alpha_stream
rgb_stream['/Width'] = width
rgb_stream['/Height'] = height

fxo = pikepdf.Stream(pdf, b'q\n1 0 0 1 0 0 cm\n/Im Do\nQ\n')
fxo['/Type'] = pikepdf.Name('/XObject')
fxo['/Subtype'] = pikepdf.Name('/Form')
fxo['/Resources'] = {
    '/XObject': {
        '/Im': rgb_stream,
    },
}
fxo['/BBox'] = [0, 0, width, height]

scale = options.width / width
im_height = scale * height
prefix = '/FxPNG'

page = pdf.pages[options.page - 1]
if '/Resources' not in page:
    page['/Resources'] = pikepdf.Dictionary(XObject=pikepdf.Dictionary())
elif '/XObject' not in page['/Resources']:
    page['/Resources']['/XObject'] = pikepdf.Dictionary()
xobject = page['/Resources']['/XObject']

n = 1
prefix = None
while prefix is None:
    candidate = f'/FX{n}'
    if candidate not in xobject:
        prefix = candidate
    else:
        n += 1

png_content = f'''Q
q
{options.width} 0 0 {im_height} {options.x} {options.y} cm
{prefix} Do
Q\n'''.encode()
page.page_contents_add(pikepdf.Stream(pdf, 'q\n'.encode()), prepend=True)
page.page_contents_add(pikepdf.Stream(pdf, png_content), prepend=False)
if '/Resources' not in page:
    page['/Resources'] = pikepdf.Dictionary(XObject=pikepdf.Dictionary())
elif '/XObject' not in page['/Resources']:
    page['/Resources']['/XObject'] = pikepdf.Dictionary()
page['/Resources']['/XObject'][prefix] = fxo
pdf.save(options.dest)
```

[pdf-add-png.py.txt](https://github.com/qpdf/qpdf/files/6410377/pdf-add-png.py.txt)

**Comment by jberkenbilt** [comment] 2021-05-01 22:23
This conversation should really be on a discussion rather than commenting on a closed issue. I tend to overlook comments on closed issues.

**Comment by mara004** [comment] 2021-05-02 11:44
Thanks for the explanation and the code!

**Comment by jberkenbilt** [comment] 2021-09-20 17:57
> Thanks so much for the explanation and the code!
> @jberkenbilt Is it okay to reuse your example in other projects? Under which license would you provide it?

By all means, and feel free to consider it in the public domain.

**Comment by jberkenbilt** [comment] 2021-09-20 18:03
For people who may come across this issue while looking for a way to overlay a signature, I'd like to echo the comment @mara004 made on https://github.com/pdfarranger/pdfarranger/issues/530:

> As a remark concerning signature overlays, I personally would recommend to be a bit careful with this: If you digitally share a PDF with signature overlay, it is possible to notice that the document has not really been signed in print, and it would also be quite easy to extract the signature...

**Comment by alexeymuranov** [comment] 2022-02-23 13:39
I have a related but slightly different use case: i would like to replace a page without affecting the table of contents of page numbering. I can simulate this with `--overlay`, but then the original page is kept hidden. Is there a way to just replace? If not, how about adding such a `--replace` option?

**Comment by michael-o** [comment] 2022-02-23 13:58
> I have a related but slightly different use case: i would like to replace a page without affecting bookmarks of page labels. I can simulate this with `--overlay`, but then the original page is kept hidden. Is there a way to just replace? If not, how about adding such a `--replace` option?

Create a new issue
