### ISSUE TITLE
qpdf removes some objects from a signed LiveCycle PDF

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#702] opened 2022-05-16 20:11 UTC
It's a fancy Adobe LiveCycle PDF with public key digital signature.
https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5708e.pdf

`qpdf --stream-data=preserve --compress-streams=n --object-streams=preserve --preserve-unreferenced-resources --preserve-unreferenced imm5708e.pdf out.pdf` will be ~100 KB smaller. The output file loads correctly in Acrobat (with an understandable complaint that the file does not match its digital signature anymore).

Originally reported here against pikepdf:
https://github.com/pikepdf/pikepdf/issues/332

The reporter said it "removed Javascript". I couldn't figure out which objects actually got dropped or if any Javascript specifically was broken. The output file has fewer objects per xref table.

**Comment by jbarlow83** [comment] 2022-05-16 20:12
Tested against qpdf 10.6.3 on linux and macos.

**Comment by jberkenbilt** [comment] 2022-05-16 20:39
Thanks, I'll give it a good look. I've always wanted to get my hands on a PDF with digital signature. I intend to find a way to support it to the extent that one can. I have to read up on that part of the spec. That may be a red herring though. I'll see what I can find.

**Comment by jberkenbilt** [comment] 2022-09-02 17:52
I'm finally starting to look at this. This file is modified by append, which explains why the output of qpdf is smaller and some things are missing, but those things that are missing are not really semantically still there... Unfortunately, qpdf doesn't really provide a very good way to examine files of this type because it deals with multiple xref tables very early on in parsing and there is, at no time, any representation in qpdf of the fact that objects have been replaced.

It would be easier to examine files like this if there were a way to decode raw xref streams. I typically do it by hand. Maybe I'll add something to do it. It probably wouldn't take very long. This file has actually been appended twice. It has three `%%EOF` markers, and the last and second to last xref streams have `/Prev` pointers. To look at it in its various versions, I just copied the file to 1.pdf, then copied 2.pdf and removed everything after the second `%%EOF`, then copied 2.pdf to 3.pdf and removed everything after the first `%%EOF`.

From the first version (in 3.pdf) to the second version (in 2.pdf), there were some changes to forms.

From the version in 2.pdf to the final version in 1.pdf, there were more form changes and lots of other annotation changes.

I don't see any evidence of javascript being removed. There is javascript code that's check XFA. XFA forms are deprecated in PDF 2.0, and I haven't paid much attention to them, so I don't really know how they work.

I don't think qpdf is doing anything bad with this file. I think the digital signature is a red herring.

When I open the original file in Acrobat Pro and also the file as modified by qpdf, I don't see at a glance any different in functionality other than that, naturally, the digital signature verification fails on the version written by qpdf.

I'm inclined to close this without more information from the original user, but I don't actually see anything bad or unexpected happining. Sorry for taking so long to study this.

**Comment by janvarsa** [comment] 2022-09-12 17:09
Thanks for looking at this! The "Validate" button on this form actually performs 2 functions (the second of which you would only see after completing the form): 

- Firstly it highlights any missing required information (red boxes).
- Secondly, if all required fields are complete, validating will append a 6th page to the document which contains a series of barcodes that are automatically generated and unique to this document.

It's really the loss of the second function that hinders my use case. Ideally I would like to complete the form programmatically, save it, and still be able to generate the page of barcodes, but this feature seems to get lost after saving with qpdf or pikepdf. Based on the lower file size after saving, I was assuming that the JavaScript used to generate the barcodes was being removed from the file, but I could be wrong about that.

Interestingly, the Mozilla pdf project doesn't seem to have this issue (you can modify fields from this file, download the modified pdf, and still open the file and perform validation): https://github.com/mozilla/pdf.js

**Comment by jberkenbilt** [comment] 2022-09-12 17:51
My first guess was that perhaps the Adobe products are refusing to do certain operations if the signature validation fails. The way I would attempt to reproduce this would be to make a gratuitous change to the file, such as modifying whitespace somewhere or changing a value without changing the size of the file. However I tried that by changing a bounding box field from 0.0 to 0 followed by two spaces, and although the resulting file failed signature validation, validate's second function still worked. So I'm not really sure what's going on. There may be something about the validation that depends on some aspect of the file's structure as an appended file, but that's a guess. It would be interesting to see what the filled in file from mozilla looks like. Sometimes form fillers fill in forms by append such that the original file is intact and signature validation may be able to pass in that case. I'm not sure.

**Comment by jberkenbilt** [comment] 2023-12-29 17:21
Closing for inactivity.

**Closed by jberkenbilt** 2023-12-29 17:21 UTC
