### ISSUE TITLE
How to make PDF content readable by qpdf?

### ISSUE THREAD

**Issue by pengyu** [qpdf/qpdf#410] opened 2020-03-17 04:04 UTC
I use the command `lualatex main.tex` to generate `main.pdf`.

```
% main.text
\documentclass{standalone}
\begin{document}
iffy fig flat office baffle
\end{document}
```

I'd like to inspect the content of `main.pdf`. Therefore, I generated main-qpdf.pdf. But it seems that there are is binary content in it. Is there a way to completely convert the binary content into a human-readable form? Thanks.

```
qpdf --qdf --object-streams=disable main.pdf main-qpdf.pdf
```

**Comment by jberkenbilt** [comment] 2020-03-31 02:30
Sorry for the delay in response. Unfortunately, there's not much you can do about this in terms of looking at the raw PDF, though there are plenty of tools out there for text extraction. The issue is the way font subsetting is implemented in PDF. Typically a font contains a character map that maps a binary character value to a position in the font map. A common pattern is for the PDF file's map to assign the first character the value 0, the next character to appear the value 1, and so forth. If you know what you're looking at, you can decode the text character by character, but the actual text won't literally appear as such. But even if it did, sophisticated typesetting systems like TeX and its derivatives will generally not relay on PDF's text rendering to properly position characters. They will instead place characters character by character using a PDF operator that allows fine-tuning of the placement of each letter. So even if you are using a built-in font or font without subsetting, the words won't usually appear.

I'm going to close this issue, but feel free to reopen if you have a specific problem or to ask further questions if necessary.

**Closed by jberkenbilt** 2020-03-31 02:30 UTC
