### ISSUE TITLE
Looping indefinitely with --empty

### ISSUE THREAD

**Issue by fblondiau** [qpdf/qpdf#217] opened 2018-07-04 20:11 UTC
With qpdf version 8.1.0, entering a command like
    qpdf --empty --pages infile.pdf 1-5 -- outfile.pdf
seems to loop indefinitely (on macOS, installed with brew)... while it was working as expected, with qpdf version 8.0.2.
Replacing --empty with a file name
    qpdf infile.pdf --pages infile.pdf 1-5 -- outfile.pdf
seems to be a valid workaround.

**Comment by jberkenbilt** [comment] 2018-07-05 16:10
Thanks for the report. This is a bit strange. I am not able to reproduce this on my mac with either qpdf built from source or installed with brew. I wonder if it could have something to do with the specific file. Is it possible for you to provide a file that you can reproduce this with? If you don't want to post it, you can email it to me at ejb@ql.org. If you don't want me to keep the file, let me know. I have a private, non-version-controlled place where I keep files people send me for temporary use that I delete when I'm finished with them.

**Comment by jberkenbilt** [comment] 2018-07-10 15:15
Thank you for sending me the sample file out of band. I have recieved it and have successfully observed a problem, so I will definitely be able to look at solving the problem as soon as I can get to it. This file seems to expose a bug in the newly added code that attempts to prune unreferenced objects. You can revert to qpdf 8.0.2's behavior by passing `--preserve-unreferenced-resources` to qpdf. 

How long did you give this to finish? When I run this, it completes in about 13 seconds. With `--preserve-unreferenced-resources`, it finishes in under 2 seconds, and with qpdf 8.0.2, it finishes in less than 0.2 seconds. There is obviously a significant problem here, so your sample file is a huge help to me.

**Comment by jberkenbilt** [comment] 2018-07-10 15:16
By the way, I see this behavior on my Linux box, so it's likely not a mac-specific issue. I'll test on mac too though.

**Comment by fblondiau** [comment] 2018-07-10 15:25
Looping indefinitely is wrong… as, indeed, after about 40 seconds, it completes successfully !  It was so fast with the previous version, that I didn't wait enough time before concluding.

**Comment by jberkenbilt** [comment] 2018-07-10 15:55
Great, then I am able to fully reproduce what you're seeing. I will track down the performance problem. I'm pretty sure I know where it is....there was a logic in error in shallow copy that was causing objects to be shared more than one level deep. This matters for pruning unreferenced resources, but it didn't matter for any use cases of shallow copy within the library prior to 8.1. There is probably some inefficiency in that code that I can find and fix. But anyway, I'll track it down and fix it for 8.1.1.

**Comment by jberkenbilt** [comment] 2018-08-04 23:57
The bulk of the problem here was actually in the code that is allowing files to be opened and closed with each operation, removing the limit in the number of files that can be merged. A little optimization around keeping files open during intensive operaitons on those files drastically increases the performance. There is still a cost to the new logic of removing duplicated operations, but the cost is much lower than the cost of opening and close the file multiple times. This will be fixed in the next release, which will most likely be 8.2.0 rather than 8.1.1 because I had to add a new public method to the API to fix the bug.

**Closed** 2018-08-05 00:26 UTC
Labels: bug, next

**Comment by fblondiau** [comment] 2018-08-05 10:46
👍

**Comment by jberkenbilt** [comment] 2018-08-18 15:08
Version 8.2.0 includes a fix for this, but version 8.2.1 includes a better fix. I should have 8.2.1 out in a couple of hours.
