### ISSUE TITLE
error: attempt to make a stream into a direct object

### ISSUE THREAD

**Issue by dansto** [qpdf/qpdf#478] opened 2020-10-30 11:58 UTC
when i try to merge a pdf which was created by scanning a document
with Xerox WorkCentre 7845 or Xerox AltaLink C8035

i get the error below

example command: "qpdf  --verbose --empty --pages in.pdf -- out.pdf "

qpdf: selecting --keep-open-files=y
qpdf: processing in.pdf
qpdf: empty PDF: checking for shared resources
qpdf: no shared resources found
qpdf: in.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: removing unreferenced pages from primary input
qpdf: adding pages from in.pdf
attempt to make a stream into a direct object

any ideas?
i cant send the pdfs because of disclosure issues.

**Comment by jberkenbilt** [comment] 2020-10-30 14:13
Can you run `qpdf --json in.pdf` and send me the output of that? You can inspect the output before sending it, but it won't contain any of the content, though it will contain metadata and any text that may appear in bookmarks. For an even more conservative approach, you can run `qpdf --json --json-keys=objects --json-keys=pages in.pdf`. I should be able to tell what's going on from that. Please also confirm what version of qpdf you are using.

It's possible that `qpdf in.pdf --pages . -- out.pdf` might be more successful, but most likely you will get the same problem. This is probably the result of some way in which the PDF is incorrect with regard to the spec, but seeing an example may make it possible for me to enable qpdf to handle files structured in whatever way this one is structured.

**Comment by dansto** [comment] 2020-10-30 18:45
qpdf version 10.0.2 (compiled on centos7)


[json1.txt](https://github.com/qpdf/qpdf/files/5466965/json1.txt)
[json2.txt](https://github.com/qpdf/qpdf/files/5466966/json2.txt)

that worked actually:

qpdf in.pdf --verbose --pages . -- out.pdf
qpdf: selecting --keep-open-files=y
qpdf: in.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: removing unreferenced pages from primary input
qpdf: adding pages from in.pdf
qpdf: wrote file out.pdf


but how can i merge two or more files with that syntax?

**Comment by jberkenbilt** [comment] 2020-10-30 19:38
You can either start with `--empty` or you can start with one of the files. You can do `qpdf file1.pdf --pages . file2.pdf -- out.pdf` for example. Basically what qpdf does is take all the document-level structures and metadata from the first file, remove all the pages from that file that aren't selected, and copy the pages from the other files. Sometimes this different code path avoids weird problems. Eventually I hope qpdf will be more intelligent about document-level structures. There are a lot of issues open around things like bookmarks and forms working properly with `--pages`, but the code to fix this will be quite a bit more complicated. One day I will get to it. I'm glad you lucked into a workaround in this case. I will take a look a the json files next time I have some time to work on qpdf. Alas, I just released 10.0.2, and it will probably be a few weeks at least before I can devote any serious time.

**Comment by jberkenbilt** [comment] 2020-10-30 19:41
There's a very good chance that this broken in 10.0.2 and would have worked in 10.0.1. I think the problem is that the `/Filter` for `/JBIG2Globals` includes some streams. This is a bug, and it may require me to release 10.0.3. I think I can reproduce it with a fake file. I'll give a few more days for 10.0.2 to get some use and may end up doing an emergency 10.0.3 to fix this bug.

**Comment by jberkenbilt** [comment] 2020-10-30 19:41
Thanks for the json -- this is what enabled me to see what the problem probably is.

**Comment by dansto** [comment] 2020-10-30 20:09
ok I will try 10.0.1 tomorrow

the problem is we generally dont know the first file we want to merge. and the problematic one could be somewhere in the middle of all files.

thanks for your effort :)

**Comment by jberkenbilt** [comment] 2020-10-30 20:12
Indeed -- that's why I said you lucked into a workaround. If this is in fact a regression from 10.0.1, I will find time to do a release to fix it very soon. I'll be interested to know what you find with 10.0.1.

**Comment by jberkenbilt** [comment] 2020-10-31 11:55
I have been able to reproduce this with a fabricated test file and will be releasing 10.0.3 to fix it. It's a big enough problem to warrant a special release. Thanks for finding it so fast and drawing it to my attention.

**Comment by jberkenbilt** [comment] 2020-10-31 15:59
I have coded a fix for this and will release the fix in 10.0.3 sometime today.

**Comment by dansto** [comment] 2020-10-31 17:32
thats brilliant

i testet also qpdf version 10.0.1
that really worked.

 qpdf --verbose  --empty --pages in.pdf in2.pdf in3.pdf  -- out.pdf
qpdf: selecting --keep-open-files=y
qpdf: processing in.pdf
qpdf: processing in2.pdf
qpdf: processing in3.pdf
qpdf: empty PDF: checking for shared resources
qpdf: no shared resources found
qpdf: in.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: in2.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: in3.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: removing unreferenced pages from primary input
qpdf: adding pages from in.pdf
qpdf: adding pages from in2.pdf
qpdf: adding pages from in3.pdf
qpdf: wrote file out.pdf

**Comment by jberkenbilt** [comment] 2020-10-31 17:36
Great, that is a strong confirmation that this is what I think it is....anyway, I am preparing 10.0.3 now and should have it released within an hour or two.

**Closed** 2020-10-31 17:37 UTC
Labels: bug, next

**Comment by jberkenbilt** [comment] 2020-10-31 18:59
Okay, 10.0.3 is out. Congratulations on finding a bug that made me do a release. There have been very few of these. :-)

**Comment by dansto** [comment] 2020-10-31 21:19
thx it worked:

qpdf --verbose  --empty --pages in.pdf in2.pdf in3.pdf  -- out.pdf
qpdf: selecting --keep-open-files=y
qpdf: processing in.pdf
qpdf: processing in2.pdf
qpdf: processing in3.pdf
qpdf: empty PDF: checking for shared resources
qpdf: no shared resources found
qpdf: in.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: in2.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: in3.pdf: checking for shared resources
qpdf: no shared resources found
qpdf: removing unreferenced pages from primary input
qpdf: adding pages from in.pdf
qpdf: adding pages from in2.pdf
qpdf: adding pages from in3.pdf
qpdf: wrote file out.pdf

**Comment by jberkenbilt** [comment] 2020-10-31 21:40
Excellent, thanks for the follow-up!
