### ISSUE TITLE
Can QPDF extract pages from a given PDF into multiple individual PDF output files ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#110] opened 2017-03-09 17:57 UTC
Hi. QPDF contain very wonderful options to extract pages from a given PDF into single output PDF, like:

$ qpdf infile.pdf --pages infile.pdf 1-10 -- output.pdf

However, is it possible to extract these pages into individual PDF files, file per each page, & these multiple output PDF files named automatically by names drive from name of original PDF? For example: if original PDF name is test1.pdf & we extract pages 7 to 15 from this file then we will have following output files:

test_07.pdf
test_08.pdf
test_09.pdf
test_10.pdf
test_11.pdf
test_12.pdf
test_13.pdf

Best.
test_14.pdf
test_15.pdf

**Comment by jberkenbilt** [comment] 2017-07-30 12:58
Please see the pdf-split-pages example in the examples directory. It pretty much does this.

**Comment by jberkenbilt** [comment] 2017-07-31 00:33
This is the same as #30. It seems worth doing.

**Comment by jberkenbilt** [comment] 2017-08-05 13:58
Closing as fixed/duplicate of #30 which I am pushing a fix for momentarily.

**Closed by jberkenbilt** 2017-08-05 13:58 UTC
Labels: next
