### ISSUE TITLE
Feature request: Higher level abstractions for objects such as forms in a PDF.

### ISSUE THREAD

**Issue by sahilarora535** [qpdf/qpdf#178] opened 2018-02-01 20:51 UTC
It is hard to represent all types of objects in a PDF using the `QPDFObjectHandle` class. An example of this is forms in a PDF.

@smilingthax says:
> to handle Form fields, the current approach of QPDF, "everything is as QPDFObjectHandle" is probably not the best way. A better way could be to introduce a "QPDFFormFieldHandle" (containing a reference to the annotation and the page, and also to the node/field in the /AcroForms - tree), but there are certainly other options.

@jberkenbilt says:
> I'm certainly willing to think about higher level abstractions for specific kinds of things. I doubt we're going to end up with QPDFFormFieldHandle, but I agree that some kind of framework for higher level abstractions is appropriate.

The issue originated while trying to fill a PDF which contains forms using QPDF.
Issue and conversation: https://github.com/OpenPrinting/cups-filters/issues/8

CC: @tillkamppeter

**Comment by smilingthax** [comment] 2018-02-04 13:51
Clarification: A terminal field's `/Kids` array can point to multiple annotations for the same field (possibly on different pages). A merge of field dictionary and annotation dictionary (i.e. bullet point iii.) is not possible in this case. An annotation dictionary must not re-used on more than one page (and probably should not appear more than once in a given `/Annots` array).

**Comment by psmlbhor** [comment] 2018-02-08 08:14
Now that @sahilarora535 has mentioned it, I remember asking @jberkenbilt a similar question quite a long time ago where he mentioned he will be thinking about it in the future. 

Having a separate object handle for Form fields, I think, will greatly reduce the work that needs to be put in while handling those fields. For eg. we need to keep track of the child of every object that comes under `/Annot`. A new object handle can just manage it allowing the user to focus on the task that he wishes to perform rather than managing the intricacies of the form objects.

**Comment by jberkenbilt** [comment] 2018-02-19 03:52
@sahilarora535 You asked: "Jay, what do you think? Do you want to think this through for yourself first, or would should we provide some ideas on how a form API for QPDF could look like?"

Feel free to provide some ideas if you want, though just be aware that I am very particular and may or may not agree with them. :-) I'm polishing up qpdf 8, and then I'll have to take another break, but next time I get some time to put into qpdf, I'll probably pick this up. I will give it some thought after thoroughly reading and digesting everything here, and I will be interested in any input.

**Comment by sahilarora535** [comment] 2018-02-23 17:41
I am not sure if I'd be able to tell how the API should be like because I do not have any prior experiences with forms in PDF. However, I can surely highlight some code snippets which make use of Poppler APIs which are currently being used for form handling in [`cups-filters`](https://github.com/openprinting/cups-filters).

```c++
// For getting a form type of a page
Catalog::FormType form_type = catalog->getFormType();
if ( form_type == Catalog::NoForm ) {
    fprintf(stderr, "PDF template file doesn't have form. It's okay.\n");
    return 0;
}

// Getting all form widgets from a page
FormPageWidgets *widgets = page->getFormWidgets();

// Getting the number of widgets of a form
int num_widgets = widgets->getNumWidgets();

// Getting a particular form widget from all the form widgets, for instance first:
FormWidget *fm = widgets->getWidget(0);

// class for a form widget of type text
// form widgets are of different types, and this converts a generic form widget to a text type form widget
FormWidgetText *fm_text = static_cast<FormWidgetText*>(fm);

// function which tells if the widget is read only
fm_text->isReadOnly()

// get the field from the widget
FormField *ff = fm_text->getField();

// get the fully qualified field name from the form field
field_name = ff->getFullyQualifiedName();

// get the partial name for a field
field_name = ff->getPartialName();

// set the content of the form field
fm_text->setContent(content);
``` 

This is the major part of the Poppler API which has been used in [`cups-filters`](https://github.com/openprinting/cups-filters). Apart from this, the appearance streams for forms are also changed. The complete function which does all this can be found [here](https://github.com/OpenPrinting/cups-filters/blob/6db3b08d3b20332b1525b8dd1a47950381b8f637/filter/pdf.cxx#L665-L962), in case it may help. 

@smilingthax has greatly described what all needs to be changed when we are working with forms in [his comment above](https://github.com/qpdf/qpdf/issues/178#issuecomment-362441409).

**Comment by sahilarora535** [comment] 2018-02-23 19:47
@jberkenbilt 
> @sahilarora535 You asked: "Jay, what do you think? Do you want to think this through for yourself first, or would should we provide some ideas on how a form API for QPDF could look like?"
Feel free to provide some ideas if you want, though just be aware that I am very particular and may or may not agree with them. :-) I'm polishing up qpdf 8, and then I'll have to take another break, but next time I get some time to put into qpdf, I'll probably pick this up. I will give it some thought after thoroughly reading and digesting everything here, and I will be interested in any input.

This was asked by @smilingthax in https://github.com/qpdf/qpdf/issues/178#issuecomment-362441409 , hence I believe he would be able to provide with some valuable suggestions here.

**Comment by sahilarora535** [comment] 2018-04-03 21:08
@smilingthax writes:

1) We probably want a cache mapping an annotation's object Id/Gen (`QPDFObjGen` ?) to its field (`QPDFObjectHandle`). This can be done like the pages API w/ cache (incl. cache invalidation) in the QPDF class.
2) As the mapping from page to annotations is straightforward (just go to `/Annots`), we might not need a convenience method(?).
3) The most useful operation is going from a page to it's fields - or at least: from an annotation to its field. This requires the mapping from 1). An API could look like:
   ```c++
   std::vector<std::pair<QPDFObjectHandle, QPDFObjectHandle>>
   QPDF::getFieldsOnPage(QPDFObjectHandle pageObj);
   ```
and/or
   ```c++   
    QPDFObjectHandle QPDF::getFormFieldForAnnotation(QPDFObjGen / QPDFObjectHandle annotation)
   ```
4) Helper method: When given a form field (inside the `/AcroForm /Fields` tree), we want to obtain the associated annotations:
```c++
    std::vector<QPDFObjectHandle> QPDFObjectHandle::getAnnotationsForFormField(QPDFObjectHandle field)
```
- this basically deals with the special case that instead of a `/Kids` array with a single element, the annotation dictionary can be merged into the field dictionary. In this case we simply return a vector containing only field.
- as the 1:1-case is pretty common, we can try to create some convenience methods for that?

5) When performing the lookup in 4), there is no way to find the page the annotation is on. Either we don't support this operation (because the usual form operations one might want to do can be done without this information, or we have to build another cache into QPDF, which maps annotations (-> `QPDFObjGen`) to page objects(? - or: page numbers??). This cache can probably be integrated into a `/AcroForm /Fields` tree representation/cache (see below).

**(Minor correction)**
- When we have the annotation id / gen in 5) [from 4)], we can use the map from 1) to also store the page handle / number (not the fields tree):
    ```c++ 
    std::map<QPDFObjGen, std::pair<QPDFObjectHandle, QPDFObjectHandle>>
    ````    
with the first element of the pair being the field handle, and the second element being the page handle (alt: page number, ...).

6) Except for acrobat < 3.0, partial field names cannot contain a period (Implementation note 116). If we ignore that exception, we can represent a path to a field in the `/Fields` -tree by the concatenation of the partial field names / splitting of the full field name at the dots. OTOH, this seems to be a rather academic exercise, as the partial field name dictionary entry is entirely optional - i.e. not really helpful for most operations on fields(?).
  - AFAIR bannertopdf somehow uses the field names, so we could add convenience methods to `QPDFObjectHandle  (::getFullFormFieldName / ::getPartialFormFieldName )`.

7) We want to iterate over all fields in the field tree. As we can see in 6), something like a `map<string,QPDFObjectHandle>` (w/ the string being the full name / path) won't do. Still we will have to somehow make the intermediate nodes visible/accessible. I don't have a solution yet. We can try:
  - Visitor pattern: QPDF calls methods which represent the tree traversal on a user-provided visitor
  - `std::vector<QPDFObjectHandle> leafs` + method to look-up keys which also looks at the ancestors until found (-> inheritance) + maybe method on `QPDFObjectHandle` to obtain the ancestors (-> `std::vector<QPDFObjectHandle>`). The not-so-nice thing about this is: Inheritance could be dealt with in O(n), but here we have something like O(n/2*log n).
  - `std::vector<...some...new...objects...with...inheritance..."resolved"...and...page...information[cf. 5)]...> leafs`.
  - ...

8) it should be possible to add / remove fields to / from the field tree -- TBD.

9) it should be possible to add / remove annotations (possibly creating a new annotation on a given page(?)) to a field. For 1->2 Kids this can mean to un-merge the dictionaries [cf. 4)]. I'm not sure whether a form field with 0 annotations (/Kids) is meaningful (is it actually allowed in PDF?). This could be something like
  `QPDFObjectHandle QPDFObjectHandle::addAnnotation(QPDFObjectHandle dstPage)`
  - only possible when *this is a form field dictionary.
  - returns an empty / undictionary
  - Problems: We might want to add an intermediate node, not just leaf nodes. Do all /Kids have to be of the same type (leaf vs. inner node)?

=> We probably should not implement 8) + 9) for now; 7) is a bit more difficult to decide. I tend towards completely implementing the whole /NeedAppearances stuff outside of QPDF first (as Pranjal has started doing). The pdf spec even mentions things like auto-scaling the font-size to make text fit the box, etc. In the end, QPDF would need one (private) annotations-generating method per field/widget type.

- I could even imagine a separate "form addon"-library to QPDF, which contains nice (and specific) classes/methods for each form type - e.g. for a text field there is `setAlignment( ...left / center / right ...)`, etc... [which then calls QPDF's more general methods like QPDFObjectHandle::replaceKey(...)].

- And/or: QPDF could include some field-type specific methods, e.g. set text for text-widget (... encoding...), set radio button (while deselecting all others...).

=> Having methods like 1)...6)/7) would already help a lot. Having to use (e.g.) replaceKey("/V", ...new string...) on a field dictionary to change the field's text-value is not that big of a deal, IMHO.
We then set `/NeedAppearances true` (or: QPDF might be able to track that?) and let pdftopdf do its job (i.e. currently it calls poppler/gs to regenerate the appearances and flatten them).

**Comment by jberkenbilt** [comment] 2018-05-22 00:36
Regarding the API changes, I haven't had time to think about it deeply, nor have I had time to digest everything above, but I fully intend to do so. That said, I can share my general thoughts. These are subject to change once I've done a little more work. It's just my initial thinking.

In PDF, it's really hard to know for sure what kind of thing something is because there are so many ways that people can violate the spec without breaking various readers. For example, all previous attempts at asserting whether something was a page have failed. `/Contents` is optional. While `/Type /Page` is mandatory, no decent reader enforces it. I've seen `/Type (Page)`, no `/Type` field at all, and `/type /page` in the wild. Mostly the only thing I've found to be sensible is to treat any dictionary as anything you want to treat it as and just to have sensible defaults for things that aren't there. While this would allow for some preposterous results from odd coding errors, it would also allow a much greater array of broken files to be processed with much less explicit effort on the part of the programmer. I will say that the significant majority of changes I've made to qpdf in the last few years have been in the areas of making it more tolerant of more and more different types of broken files.

The questions I would want to resolve would be around how much to encode things into the C++ class structure and how much to come up with some softer way of treating things differently. To help think this through, I would study the various methods in QPDFObjectHandle and QPDF around pages and see how those things could have been done with a higher-level interface. I'm not sure whether this would result in something like a QPDFPage class or in something else. I want to design an interface that makes it easy for people working on the library to add interfaces that are in turn easy for developers to use safely. Lots of the changes for qpdf 8 were of this nature: calling a method on one object that was intended to be called on a different type of object returns a sensible default instead of throwing an exception or raising an assertion failure. The main place where I get hung up is that qpdf was never conceived as a library for manipulating PDF files at this level, and if I'm going to extend it to do that, I want to do it in a relatively future-proof way so I don't get stuck with a bunch of APIs that I don't like.

The way I work is that, once I've coded it up with the existing QPDFObjectHandle based interface, I would probably have a strong feeling about I wish I could have coded it, and that would be the basis for a higher-level API. I usually do this once I've had three different examples. Pages and form fields could be two. There are also outstanding requests to do stuff with embedded files and article threads. Working all these would probably give me a good feel for what we need that would strike the right balance between not being too rigid but offering more convenience than dealing with raw dictionaries all the time. Also, some common constructs such as trees with inheritible fields could probably be provided in a somewhat more general way.

Anyway, it's all stuff to think about it, and I anticipate that I should be able to do the required deep dive in the next few weeks.

**Comment by jberkenbilt** [comment] 2018-06-18 14:50
@sahilarora535 Sahil, I've now had a chance to read through everything in all the various email threads and issues. I have to commend you on your handling of this information. You did a great and extremely helpful job of capturing the relevant information into this ticket.

**Comment by jberkenbilt** [comment] 2018-06-18 15:35
I've now had a chance to fully digest all this information and that from other issues and email threads. All the relevant information from the private email threads appears to be incorporated into this issue or #72. The only thing that I am really not sure how to do with is potentially adding code to fill in form fields that can handle characters I will refer to as *extended characters*: those that can't be represented with PDF Doc Encoding (ASCII + a few extras). In this case, you must use an appearance stream, and that stream must include use of a font that has the characters that need to be rendered. This is typically handled by partially embedding a font to include only the required glyphs and using a character mapping. QPDF doesn't have any code in it that knows how to do that, and I don't see a way to do that without adding a dependency on libraries that can manipulate true type fonts. Anyway, I don't think we'll get quite that far. For now, it may be left up to the library user to handle making sure the file does everything it needs to do to actually process any appearance streams that are created. I will discuss my other thinking in an additional comment.

**Comment by smilingthax** [comment] 2018-06-18 16:32
Well, the basic idea is that the pdf/form creation application will make sure, that an appropriate font is assigned (appropriate resource is used for the `Tf` operator in `/DA`) to the form field - i.e. either one of the Standard-14 fonts (containing only ASCII + X), or a font *not* heavily subsetted. As long as one does not create a new form field and use a new font, qpdf should simply expect that the assigned font is appropriate. AFAIK Adobe Reader will simply leave an empty space for each character entered into a form, that is not included in the assigned font.

When an application uses qpdf to create an entirely new form, it is responsible for appropriately embedding a font (or use one of the standard-14 fonts), just as it is, when it adds text in "font such-and-such" to a page (e.g. my texttopdf implementation of cups-filters includes a custom "libfontembed" for exactly that purpose). 

AFAIUI the whole idea of pdf font dictionaries containing a `/Widths` array is to be able to calculate the positions and widths of strings using that particular font without having to go to the data structures inside the binary font blob. One still has to deal with the `/Encoding`, though.

**Comment by jberkenbilt** [comment] 2018-06-18 16:45
@smilingthax Your description matches what I have in mind. I'm glad we're on the same page, so to speak. In general, I have noticed that it is possible to enter arbitrary unicode characters into a text form field, and that most applications capable of handling form fields will not render the fields properly in this case. In those cases, if you click on the form field so that the field's value (`/V`) is rendered by the application for editing, you will see all the characters, but if you remove focus from the field, it will appear blank. If you use Adobe Acrobat to fill in the form, it will actually embed the required fonts, optimally subsetted, for you and generate appearance streams that render the field with those fonts. This is a level of complexity that I don't expect qpdf to support for the foreseeable future. However, I see no problem supporting the case you describe in which the file already has a font in it that already has the characters that are needed.

**Comment by jberkenbilt** [comment] 2018-06-18 17:13
This comment describes my thinking about higher level APIs.

# Background

One of the defining properties of the QPDF APIs is that they abstract away from the user lexical and grammatical aspects of the PDF file but do not attempt to shield the user from semantics. Users of QPDF don't have to be concerned in general with the distinction between direct and indirect objects, alternative syntaxes for equivalent things (different string and name representations, for example), whether or not the file is using object streams, encryption, compression, cross reference tables, etc. But they are directly concerned and always have direct access to things like actual dictionary keys, arrays, or any other details that have to do with the semantic meaning of the file.

At present, there are a small number of places where qpdf provides helper methods. These are all defined either in QPDF.hh or QPDFObjectHandle.hh. The helper methods are intended to work with certain types of objects but don't generally enforce this. They provide only a light level of help, still requiring the user to be mostly concerned with the details.

My goal is to provide some kind of higher level APIs that make it easier for a user to work with certain aspects of PDF structure without having to be as concerned about the implementation details within the PDF, but such APIs should not preclude access to this detail and should be fully interoperable with all existing APIs. It should also be possible to add new higher level APIs and to extend existing ones to add more functionality with negatively impacting older code, and the pattern established by the APIs should make it relatively obvious how to extend or write new APIs for future cases. Since I have limited time to work on qpdf and there are no other regular contributors, this has to support the gradual, incremental creation of such APIs in a manner that doesn't break source compatibility and ideally doesn't mess up binary compatibility either.

# Overall Structure

I am going to introduce the concept of `Helper` objects into the QPDF API. In most cases, the kinds of things that helper objects are useful for are things that have some representation at the overall document level but are also implemented with specific regular objects that take on certain characteristics. The structure of the helper classes will reflect this. Obvious examples of this kind of helper would be page helpers and form helpers. It likely also makes sense to have helpers for article threads and file attachments. Basically anything where you start at the document catalog, traverse structures, and land at objects that are referenced in other places would fit this pattern.

In some cases, it probably makes sense to create helpers that operate only at the object level and not at the document level. Maybe fonts or images are like this. I guess it's possible that some document-level helpers without object-level helpers may also make sense, though I'm not thinking off hand of any obvious use cases.

What I will probably do is to create two new abstract classes: `QPDFDocumentHelper` and `QPDFObjectHelper`. These will be minimal and will just establish the patterns for getting access to the underlying documents or object handles. From this, we would derive classes like `QPDFPageDocumentHelper` and `QPDFPageObjectHelper`.

A document helper would be initialized with a reference to qpdf object and would have methods that would work with the object helpers. An object helper would be initialized typically with a `QPDFObjectHandle` and would have methods to work with that object in specific ways. It will always be possible to retrieve the underling `QPDF` or `QPDFObjectHandle` so that it is easy to do things that aren't fully supported without having to abandon the helpers, and if the helpers are extended in the future, it will result in small code changes to existing code that is already using the helpers.

I will have the document and object helper classes exist on their own and not be known by underlying `QPDF` and `QPDFObjectHandle` classes. As such, the things they do will be constrained to only operate on public methods of the underying objects. This is important for two reasons: one is that it forces me to ensure that the public APIs of the underlying objects are rich enough to directly handle whatever the use case is, and the other is that it makes it easier for application authors to follow the pattern in their own code and to write their own helpers. I think this will also make it easier for users to contribute helper objects to QPDF.

# Example helpers

The most obvious example of helpers would be for pages. The next one, relevant to this ticket, is for forms. What I will probably do is spike out this idea by writing document and object helpers for pages and providing ways through those helpers to do the things that are currently provided by `QPDF` and `QPDFObjectHandle`. That exercise should help me solidify whether I like this approach. Once done, I can start building helper classes for forms.

Comments welcome. When I get far enough to have something to review, I'll create a branch and maybe a pull request that we can comment on.

**Comment by jberkenbilt** [comment] 2018-06-18 21:15
I have converted the pages APIs over to the handler system. I deviated a little from above in that the document helpers do not use the object helpers because I wanted to keep the APIs the same. The new API is a little more cumbersome than the old one in that you have to create an extra object, but I think in the long run it will be better because it will allow some state to be held in the helper classes and will simplify interfaces for core library classes. For page APIs, I just took 6 methods from `QPDF` and 9 from `QPDFObjectHandle` and moved them into `QPDFPageDocumentHelper` and `QPDFPageObjectHelper` respectively, while leaving the legacy versions intact. I will open a pull request for easy tracking of my changes. I'm going to take a short break and then work on a spec for `QPDFAcroFormDocumentHelper` and `QPDFAcroFormObjectHelper`.

**Comment by jberkenbilt** [comment] 2018-06-21 20:00
I'm closing this issue now. Higher level interfaces for forms that should be good enough for bannertopdf will be in 8.1, which I hope to release in the next couple of days. I'm working on a few other, unrelated issues.

**Closed by jberkenbilt** 2018-06-21 20:00 UTC
Labels: next
